class SV {
  static Map<String, String> get keys => {
        "about": "Om",
        "aboutLine1": "Detta är ett open-source projekt och kan hittas på",
        "accent": "Accentfärg & Nyans",
        "addNew": "Lägg till ny",
        "addSomething": "Gå och lägg till något",
        "addToPlaylist": "Lägg till i spellista",
        "addedBy": "Tillagd av",
        "addedTo": "Tillagd i",
        "albums": "Album",
        "addedToFav": "Tillagd i favoriter",
        "addedToPlaylists": "Tillagd i spellistor",
        "addedToQueue": "Tillagd i kö",
        "adjustSpeed": "Justera hastighet",
        "album": "Album",
        "albumArtist": "Album artist",
        "alreadyInQueue": "Redan i kön",
        "appTitle": "BlackHole",
        "artist": "Artist",
        "artists": "Artister",
        "autoBackLocation": "Auto backup plats",
        "autoBack": "Auto backup",
        "autoBackSub": "Automatiskt säkerhetskopiera data",
        "autoplay": "Autouppspelning",
        "autoplaySub": "Automatiskt lägg till relaterade låtar i kön",
        "back": "Tillbaka",
        "backNRest": "Säkerhetskopiera och återställ",
        "backupSuccess": "Säkerhetskopiering lyckades",
        "bgGrad": "Bakgrunds gradient",
        "bgGradSub": "Gradient använd som bakgrund överallt",
        "blacklistedHomeSections": "Svartlistade hemsektioner",
        "blacklistedHomeSectionsSub":
            "Sektioner med dessa titlar visas inte på hemskärmen",
        "bottomGrad": "Nedre ark gradient",
        "bottomGradSub": "Gradient som används i nedre ark",
        "buyCoffee": "Köp mig en kaffe",
        "cache": "Cache",
        "cacheSong": "Cacha låtar",
        "cacheSongSub":
            "Låtar kommer att bli cachade för framtida uppspelning. Kommer ta extra utrymme på enheten",
        "cancel": "Avbryt",
        "cantAddToQueue": "Kan inte lägga till online låt i offline kö",
        "canvasColor": "Canvas färg",
        "canvasColorSub": "Färg på bakgrundscanvas",
        "cardColor": "Kort färg",
        "cardColorSub": "Färg på sökfält, varningsdialoger, kort",
        "cardGrad": "Kort gradient",
        "cardGradSub": "Gradient använd i kort",
        "changeDefault": "Ändra till standard",
        "changeOrder": "Håll in för att byta ordning\n",
        "chartLocation": "Spotify lokala topplistors plats",
        "chartLocationSub": "Land för top Spotify lokala topplistor",
        "checkingUpdate": "Kollar efter uppdateringar…",
        "checkUpdate": "Skanna automatiskt efter uppdateringar",
        "clear": "Rensa",
        "clearAll": "Rensa allt",
        "clearCache": "Rensa cachade detaljer",
        "clearCacheSub":
            "Raderar cachade detaljer inkluderat Hemsidan, Spotify toplistor, YouTube och senaste sessiondata. Vanligtvis raderar appen detta automatiskt när det börjar ta mycket plats\n",
        "confirmViewable": "Försäkra att spelistan är visningsbar",
        "connectingRadio": "Ansluter till radio…",
        "contactUs": "Kontakta oss",
        "contactUsSub": "Feedback uppskattas!",
        "convertingSongs": "Konverterar låtar",
        "copied": "Kopierat till urklipp!",
        "copy": "Kopiera",
        "countryQue":
            "För vilket land skulle du vilja se Spotify lokala topplistor?",
        "createAlbumFold": "Skapa mapp för nedladdade album & spellistor",
        "createAlbumFoldSub":
            "Skapar mapp för låtar när album eller spellista är nedladdad",
        "createBack": "Skapa säkerhetskopia",
        "createBackSub": "Skapa säkerhetskopia av din data",
        "createNewPlaylist": "Skapa ny spellista",
        "createPlaylist": "Skapa spellista",
        "createYtFold": "Skapa en annan mapp för YouTube nedladdningar",
        "createYtFoldSub":
            "Skapar en annan mapp för låtar nedladdade från YouTube",
        "currentTheme": "Nuvarande tema",
        "date": "Datum",
        "dec": "Minskande",
        "delete": "Radera",
        "deleted": "Raderad",
        "deleteTheme": "Radera tema",
        "deleteThemeSubtitle": "Är du säker på att du vill radera?",
        "disclaimer": "Anvarsfriskrivning:",
        "displayName": "Visningsnamn",
        "donateGpaySub":
            "Minsta mängd gör mig glad :)\nTryck för att donera eller håll in för att kopiera UPI ID",
        "down": "Ladda ner",
        "downAgain": "existerar redan.\nVill du ladda ner den igen?",
        "downDone": "Nedladdning klar",
        "downFilename": "Namnformat för nedladdning",
        "downFilenameSub":
            "Låtar kommer att laddas ner enligt detta filnamnsformat",
        "downLocation": "Nedladdningsplats",
        "downLyrics": "Ladda ner låttext",
        "downLyricsSub": "Ladda ner låttext med låten, om tillgänglig",
        "downQualitySub": "Högre kvalitet använder mer lagringsutrymme",
        "downed": "har blivit nedladdad",
        "duration": "Varaktighet",
        "enableGesture": "Aktivera gester för konstverk",
        "enforceRepeat": "Påtvinga upprepning",
        "aboard": "Ombord",
        "aboutLine2": "Om du gillar mitt arbete\nvisa lite ♥ och ⭐ repot",
        "addToQueue": "Lägg till i kö",
        "alphabetical": "Alfabetisk",
        "alreadyExists": "Existerar redan",
        "checkUpdateSub":
            "Om du laddade ner BlackHole från ett apprepositorie som 'F-Droid', 'IzzyOnDroid', etc. som tillhandahåller sina egna uppdateringsalternativ, låt denna inställning vara AV. Medan, om du laddade ner BlackHole från 'GitHub' eller en annan källa som inte tillhandahåller automatiska uppdateringar, slå på denna inställning så du kan få information om nya uppdateringar.\n",
        "darkMode": "Mörkt läge",
        "dateAdded": "Datum tillagd",
        "downQuality": "Nedladdningskvalite",
        "enableGestureSub":
            "Aktiverar tryck, nerhållning, swipe, etc. på konstverket i mediaspelaren",
        "disclaimerText":
            "Vi respekterar din integritet mer än någonting annat. Enbart ditt namn, som du matar in här, kommer sparas.",
        "donateGpay": "Donera med GPay",
        "downingAlbum": "Laddar ner album",
        "downs": "Nedladdningar",
        "downloadSomething": "Ladda ner någonting",
        "edit": "Redigera",
      };
}
