class IT {
  static Map<String, String> get keys => {
        "about": "Informazioni",
        "aboutLine1":
            "Il codice sorgente di questo progetto è aperto e può essere trovato su",
        "accent": "Colore e tonalità di accento",
        "addNew": "Aggiungi nuovo",
        "addSomething": "Vai e aggiungi qualcosa",
        "aboard": "a bordo",
        "addToQueue": "Aggiungi alla coda",
        "addedTo": "Aggiunto a",
        "addedToFav": "Aggiunto ai preferiti",
        "album": "Album",
        "alphabetical": "Alfabetico",
        "alreadyInQueue": "Già in coda",
        "artist": "Artista",
        "autoBack": "Backup automatico",
        "back": "Indietro",
        "backNRest": "Backup e ripristino",
        "buyCoffee": "Comprami un caffè (donazione)",
        "cancel": "Annulla",
        "cardColor": "Colore della carta",
        "year": "Anno",
        "yes": "Sì",
        "yesReplace": "Sì, ma sostituisci il vecchio",
        "willPlayNext": "viene poi giocato",
        "viewArtist": "Vedi l'artista",
        "useVpn": "Non dall'India? Prova a usare una VPN con un server indiano",
        "addToPlaylist": "Aggiungi alla playlist",
        "addedBy": "Aggiunto da",
        "addedToPlaylists": "Aggiunto alle playlist",
        "cardColorSub":
            "Colore della barra di ricerca, finestre di avviso, schede",
        "addedToQueue": "Aggiunto alla coda",
        "adjustSpeed": "Regola la velocità",
        "albumArtist": "Artista dell'album",
        "albums": "Album",
        "alreadyExists": "Esiste già",
        "appTitle": "BlackHole",
        "artists": "Artisti",
        "backupSuccess": "Backup riuscito",
        "bgGrad": "Sfumatura di sfondo",
        "cache": "Cache",
        "welcome": "Benvenuto/a",
        "version": "Versione",
        "useDown": "Canzoni scaricate in streaming, se disponibili",
        "bgGradSub": "Gradiente usato come sfondo ovunque",
        "aboutLine2":
            "Se ti è piaciuto il mio lavoro\nmostra un po' di ♥ e ⭐ il repo",
        "autoplay": "Riproduzione automatica",
        "autoplaySub":
            "Aggiungi automaticamente le canzoni correlate alla coda",
        "autoBackSub": "Backup automatico dei dati",
        "blacklistedHomeSectionsSub":
            "Le sezioni con questi titoli non saranno mostrate nella schermata principale",
        "cacheSong": "Canzoni nella cache",
        "cantAddToQueue":
            "Non è possibile aggiungere una canzone online a una coda di riproduzione offline",
        "changeDefault": "Ripristina le impostazioni di default",
        "changeOrder": "Tieni premuto per cambiare ordine\n",
        "checkingUpdate": "Ricerca aggiornamenti…",
        "checkUpdate": "Aggiornamenti automatici",
        "checkUpdateSub":
            "Se hai scaricato BlackHole da uno store alternativo come F-Droid, IzzyOnDroid o altri che permettono aggiornamenti automatici, tieni questa spunta disattivata. Invece, se hai scaricato l'app da GitHub o altre fonti che non permettono aggiornamenti automatici, mantieni questa spunta attivata per poter ricevere notifiche quando è disponibile un aggiornamento\n",
        "clear": "Pulisci",
        "clearAll": "Pulisci tutto",
        "downLyrics": "Scarica i testi",
        "downLyricsSub":
            "Scarica il testo insieme alla canzone, se disponibili",
        "ytDownQuality": "Qualità scaricamento YouTube",
        "contactUsSub": "I commenti sono apprezzati!",
        "convertingSongs": "Converti canzoni",
        "copy": "Copia",
        "countryQue":
            "Vuoi visualizzare le classifiche di Spotify di quale paese?",
        "createBack": "Crea un backup",
        "createBackSub": "Crea un backup dei tuoi dati",
        "createNewPlaylist": "Crea una nuova playlist",
        "createPlaylist": "Crea una playlist",
        "currentTheme": "Tema selezionato",
        "date": "Data",
        "deleteTheme": "Elimina tema",
        "deleted": "Eliminato",
        "donateGpay": "Dona con GPay",
        "downAgain": "esiste già.\nVuoi riprovare a scaricarlo?",
        "downDone": "Download completato",
        "edit": "Modifica",
        "enterName": "Inserisci il tuo nome",
        "exitConfirm": "Premi di nuovo per uscire",
        "export": "Esporta",
        "favorites": "Preferiti",
        "favSongs": "Brani preferiti",
        "ytStreamQuality": "Qualità streaming YouTube",
        "youTube": "YouTube",
        "watchVideo": "Guarda il video",
        "viewAll": "Visualizza tutto",
        "viewAlbum": "Visualizza album",
        "genre": "Genere",
        "genres": "Generi",
        "useSystemTheme": "Usa tema del sistema",
        "ytDownQualitySub":
            "Una qualità più alta utilizza più spazio sul disco",
        "cacheSongSub":
            "Le canzoni verranno salvate nella cache per essere riprodotte in seguito. Sarà utilizzato spazio sul dispositivo",
        "versionSub": "Premi per cercare aggiornamenti",
        "copied": "Copiato negli appunti!",
        "ytStreamQualitySub": "Una qualità più alta utilizza più dati",
        "ytLiveAlert":
            "Il video è in diretta o si è verificato un errore. Attendere il termine del flusso live o riprovare.",
        "contactUs": "Contattaci",
        "delete": "Elimina",
        "confirmViewable": "Assicurati che la playlist sia pubblica",
        "darkMode": "Tema scuro",
        "deleteThemeSubtitle": "Sei sicuro/a di voler eliminare?",
        "disclaimerText":
            "Rispettiamo la tua privacy più di qualsiasi altra cosa. Solo il tuo nome che inserisci qui sarà registrato.",
        "blacklistedHomeSections": "Sezioni di casa in lista nera",
        "bottomGrad": "Fogli di fondo Gradiente",
        "bottomGradSub": "Gradiente usato nei fogli inferiori",
        "canvasColor": "Colore tela",
        "canvasColorSub": "Colore della tela di sfondo",
        "chartLocation": "Posizione Canzoni Locali Spotify",
        "chartLocationSub": "Paese per le top locali di Spotify",
        "clearCache": "Pulisci Dettagli Nella Cache",
        "clearCacheSub":
            "Elimina i dettagli nella cache includendo pagina principale, classifiche Spotify, YouTube e i dati dell'ultima sessione. Solitamente l'app li cancella automaticamente quando i dati diventano troppo grandi\n",
        "connectingRadio": "Connetto alla radio…",
        "useAmoled": "Usa impostazioni modalità scura AMOLED",
        "useDenseMini": "Usa Miniplayer Dense",
        "stopDown": "Ferma lo scaricamento",
        "stopOnClose": "Ferma la musica quando chiudi l'app",
        "sleepDur": "Standby dopo hh:mm",
        "useDenseMiniSub": "L'altezza del miniplayer sarà ridotta",
        "title": "Titolo",
        "useProxy": "Usa proxy",
        "useProxySub":
            "Accendi questo se non sei indiano e stai avendo problemi con la ricerca, per esempio se trovi solo canzoni indiane o non trovi alcun risultato, puoi anche usare una VPN indiana\n",
        "upNext": "Prossimo",
        "useDominant":
            "Usa il colore dominante per la schermata di riproduzione",
        "useDominantSub":
            "Il colore dominante dall'immagine sarà usato per lo sfondo della schermata di riproduzione. Se spento, il gradiente predefinito sarà usato",
        "no": "No",
        "ok": "OK",
        "downFilename": "Formato del nome di scaricamento",
        "downFilenameSub":
            "Le canzoni saranno scaricate secondo questo formato di nome di file",
        "downLocation": "Posizione degli scaricamenti",
        "ipAdd": "Indirizzo IP",
        "joinTg": "Unisciti a noi su Telegram",
        "miniButtons": "Pulsanti da mostrare nel mini lettore",
        "minAudioLenSub":
            "Gli audio con lunghezza inferiore a questa non saranno mostrati nella sezione «La mia musica»",
        "madeBy": "Fatto con ♥ da Ankit Sangwan",
        "minAudioAlert": "Lunghezza minima dell'audio (in s)",
        "minAudioLen": "Lunghezza minima dell'audio per cercare la musica",
        "playing": "In riproduzione",
        "playingCap": "In riproduzione",
        "playNext": "Ascolta dopo",
        "playSomething": "Riproduci qualcosa",
        "showHistorySub":
            "Mostra la cronologia di ricerca sotto la barra di ricerca",
        "showHere": "Mostra qui",
        "showHistory": "Mostra la cronologia di ricerca",
        "updateAvailable": "Aggiornamento disponibile!",
        "upiCopied": "ID UPI copiato!",
        "update": "Aggiorna",
        "displayName": "Nome visualizzato",
        "down": "Scarica",
        "donateGpaySub":
            "Ogni piccola somma mi fa sorridere :)\nTocca per donare o premi a lungo per copiare l'ID UPI",
        "downQuality": "Qualità dello scaricamento",
        "downQualitySub": "Una qualità più alta usa più spazio su disco",
        "downed": "è stato scaricato",
        "downingAlbum": "Scaricamento dell'album",
        "downloadSomething": "Scarica qualcosa",
        "downs": "Scaricamenti",
        "duration": "Durata",
        "lastAdded": "Ultimo aggiunto",
        "lang": "Lingua",
        "share": "Condividi",
        "savePlaylist": "Salva la playlist",
        "saveTheme": "Salva il tema",
        "search": "Ricerca",
        "trendingSearch": "Tendenze",
        "ui": "Interfaccia utente",
        "undo": "Annulla",
        "unknown": "Sconosciuto",
        "autoBackLocation": "Posizione del backup automatico",
        "createAlbumFold":
            "Crea una cartella per lo scaricamento di album e playlist",
        "createAlbumFoldSub":
            "Crea una cartella comune per le canzoni quando si scarica un album o una playlist",
        "createYtFold":
            "Crea una cartella diversa per gli scaricamenti di YouTube",
        "createYtFoldSub":
            "Crea una cartella diversa per le canzoni scaricate da YouTube",
        "dateAdded": "Data di aggiunta",
        "dec": "Decrescente",
        "enterSongsCount": "Inserisci il numero di canzoni",
        "enterText": "Inserisci testo",
        "enterThemeName": "Inserisci il nome del tema",
        "equalizer": "Equalizzatore",
        "excluded": "Escluso",
        "excludedDetails":
            "I brani delle cartelle selezionate non saranno mostrati",
        "exported": "Esportato",
        "failedCreateBackup": "Impossibile creare il backup",
        "failedDelete": "Impossibile eliminare",
        "failedExport": "Impossibile esportare",
        "from": "da",
        "getLyricsOnline": "Cerca i testi delle canzoni locali",
        "getLyricsOnlineSub":
            "Cerca in linea se i testi non sono disponibili/scaricati per qualsiasi canzone fuori linea",
        "langQue": "Quali canzoni in lingua preferisci ascoltare?",
        "langSub": "Lingua del testo dell'app",
        "lastModified": "Ultima modifica",
        "lastSession": "Ultima sessione",
        "musicLang": "Lingua della musica",
        "miniButtonsSub":
            "Tocca per cambiare i pulsanti mostrati nel mini lettore",
        "lyrics": "Testo",
        "local": "Locale",
        "latest": "Congratulazioni! Stai usando l'ultima versione :)",
        "library": "Biblioteca",
        "like": "Mi piace",
        "likedWork": "Ti è piaciuto il mio lavoro?",
        "live": "IN DIRETTA",
        "playlists": "Playlist",
        "pause": "Pausa",
        "play": "Riproduci",
        "nowPlaying": "In riproduzione",
        "or": "O",
        "others": "Altri",
        "nothingIs": "Niente è ",
        "nothingPlaying": "Niente è in riproduzione",
        "restore": "Ripristina",
        "showQr": "Mostra il codice QR",
        "showLast": "Mostra l'ultima sessione",
        "showLastSub": "Mostra l'ultima sessione nella schermata principale",
        "selectDur": "Seleziona una durata",
        "selectExportLocation": "Seleziona la posizione di esportazione",
        "selectJsonImport": "Seleziona il file JSON da importare",
        "settings": "Impostazioni",
        "shareApp": "Condividi l'app",
        "shareAppSub": "Fai sapere ai tuoi amici di noi",
        "shareAppText":
            "Ehi, dai un'occhiata a questa fantastica app per la riproduzione di musica",
        "selectBackLocation": "Seleziona la posizione di backup",
        "selectDownLocation": "Seleziona la posizione degli scaricamenti",
        "searchVideo": "Ricerca la video",
        "searchYt": "Cerca su YouTube",
        "restoreSub":
            "Ripristina i tuoi dati dal backup.\nPotrebbe essere necessario riavviare l'app\n",
        "resultsNotFound": "Risultati non trovati",
        "searchHome": "Pagina ricerche",
        "searchText": "Canzoni, album o artisti",
        "selectBackFile": "Seleziona un file di backup",
        "proxySet": "Impostazioni proxy",
        "proxySetSub": "Cambia l'IP e la porta del proxy",
        "rememberChoice": "Ricorda la mia scelta",
        "remove": "Rimuovi",
        "removed": "Rimosso",
        "removedFrom": "Rimosso da",
        "removedFromFav": "Rimosso dai preferiti",
        "rename": "Rinomina",
        "reset": "Azzera",
        "prefReq": "Ti dispiace dirci alcune cose?",
        "port": "Porta",
        "streamQuality": "Qualità del flusso",
        "size": "Dimensioni",
        "skipPrevious": "Salta precedente",
        "skip": "Salta",
        "sleepTimerSetFor": "Temporizzatore impostato per",
        "songInfo": "Info canzone",
        "songPath": "Percorso canzone",
        "themeSaved": "Tema salvato!",
        "tgCh": "Canale Telegram",
        "tgGp": "Gruppo Telegram",
        "streamQualitySub": "Una qualità superiore utilizza più dati",
        "successTagEdit": "Etichette modificate con successo!",
        "songs": "Canzoni",
        "sorry": "DISPIACE",
        "spotifyCharts": "Classifiche Spotify",
        "spotifyPublic": "Spotify pubblico",
        "spotifyTopCharts": "Classifiche Spotify",
        "yourPlaylists": "Le tue playlist",
        "finish": "Termina",
        "enforceRepeatSub":
            "Mantieni la stessa opzione di ripetizione per ogni sessione",
        "sponsor": "Sponsorizza questo progetto",
        "musicPlayback": "Musica e riproduzione",
        "minutes": "minuti",
        "failedImport": "Impossibile importare",
        "useDownSub":
            "Se la canzone è già stata scaricata, la canzone scaricata sarà riprodotta invece dello streaming in linea",
        "enterPlaylistLink": "Inserisci il collegamento della playlist",
        "failedTagEdit": "Impossibile modificare le etichette",
        "fetchingStream": "Recupero del flusso audio",
        "sleepAfterSub":
            "La musica si fermerà dopo aver riprodotto il numero selezionato di canzoni",
        "theme": "Tema",
        "song": "Canzone",
        "unlike": "Non mi piace più",
        "sleepDurSub": "La musica si fermerà dopo la durata selezionata",
        "sleepAfter": "Dormi dopo N canzoni",
        "themeDeleted": "Tema eliminato!",
        "sleepTimer": "Temporizzatore",
        "stopOnCloseSub":
            "Se disattivato, la musica non si fermerà anche dopo che l'app è «chiusa», fino a quando si preme il pulsante di arresto. Questa opzione è per quando l'app è chiusa, non quando l'app è nello sfondo. La musica verrà sempre riprodotta in sfondo, non c'è bisogno di cambiare alcuna impostazione per questo.\n",
        "noFolderSelected": "Nessuna cartella selezionata",
        "skipNext": "Salta prossimo",
        "playlistShareText": "Date un'occhiata alla mia playlist!",
        "showPlaylists": "Mostra le playlist sulla schermata principale",
        "popularity": "Popolarità",
        "noLangSelected":
            "Nessuna lingua musicale selezionata. Seleziona una lingua per vedere le canzoni nella schermata principale",
        "notAvailable": "Non disponibile",
        "nothingTo": "Niente da ",
        "musicLangSub":
            "Per visualizzare le canzoni sulla schermata principale",
        "myMusic": "La mia musica",
        "moreInfo": "Più info",
        "importJioSaavn": "Importa da JioSaavn",
        "included": "Incluso",
        "playerScreenBackground": "Schermata di sfondo del lettore musicale",
        "playerScreenBackgroundSub":
            "Lo sfondo selezionato sarà mostrato nella pagina del lettore musicale",
        "cardGrad": "Gradiente della carta",
        "insta": "Instagram",
        "useHome":
            "Usa la sezione principale per miglior qualità e supporto di scaricamento",
        "joinTgSub": "Vuoi provare la versione beta? Unisciti ora!",
        "enableGesture": "Abilita gesti",
        "includeExcludeFolderSub":
            "Includi/Escludi cartelle selezionate dalla sezione «La mia musica»",
        "shuffle": "A caso",
        "supportEqSub":
            "Mantieni disabilitato se non riesci a sentire le canzoni (sia in modalità in linea che fuori linea)",
        "tg": "Telegram",
        "liveSearchSub": "Ricerca canzoni appena l'utente smette di scrivere",
        "playRadio": "Riproduci la radio",
        "disclaimer": "Avviso:",
        "includedDetails":
            "Saranno mostrate solo canzoni dalle cartelle selezionate",
        "liveSearch": "Ricerca in diretta",
        "cardGradSub": "Gradiente usato nelle carte",
        "enforceRepeat": "Imponi ripetizione",
        "topCharts": "Classifiche principali",
        "loadLast": "Carica ultima sessione all'avvio dell'app",
        "loadLastSub":
            "Carica automaticamente l'ultima sessione all'avvio dell'app",
        "resetOnSkipSub":
            "Riproduci dall'inizio invece che saltare la canzone precedente",
        "enableGestureSub":
            "Abilita tocco, pressione, scorrimento, ecc. sull'immagine nella schermata del lettore musicale",
        "useBlurForNowPlayingSub":
            "Sarà usato blur con opacità minore come lo sfondo della sezione «In riproduzione»",
        "importYt": "Importa da YouTube",
        "resetOnSkip": "Riproduci su Salta precedente",
        "inc": "In aumento",
        "includeExcludeFolder": "Includi/Escludi cartelle",
        "gmail": "Gmail",
        "getStarted": "Inizia",
        "global": "Globale",
        "guest": "Anonimo",
        "home": "Pagina principale",
        "homeGreet": "Ciao,",
        "importFile": "Importa da un file",
        "importPublicPlaylist": "Importa una paylist pubblica",
        "importResso": "Importa da Resso",
        "importSpotify": "Importa da Spotify",
        "importSuccess": "Importato con successo",
        "supportEq": "Supporta l'equalizzatore",
        "importPlaylist": "Importa una playlist",
        "mergePlaylists": "Unisci le playlist",
        "top": "In alto",
        "viral": "Virale",
        "openInSpotify": "Apri in Spotify",
        "signInSpotify": "Accedi a Spotify",
        "shareLogs": "Condividi i registri",
        "shareLogsSub": "Condividi i registri delle sessioni correnti",
        "radio": "Radio",
        "cantFind": "Non riesci a trovare quello che stai cercando? ",
        "showTopCharts": "Mostra le classifiche principali",
        "showTopChartsSub":
            "Mostra le classifiche principali nella home screen",
        "mostPlayedSong": "Canzone più ascoltata",
        "stats": "Statistiche",
        "songsPlayed": "Canzoni riprodotte",
        "compactNotificationButtonsSub":
            "Pulsanti da mostrare nella visualizzazione compatta delle notifiche",
        "compactNotificationButtons": "Pulsanti di notifica compatti",
      };
}
