class OR {
  static Map<String, String> get keys => {
        "about": "ବିଷୟରେ",
        "alreadyInQueue": "ପୂର୍ବରୁ ଧାଡିରେ ଅଛି",
        "aboutLine1": "ଏହା ଏକ ମୁକ୍ତ ଉତ୍ସ ପ୍ରୋଜେକ୍ଟ ଏବଂ ଏହା ଉପରେ ମିଳିପାରିବ",
        "aboutLine2": "ଯଦି ତୁମେ ମୋର କାମ ପସନ୍ଦ କର\nକିଛି ♥ ଏବଂ ⭐ ରେପୋ ଦେଖାନ୍ତୁ",
        "addedBy": "ଦ୍ୱାରା ଯୋଗ କରାଯାଇଛି",
        "addedToPlaylists": "ପ୍ଲେଲିଷ୍ଟରେ ଯୋଡା ଯାଇଛି",
        "albums": "ଆଲବମ୍ ଗୁଡ଼ିକ",
        "accent": "Accent ରଙ୍ଗ ଏବଂ ରଙ୍ଗ",
        "addNew": "ନୂତନ ଯୋଡନ୍ତୁ",
        "addSomething": "ଯାଅ ଏବଂ କିଛି ଯୋଗ କର",
        "addToPlaylist": "ପ୍ଲେ ଲିଷ୍ଟରେ ଯୋଡନ୍ତୁ",
        "addToQueue": "ଧାଡିରେ ଯୋଡନ୍ତୁ",
        "addedTo": "ସହିତ ଯୋଡା ଯାଇଛି",
        "addedToFav": "ପସନ୍ଦଗୁଡିକରେ ଯୋଡା ଯାଇଛି",
        "addedToQueue": "ଧାଡିରେ ଯୋଡା ଯାଇଛି",
        "adjustSpeed": "ବେଗ ନିୟନ୍ତ୍ରଣ କରନ୍ତୁ",
        "album": "ଆଲବମ୍",
        "albumArtist": "ଆଲବମ୍ କଳାକାର",
        "alphabetical": "ବର୍ଣ୍ଣାନୁକ୍ରମିକ",
        "alreadyExists": "ପୂର୍ବରୁ ବିଦ୍ୟମାନ ଅଛି",
        "appTitle": "କୃଷ୍ଣଗର୍ତ୍ତ",
      };
}
