class VI {
  static Map<String, String> get keys => {
        "about": "Thông tin",
        "aboutLine1":
            "Đây là một dự án mã nguồn mở và có thể được tìm thấy trên",
        "addNew": "Thêm Mới",
        "aboutLine2":
            "Nếu bạn thích dự án này\nhãy thể hiện ♥ và ⭐ repo của nó",
        "accent": "Màu nhấn & sắc thái",
        "addSomething": "Đi và thêm thứ gì đó đi",
        "addToPlaylist": "Thêm vào Danh sách phát",
        "addedToFav": "Đã thêm vào Mục yêu thích",
        "addedToPlaylists": "Đã thêm vào Danh sách phát",
        "addedToQueue": "Đã thêm vào hàng đợi",
        "adjustSpeed": "Điều chỉnh tốc độ",
        "album": "Album",
        "albumArtist": "Album Nghệ sĩ",
        "albums": "Albums",
        "alphabetical": "Thứ tự bảng chữ cái",
        "alreadyExists": "Đã tồn tại",
        "alreadyInQueue": "Đã có trong hàng đợi",
        "appTitle": "BlackHole",
        "artist": "Nghệ sĩ",
        "artists": "Các nghệ sĩ",
        "autoBack": "Tự động sao lưu",
        "autoplay": "Tự động phát",
        "buyCoffee": "Mua tôi một cốc cà phê",
        "cache": "Bộ nhớ đệm",
        "clear": "Xóa",
        "ytStreamQualitySub": "Chất lượng cao đớp nhiều dung lượng mạng",
        "ytStreamQuality": "Chất lượng phát trực tuyến trên YouTube",
        "autoBackLocation": "Vị trí tự động sao lưu",
        "autoBackSub": "Tự động sao lưu dữ liệu",
        "autoplaySub": "Tự động thêm các bài hát có liên quan vào hàng đợi",
        "backNRest": "Sao lưu và Phục hồi",
        "bgGradSub": "Gradient được sử dụng làm nền ở mọi nơi",
        "blacklistedHomeSections":
            "Các mục Trang chủ được đưa vào danh sách đen",
        "blacklistedHomeSectionsSub":
            "Các phần có các tiêu đề này sẽ không được hiển thị trên Màn hình chính",
        "bottomGrad": "Nền Gradient ở đáy",
        "cacheSong": "Bài hát trong bộ nhớ đệm",
        "cacheSongSub":
            "Các bài hát sẽ được lưu vào bộ nhớ đệm để phát lại trong tương lai. Nó sẽ ăn dung lượng thiết bị của bạn",
        "cantAddToQueue":
            "Không thể thêm bài hát trực tuyến vào hàng đợi ngoại tuyến",
        "canvasColorSub": "Màu của vải nền",
        "cardColor": "Màu thẻ",
        "cardGrad": "Thẻ Gradient",
        "cardGradSub": "Gradient được sử dụng trong thẻ",
        "chartLocation": "Vị trí bảng xếp hạng trên Spotify",
        "checkingUpdate": "Đang kiểm tra cập nhật…",
        "checkUpdate": "Tự động kiểm tra cập nhật",
        "clearAll": "Xóa tất cả",
        "clearCache": "Xóa chi tiết lưu trong bộ nhớ cache",
        "clearCacheSub":
            "Xóa các chi tiết được lưu trong bộ nhớ cache bao gồm Trang chủ, Biểu đồ hàng đầu trên Spotify, YouTube và Dữ liệu phiên cuối cùng. Thông thường, ứng dụng sẽ tự động xóa chúng khi dữ liệu trở nên siêu to khổng lồ\n",
        "connectingRadio": "Đang kết nối tới Radio…",
        "contactUs": "Liên hệ với chúng tôi",
        "contactUsSub": "Các phản hồi của bạn được đánh giá cao!",
        "convertingSongs": "Đang chuyển đổi bài hát",
        "copied": "Đã sao chép vào clipboard!",
        "copy": "Sao chép",
        "countryQue":
            "Bạn muốn xem Bảng xếp hạng địa phương trên Spotify cho quốc gia nào?",
        "createAlbumFold": "Tạo thư mục Tải xuống cho Album & Danh sách phát",
        "createAlbumFoldSub":
            "Tạo thư mục chung cho Bài hát khi Album hoặc Danh sách phát được tải xuống",
        "createBack": "Tạo bản sao lưu",
        "createBackSub": "Sao lưu các zữ liệu của bạn",
        "createNewPlaylist": "Tạo Danh sách phát mới",
        "createPlaylist": "Tạo danh sách phát",
        "createYtFold": "Tạo các thư mục Tải xuống khác nhau cho YouTube",
        "createYtFoldSub":
            "Tạo một thư mục khác cho các Bài hát được tải xuống từ YouTube",
        "currentTheme": "Theme hiện tại",
        "addedBy": "Đã thêm bởi",
        "canvasColor": "Màu canvas",
        "checkUpdateSub":
            "Nếu bạn đã tải xuống BlackHole từ bất kỳ kho ứng dụng nào như 'F-Droid', 'IzzyOnDroid', v.v. mà có cung cấp khả năng cập nhật, hãy TẮT cài đặt này. Trong khi đó, nếu bạn đã tải xuống từ 'GitHub' hoặc bất kỳ nguồn nào khác không cung cấp cập nhật tự động thì hãy BẬT tính năng này để nhận thông báo cập nhật\n",
        "cancel": "Hủy",
        "bgGrad": "Nền Gradient",
        "bottomGradSub": "Gradient được sử dụng ở Sheets ở đáy",
        "cardColorSub": "Màu của thanh tìm kiếm, hộp thoại cảnh báo, thẻ",
        "changeDefault": "Đặt về mặc định",
        "chartLocationSub": "Quốc gia cho Bảng xếp hạng trên Spotify",
        "changeOrder": "Nhấn và giữ để thay đổi thứ tự\n",
        "confirmViewable": "Đảm bảo rằng danh sách phát có thể xem được",
        "addToQueue": "Thêm vào Hàng đợi",
        "addedTo": "Đã thêm vào",
        "back": "Trở về",
        "backupSuccess": "Sao lưu thành công",
      };
}
