class ZH {
  static Map<String, String> get keys => {
        "autoplay": "自动播放",
        "cache": "缓存",
        "about": "关于",
        "addNew": "新建",
        "addToPlaylist": "添加到播放列表",
        "aboutLine1": "本软件为开源项目，您可以在这里找到源代码",
        "alphabetical": "按首字母排序",
        "autoBack": "自动备份",
        "aboutLine2": "如果您喜欢我的工作，记得给个star",
        "accent": "强调色 & 色调",
        "addSomething": "去添加新内容",
        "addToQueue": "添加队列",
        "addedBy": "添加方式",
        "addedToPlaylists": "已添加到播放列表",
        "addedToQueue": "已添加到队列",
        "addedTo": "已添加到",
        "addedToFav": "已添加到收藏夹",
        "adjustSpeed": "调整速度",
        "album": "专辑",
        "albumArtist": "艺人专辑",
        "albums": "专辑",
        "alreadyExists": "已存在",
        "alreadyInQueue": "已在队列中",
        "appTitle": "黑洞",
        "artist": "艺术家",
        "artists": "艺术家",
        "autoBackSub": "自动备份数据",
        "autoplaySub": "自动将相关歌曲加入队列",
        "live": "正在直播",
        "liveSearch": "立即搜索",
        "no": "无",
        "notAvailable": "不可用",
        "others": "其他",
        "playingCap": "正在播放",
        "remove": "移除",
        "removed": "已移除",
        "restoreSub": "从备份文件中恢复数据\n您需要在恢复成功后重启应用\n",
        "like": "收藏",
        "downFilenameSub": "下载的歌曲将使用该命名格式",
        "downloadSomething": "下载一些内容",
        "edit": "编辑",
        "enableGestureSub": "在播放界面开启点击、长按、滑动等手势",
        "enableGesture": "开启播放手势",
        "enforceRepeat": "强制重复选项",
        "enterName": "输入昵称",
        "enterPlaylistLink": "输入播放列表链接",
        "enterSongsCount": "输入歌曲数量",
        "enforceRepeatSub": "对每个界面保持相同的重复选项",
        "equalizer": "均衡器",
        "excluded": "已排除",
        "excludedDetails": "已选择的文件夹中的歌曲不会显示",
        "export": "导出",
        "failedExport": "导出失败",
        "failedImport": "导入失败",
        "failedTagEdit": "编辑标签失败",
        "favorites": "收藏夹",
        "favSongs": "我喜欢的音乐",
        "fetchingStream": "正在获取音频流",
        "finish": "结束",
        "genre": "类型",
        "genres": "类型",
        "getStarted": "开始使用",
        "global": "全球",
        "gmail": "Gmail",
        "guest": "留言",
        "home": "主页",
        "homeGreet": "你好，",
        "importFile": "从文件导入",
        "importPublicPlaylist": "导入公开播放列表",
        "importSuccess": "导入成功",
        "importYt": "从 YouTube 导入",
        "inc": "增序",
        "includeExcludeFolder": "包括/不包括文件夹",
        "includeExcludeFolderSub": "包括/不包括 '我的音乐' 中选则的文件夹",
        "includedDetails": "仅显示选中的文件夹中的音乐",
        "insta": "Instagram",
        "ipAdd": "IP 地址",
        "lastSession": "最近收听",
        "latest": "当前版本已是最新",
        "library": "音乐库",
        "likedWork": "支持开发",
        "liveSearchSub": "用户停止输入后立即搜索",
        "loadLastSub": "应用开启时自动转到上次开启的界面",
        "loadLast": "应用开启时转到上次开启的界面",
        "local": "本地",
        "lyrics": "歌词",
        "madeBy": "开发者：Ankit Sangwan",
        "minAudioAlert": "最小音频长度（单位：秒）",
        "minAudioLen": "搜索音乐的最小音频长度",
        "minAudioLenSub": "长度小于该值的音频不会显示在 '我的音乐' 界面",
        "minutes": "分钟",
        "moreInfo": "更多信息",
        "musicLang": "音乐语言",
        "musicLangSub": "在主页显示歌曲",
        "musicPlayback": "音乐 & 播放列表",
        "myMusic": "我的音乐",
        "noFolderSelected": "尚未选择文件夹",
        "noLangSelected": "尚未选择我音乐语言。请选择您想听的音乐语言",
        "nothingIs": "暂无 ",
        "or": "二维码",
        "playing": "播放的歌曲",
        "playSomething": "去播放点东西吧",
        "pause": "暂停",
        "play": "播放",
        "miniButtons": "音乐通知界面按钮",
        "playNext": "播放下一首",
        "playlistShareText": "看看我的播放列表吧！",
        "playlists": "播放列表",
        "popularity": "热门",
        "port": "端口",
        "proxySet": "代理设置",
        "proxySetSub": "修改代理 IP 和端口",
        "rememberChoice": "记住选择",
        "removedFrom": "已移除自",
        "reset": "重置",
        "restore": "恢复",
        "resultsNotFound": "未找到结果",
        "savePlaylist": "保存播放列表",
        "saveTheme": "保存主题",
        "searchHome": "搜索主页",
        "settings": "设置",
        "share": "分享",
        "shareApp": "分享应用",
        "shareAppText": "嘿，快看看这个第三方音乐 APP",
        "showHistorySub": "在搜索栏下方显示搜索历史",
        "showLast": "显示最近播放",
        "showQr": "显示二维码",
        "shuffle": "拖动",
        "size": "大小",
        "skip": "跳过",
        "skipNext": "跳过下一步",
        "sleepAfterSub": "播放完指定数量后将自动暂停播放",
        "sleepDur": "持续 hh:mm 后入睡",
        "sleepDurSub": "音乐将在指定时间后暂停",
        "sleepTimer": "睡眠计时器",
        "sleepTimerSetFor": "睡眠计时器设置为",
        "song": "歌曲",
        "songInfo": "歌曲信息",
        "songPath": "歌曲路径",
        "checkingUpdate": "正在检查更新…",
        "cacheSongSub": "歌曲将进行缓存，便于后续播放。将占用设备上的额外空间",
        "cardColorSub": "搜索栏、提示框和卡片的颜色",
        "checkUpdateSub":
            "如果你是从 'F-Droid' 、 'IzzyOnDroid' 等提供自动更新的第三方存储库下载的本应用，可关闭本开关。如果是从 Github 或不提供自动更新的任何其他来源下载的本应用，请打开本开关，确保可以接受更新提醒\n",
        "createBack": "创建备份",
        "date": "日期",
        "createBackSub": "备份您的数据",
        "createNewPlaylist": "新建播放列表",
        "createPlaylist": "新建播放列表",
        "createYtFold": "为 YouTube 下载的内容创建不同的文件夹",
        "createYtFoldSub": "为 YouTube 下载的内容创建不同的文件夹",
        "currentTheme": "当前主题",
        "darkMode": "深色模式",
        "downFilename": "下载名称格式",
        "downs": "下载",
        "duration": "持续时间",
        "enterThemeName": "输入主题名称",
        "enterText": "输入文本",
        "exported": "已导出",
        "failedCreateBackup": "创建备份失败",
        "failedDelete": "删除失败",
        "from": "从",
        "joinTgSub": "想体验测试版本吗？快加入我们的频道吧！",
        "included": "包括",
        "lang": "歌曲语言",
        "importSpotify": "从 Spotify 导入",
        "joinTg": "加入 Telegram 频道/群组",
        "langSub": "应用语言",
        "lastAdded": "最近添加",
        "langQue": "您想听什么语言的歌曲？",
        "lastModified": "最近修改",
        "nothingPlaying": "暂无播放内容",
        "nothingTo": "暂无内容 ",
        "prefReq": "反馈和提出建议",
        "nowPlaying": "播放列表",
        "ok": "确定",
        "rename": "重命名",
        "showHere": "在此显示",
        "miniButtonsSub": "点击修改音乐通知界面显示的按钮",
        "removedFromFav": "已从收藏夹中移除",
        "search": "搜索",
        "shareAppSub": "向您的好友分享本应用",
        "showHistory": "显示搜索历史",
        "showLastSub": "在主页上显示最近播放",
        "skipPrevious": "跳过上一步",
        "sleepAfter": "睡眠音乐",
        "songs": "歌曲",
        "sorry": "抱歉",
        "aboard": "正在播放",
        "back": "返回",
        "backNRest": "备份 & 恢复",
        "backupSuccess": "备份成功",
        "bgGrad": "背景渐变",
        "bgGradSub": "使用全局渐变背景",
        "blacklistedHomeSections": "已·将主页部分列入黑名单",
        "blacklistedHomeSectionsSub": "包含这些标题的部分不会显示在主页",
        "bottomGrad": "底栏渐变",
        "bottomGradSub": "在底栏上使用渐变",
        "buyCoffee": "向开发者捐赠",
        "cacheSong": "缓存音乐",
        "cancel": "取消",
        "cantAddToQueue": "无法将在线歌曲添加到本地播放列表",
        "canvasColor": "背景颜色",
        "canvasColorSub": "应用主体背景颜色",
        "cardColor": "卡片颜色",
        "cardGrad": "卡片渐变",
        "cardGradSub": "卡片的渐变色",
        "changeDefault": "改为默认",
        "changeOrder": "长按修改顺序\n",
        "chartLocation": "Spotify 本地排行榜位置",
        "chartLocationSub": "Spotify 最热本地排行榜的国家/地区",
        "checkUpdate": "自动检查更新",
        "clear": "清除",
        "clearAll": "清除全部",
        "clearCache": "清除缓存内容",
        "clearCacheSub":
            "删除缓存内容，包括主页内容、Spotify 热门排行榜、YouTube 等数据。当占用空间过多时应用会自动清除数据\n",
        "connectingRadio": "正在连接至收音机…",
        "contactUs": "联系我们",
        "contactUsSub": "反馈问题或提出建议",
        "convertingSongs": "正在转换歌曲",
        "copied": "已复制到剪切板！",
        "copy": "复制",
        "countryQue": "您希望看到哪个国家的 Spotify 热门排行？",
        "createAlbumFold": "创建专辑和播放列表的下载文件夹",
        "createAlbumFoldSub": "下载专辑或播放列表时创建公共文件夹",
        "dateAdded": "已添加日期",
        "delete": "删除",
        "deleted": "已删除",
        "deleteTheme": "删除主题",
        "deleteThemeSubtitle": "是否删除？",
        "disclaimer": "免责声明：",
        "disclaimerText": "我们尊重你的隐私胜过一切。只有你在这里输入的名字会被记录下来。",
        "displayName": "显示名称",
        "donateGpay": "使用 GPay 捐赠",
        "donateGpaySub": "每一份小小的支持都让我微笑 :)\n点击显示捐赠二维码，或长按复制 UPI ID",
        "dec": "降序",
        "down": "下载",
        "downAgain": "已下载\n是否重新下载？",
        "downDone": "下载完成",
        "downLocation": "下载位置",
        "downLyrics": "下载歌词",
        "downLyricsSub": "如果有歌词，则在下载音乐的同时下载歌词",
        "downQuality": "下载音质",
        "downQualitySub": "音质越高，占用的空间越多",
        "downed": "已下载",
        "downingAlbum": "正在下载专辑",
        "exitConfirm": "再次点击返回按钮退出应用",
        "selectBackLocation": "选择备份位置",
        "selectDownLocation": "选择下载位置",
        "selectDur": "选择持续时间",
        "selectExportLocation": "选择导出位置",
        "selectJsonImport": "选择需要导入的 JSON 文件",
        "searchText": "歌曲，专辑或艺术家",
        "searchVideo": "搜索视频",
        "searchYt": "搜索 YouTube",
        "selectBackFile": "选择备份文件",
        "streamQuality": "流质量",
        "useDown": "流式播放下载的音乐（如果可用）",
        "supportEqSub": "无法播放音乐时关闭该选项（在线或离线音乐）",
        "sponsor": "赞助本项目",
        "spotifyCharts": "Spotify 排行榜",
        "spotifyPublic": "Spotify 公共信息",
        "spotifyTopCharts": "Spotify 热门排行",
        "stopDown": "停止下载",
        "stopOnClose": "关闭应用后停止音乐",
        "stopOnCloseSub":
            "关闭此开关后，您只能通过点击暂停或停止播放按钮来暂停音乐，关闭本应用不会停止播放\n本应用处于后台时将持续播放音乐，您无需担心后台播放时自动暂停\n",
        "streamQualitySub": "高质量的流会占用更多空间",
        "successTagEdit": "编辑标签成功！",
        "supportEq": "支持的均衡器",
        "tg": "Telegram",
        "tgCh": "Telegram 频道",
        "tgGp": "Telegram 群组",
        "theme": "主题",
        "themeDeleted": "主题已删除！",
        "themeSaved": "主题已保存！",
        "title": "标题",
        "trendingSearch": "热门搜索",
        "ui": "应用界面",
        "undo": "撤销",
        "unknown": "未知",
        "unlike": "取消收藏",
        "update": "更新",
        "updateAvailable": "有更新可用！",
        "upiCopied": "UPI ID 已复制！",
        "useAmoled": "使用 Amoled 深色模式设置",
        "useDenseMini": "密集显示音乐通知",
        "useDenseMiniSub": "音乐通知将减小高度",
        "useDominant": "播放界面使用主色调",
        "useDominantSub": "开启后，使用歌曲图片作为背景主色调；\n关闭后，使用默认渐变作为背景主色调。",
        "useDominantFullScreen": "对整个播放界面使用主色调",
        "useDownSub": "对于已下载的歌曲，将优先播放本地音乐而非在线播放",
        "useProxy": "使用代理",
        "useSystemTheme": "主题跟随系统",
        "useVpn": "不在印度？尝试使用印度服务器的 VPN",
        "version": "版本",
        "versionSub": "点击检查更新",
        "viewAlbum": "查看专辑",
        "viewAll": "查看全部",
        "willPlayNext": "下一首播放",
        "year": "年",
        "yes": "确定",
        "yesReplace": "是，但替换旧文件",
        "ytLiveAlert": "视频为直播内容或者发生了一些错误，请等待直播结束或者重试",
        "useDominantFullScreenSub": "将歌曲图片的颜色作为整个背景的主色调。仅当 '播放界面使用主色调' 选项开启时可用",
        "useHome": "使用主选项可以获得更好的质量和下载支持",
        "useProxySub":
            "如果您不在印度且搜索歌曲时出现问题（例如搜索印度歌曲无结果），则可以开启本选项。您也可以使用带印度服务器的 VPN\n",
        "viewArtist": "查看艺术家",
        "watchVideo": "观看视频",
        "welcome": "欢迎使用",
        "youTube": "YouTube",
        "getLyricsOnline": "搜索本地歌曲的歌词",
        "getLyricsOnlineSub": "如任何离线歌曲的歌词未下载或不可用，则在线搜索",
        "importResso": "从 Resso 导入",
        "ytDownQualitySub": "更高的画质需要更多的磁盘空间",
        "ytStreamQuality": "YouTube 在线播放画质",
        "ytStreamQualitySub": "更高画质使用更多流量",
        "ytDownQuality": "YouTube 下载画质",
        "useBlurForNowPlaying": "模糊“正在播放”区域的背景",
        "useBlurForNowPlayingSub": "低透明度模糊将被用作“正在播放”区域的背景",
        "useDominantAndDarkerColorsSub":
            "主色调和暗色将被用作播放器屏背景的渐变。仅当“使用主色调” 开启时可用（如开启“对全屏使用主色调”效果会更好）",
        "useDominantAndDarkerColors": "对播放屏使用主色调和深色",
        "upNext": "播放下一首",
        "confirmViewable": "确保播放列表可见",
        "autoBackLocation": "自动备份位置",
        "yourPlaylists": "你的播放列表",
        "showPlaylists": "在主屏幕上显示播放列表",
        "playerScreenBackgroundSub": "所选背景将显示在播放器屏幕中",
        "resetOnSkipSub": "从头开始重播，而不是跳到上一首歌曲",
        "resetOnSkip": "跳过上一首时重新播放",
        "playerScreenBackground": "播放器屏幕背景",
        "importJioSaavn": "从 JioSaavn 导入",
        "topCharts": "排行榜",
        "playRadio": "播放电台",
        "importPlaylist": "导入播放列表",
        "mergePlaylists": "合并播放列表",
        "openInSpotify": "在 Spotify 中打开",
        "top": "热门",
        "viral": "飙升",
        "signInSpotify": "登录 Spotify",
        "shareLogsSub": "分享当前会话日志",
        "radio": "电台",
        "shareLogs": "分享日志",
        "cantFind": "无法找到你所寻找的东西？ ",
        "showTopCharts": "显示排行榜",
        "showTopChartsSub": "在主屏幕上显示 Spotify 排行榜",
      };
}
