class CS {
  static Map<String, String> get keys => {
        "accent": "Barva odstínu",
        "alreadyExists": "Již existuje",
        "bgGradSub": "Přechod použitý jako pozadí všude",
        "addNew": "Přidat nové",
        "addSomething": "Běžte něco přidat",
        "addToPlaylist": "Přidat do playlistu",
        "addToQueue": "Přidat do fronty",
        "addedBy": "Přidal/a",
        "addedToQueue": "Přidáno do fronty",
        "adjustSpeed": "Upravit rychlost",
        "album": "Album",
        "alphabetical": "Abecední",
        "appTitle": "BlackHole",
        "artist": "Umělec",
        "artists": "Umělci",
        "autoBack": "Automatická záloha",
        "autoplay": "Automatické přehrávání",
        "autoplaySub": "Automaticky přidávat související skladby do řady",
        "backNRest": "Záloha a obnovení",
        "backupSuccess": "Záloha úspěšná",
        "bgGrad": "Přechod pozadí",
        "blacklistedHomeSections": "Domácí sekce na černé listině",
        "bottomGrad": "Přechod spodních listů",
        "bottomGradSub": "Přechod použitý ve spodních listech",
        "cacheSong": "Uložit skladby do mezipaměti",
        "cancel": "Zrušit",
        "cantAddToQueue": "Do offline fronty nelze přidat online skladbu",
        "canvasColor": "Barva plátna",
        "canvasColorSub": "Barva pozadí plátna",
        "cardColor": "Barva karet",
        "cardGrad": "Přechod karet",
        "cardGradSub": "Přechod použitý v kartách",
        "changeDefault": "Změnit na výchozí",
        "changeOrder": "Dlouhým stisknutím změníte pořadí\n",
        "checkingUpdate": "Kontrola aktualizací…",
        "checkUpdate": "Automatická kontrola aktualizací",
        "clear": "Vymazat",
        "clearAll": "Vymazat vše",
        "clearCache": "Vymazat podrobnosti v mezipaměti",
        "connectingRadio": "Připojování k rádiu…",
        "contactUs": "Kontaktujte nás",
        "convertingSongs": "Konvertuji skladby",
        "copied": "Zkopírováno do schránky!",
        "copy": "Kopírovat",
        "createAlbumFold": "Vytvořit složku pro stahování alb a playlistů",
        "createBack": "Vytvořit zálohu",
        "createBackSub": "Vytvořit zálohu vašich dat",
        "createNewPlaylist": "Vytvořit nový playlist",
        "createPlaylist": "Vytvořit playlist",
        "currentTheme": "Aktuální motiv",
        "darkMode": "Tmavý režim",
        "date": "Datum",
        "dec": "Sestupně",
        "delete": "Smazat",
        "deleteTheme": "Odstranit motiv",
        "disclaimer": "Varování:",
        "displayName": "Zobrazovaný název",
        "donateGpay": "Přispějte pomocí GPay",
        "down": "Stáhnout",
        "downAgain": "již existuje.\nChcete to stáhnout znovu?",
        "downDone": "Stahování dokončeno",
        "downFilenameSub":
            "Skladby budou staženy podle tohoto formátu názvu souboru",
        "downLyrics": "Stáhnout texty",
        "downQuality": "Kvalita stahování",
        "downQualitySub": "Vyšší kvalita využívá více místa na disku",
        "downed": "bylo staženo",
        "downingAlbum": "Stahuji album",
        "downs": "Stahování",
        "duration": "Trvání",
        "edit": "Upravit",
        "enableGesture": "Povolit gesta obalů alb",
        "enableGestureSub":
            "Povolí kliknutí, dlouhé stisknutí, přejetí atd. na obalu alba v obrazovce přehrávače",
        "enforceRepeat": "Vynutit opakování",
        "about": "O aplikaci",
        "aboutLine1": "Toto je open-source projekt a lze jej nalézt na",
        "aboutLine2":
            "Pokud se vám líbila moje práce,\nukažte svou ♥ a dejte ⭐ repozitáři",
        "back": "Zpět",
        "addedToFav": "Přidáno do oblíbených",
        "addedToPlaylists": "Přidáno do playlistů",
        "albums": "Alba",
        "autoBackSub": "Automaticky zálohovat data",
        "addedTo": "Přidáno do",
        "albumArtist": "Interpret alba",
        "alreadyInQueue": "Již ve frontě",
        "cache": "Mezipaměť",
        "blacklistedHomeSectionsSub":
            "Sekce s těmito názvy nebudou zobrazovány na domovské stránce",
        "buyCoffee": "Kupte mi kafe",
        "cacheSongSub":
            "Skladby budou uloženy do mezipaměti pro budoucí přehrání. Další prostor na vašem zařízení bude zabrán",
        "cardColorSub":
            "Barva vyhledávací lišty, vyhledávacích dialogů a karet",
        "chartLocationSub":
            "Země pro místní žebříčky nejlepších skladeb na Spotify",
        "countryQue":
            "Pro jakou zemi by jste si přáli vidět své místní žebříčky Spotify?",
        "clearCacheSub":
            "Vymaže podrobnosti z mezipaměti, což zahrnuje domovskou stránku, žebříčky nejlepších skladeb na Spotify a data poslední relace. Aplikace je obvykle automaticky vymaže, když se data stanou příliš velkými\n",
        "checkUpdateSub":
            "Pokud jste si stáhli BlackHole z jakéhokoliv repozitáře aplikací jako je F-Droid, IzzyOnDroid atd., který poskytuje možnost aktualizace, nechte toto VYPNUTÉ. Pokud jste si ale BlackHole stáhli z GitHubu nebo z jakéhokoliv jiného zdroje, který neumožňuje automatické aktualizace, nechte toto ZAPNUTÉ, abyste dostávali upozornění o aktualizacích\n",
        "contactUsSub": "Ceníme si zpětné vazby!",
        "createYtFold": "Vytvořit jinou složku pro stahování z YouTube",
        "createAlbumFoldSub":
            "Při stahování alba nebo playlistu vytvoří obecnou složku",
        "createYtFoldSub": "Vytvoří jinou složku pro skladby stažené z YouTube",
        "dateAdded": "Datum přidání",
        "deleted": "Smazáno",
        "deleteThemeSubtitle": "Opravdu chcete odstranit tento motiv?",
        "downloadSomething": "Něco stáhněte",
        "disclaimerText":
            "Respektujeme vaše soukromí více než vše ostatní. Bude zaznamenáno pouze vaše jméno, které sem zadáte.",
        "downLyricsSub":
            "Stahování textu spolu se skladbou, pokud je k dispozici",
        "donateGpaySub":
            "Každá malá částka mi udělá radost :)\nKlepněte pro přispění nebo dlouze pro zkopírování ID UPI",
        "downFilename": "Formát názvu ke stažení",
        "downLocation": "Umístění stahování",
        "chartLocation": "Lokace lokálních žebříčků Spotify",
        "enforceRepeatSub": "Zapamatovat možnost opakování u každé relace",
        "enterName": "Zadejte vaše jméno",
        "excludedDetails": "Skladby z vybraných složek nebudou zobrazeny",
        "exitConfirm": "Stiskněte znovu tlačítko zpět pro opuštění aplikace",
        "export": "Exportovat",
        "exported": "Exportováno",
        "failedCreateBackup": "Nepodařilo se vytvořit zálohu",
        "failedDelete": "Nepodařilo se odstranit",
        "favorites": "Oblíbené",
        "favSongs": "Oblíbené skladby",
        "fetchingStream": "Načítání streamu zvuku",
        "finish": "Dokončit",
        "from": "z playlistu",
        "genre": "Žánr",
        "genres": "Žánry",
        "getStarted": "Začít",
        "global": "Globální",
        "gmail": "Gmail",
        "guest": "Host",
        "home": "Domů",
        "includeExcludeFolder": "Zahrnout/vyloučit složky",
        "includeExcludeFolderSub":
            "Zahrne/vyloučí vybrané složky ze sekce Moje hudba",
        "importSuccess": "Úspěšně importováno",
        "importYt": "Importovat z YouTube",
        "inc": "Vzestupně",
        "included": "Zahrnuto",
        "lang": "Jazyk",
        "langQue": "V jakém jazyce preferujete poslouchat skladby?",
        "insta": "Instagram",
        "ipAdd": "IP adresa",
        "joinTg": "Připojte se k nám na Telegramu",
        "joinTgSub": "Chcete vyzkoušet beta verze? Připojte se k nám!",
        "liveSearch": "Živé hledání",
        "liveSearchSub": "Hledat skladby hned, jak uživatel přestane psát",
        "loadLast": "Načíst poslední relaci při spuštění aplikace",
        "loadLastSub":
            "Automaticky načíst poslední relaci při spuštění aplikace",
        "madeBy": "S ♥ vytvořil Ankit Sangwan",
        "minAudioAlert": "Minimální délka zvuku (ve vteřinách)",
        "minAudioLen": "Minimální délka zvuku pro hledání hudby",
        "minAudioLenSub":
            "Zvuk s délkou kratší než je nastavená nebude zobrazen v sekci Moje hudba",
        "musicLangSub": "K zobrazení skladeb na domovské obrazovce",
        "musicPlayback": "Hudba a přehrávání",
        "myMusic": "Moje hudba",
        "moreInfo": "Další informace",
        "musicLang": "Jazyk hudby",
        "noFolderSelected": "Nebyla vybrána žádná složka",
        "enterPlaylistLink": "Zadejte odkaz na playlist",
        "enterSongsCount": "Zadejte počet skladeb",
        "enterText": "Zadejte text",
        "enterThemeName": "Zadejte název motivu",
        "equalizer": "Ekvalizér",
        "excluded": "Vyloučeno",
        "failedExport": "Nepodařilo se exportovat",
        "importResso": "Importovat z Resso",
        "includedDetails": "Budou zobrazeny pouze skladby z vybraných složek",
        "langSub": "Jazyk aplikace",
        "lastAdded": "Naposledy přidáno",
        "local": "Místní",
        "lyrics": "Texty",
        "miniButtons": "Tlačítka k zobrazení v mini přehrávači",
        "miniButtonsSub":
            "Klepněte pro změnu zobrazených tlačítek v mini přehrávači",
        "minutes": "minut",
        "no": "Ne",
        "getLyricsOnline": "Hledat texty lokálních skladeb",
        "getLyricsOnlineSub":
            "Hledat texty online, pokud nejsou dostupné/stažené",
        "homeGreet": "Zdravíme,",
        "importFile": "Importovat ze souboru",
        "importPublicPlaylist": "Importovat veřejný playlist",
        "importSpotify": "Importovat ze Spotify",
        "like": "Líbí se mi",
        "confirmViewable": "Ujistěte se, že je playlist zobrazitelný",
        "failedTagEdit": "Nepodařilo se upravit štítky",
        "failedImport": "Nepodařilo se importovat",
        "lastModified": "Naposledy upraveno",
        "lastSession": "Poslední relace",
        "library": "Knihovna",
        "likedWork": "Líbí se vám má práce?",
        "latest": "Gratulujeme! Používáte nejnovější verzi :)",
        "live": "NYNÍ ŽIVĚ",
        "yesReplace": "Ano, ale nahradit starou",
        "youTube": "YouTube",
        "ytStreamQuality": "Kvalita streamování z YouTube",
        "playing": "Nehraje",
        "removedFrom": "Odebráno z playlistu",
        "removedFromFav": "Odebráno z oblíbených",
        "rename": "Přejmenovat",
        "reset": "Resetovat",
        "restore": "Obnovit",
        "resultsNotFound": "Nenalezeny žádné výsledky",
        "savePlaylist": "Uložit playlist",
        "searchVideo": "Hledat video",
        "selectBackFile": "Vyberte soubor zálohy",
        "settings": "Nastavení",
        "showLastSub": "Zobrazit poslední relaci na domovské obrazovce",
        "songPath": "Cesta ke skladbě",
        "streamQuality": "Kvalita hudby",
        "streamQualitySub": "Vyšší kvalita využívá více dat",
        "tgGp": "Skupina Telegram",
        "theme": "Motiv",
        "updateAvailable": "Je dostupná aktualizace!",
        "upiCopied": "ID UPI zkopírováno!",
        "useSystemTheme": "Použít systémový motiv",
        "viewAlbum": "Zobrazit album",
        "viewArtist": "Zobrazit umělce",
        "viewAll": "Zobrazit vše",
        "watchVideo": "Zhlédnout video",
        "nothingPlaying": "Nic nehraje",
        "nothingTo": "Nic k ",
        "prefReq": "Nechcete nám říct pár dalších věcí?",
        "proxySet": "Nastavení proxy",
        "proxySetSub": "Změnit IP a port proxy",
        "rememberChoice": "Zapamatovat si mou volbu",
        "remove": "Odebrat",
        "removed": "Odebráno",
        "restoreSub":
            "Obnovte vaše data ze zálohy.\nMožná budete muset restartovat aplikaci\n",
        "searchHome": "Hledat doma",
        "searchText": "Skladby, alba nebo umělci",
        "selectDur": "Vyberte dobu trvání",
        "selectExportLocation": "Vyberte umístění exportu",
        "selectJsonImport": "Vyberte soubor JSON k importování",
        "share": "Sdílet",
        "shareApp": "Sdílet aplikaci",
        "shareAppSub": "Dejte svým přátelům vědět o této aplikaci",
        "shareAppText": "Ahoj! Mrkni na tenhle super hudební přehrávač",
        "showHere": "Vidění",
        "showHistory": "Zobrazit historii vyhledávání",
        "showHistorySub":
            "Zobrazit historii vyhledávání pod vyhledávací lištou",
        "showLast": "Zobrazit poslední relaci",
        "size": "Velikost",
        "skip": "Přeskočit",
        "skipNext": "Přeskočit další",
        "skipPrevious": "Přeskočit předchozí",
        "sleepAfter": "Uspat aplikaci po N skladbách",
        "sleepTimer": "Časovač uspání",
        "sleepTimerSetFor": "Časovač uspání nastaven na",
        "song": "Skladba",
        "songInfo": "Informace o skladbě",
        "sorry": "OMLOUVÁME SE",
        "sponsor": "Podpořte tento projekt",
        "spotifyCharts": "Žebříčky Spotify",
        "stopDown": "Zastavit stahování",
        "stopOnClose": "Zastavit hudbu při zavření aplikace",
        "stopOnCloseSub":
            "Pokud je nastavení vypnuto, hudba bude pokračovat v přehrávání i po 'zavření' aplikace, dokud nezmáčknete tlačítko k zastavení. Tato možnost platí pro 'zavření' aplikace, když není na 'pozadí'. Hudba bude stále přehrávána na pozadí, k tomu není potřeba měnit žádné nastavení.\n",
        "supportEq": "Podpora ekvalizéru",
        "supportEqSub":
            "Ponechte toto vypnuté, pokud vám nefunguje přehrávání skladeb (v online ani offline režimu)",
        "trendingSearch": "Trendy vyhledávání",
        "ui": "UI aplikace",
        "useAmoled": "Použít AMOLED tmavý režim",
        "useDenseMini": "Použít menší minipřehrávač",
        "useDenseMiniSub": "Výška minipřehrávače bude zmenšena",
        "useDominant": "Použít dominantní barvu pro obrazovku přehrávání",
        "useDominantSub":
            "Dominantní barva z obrázku bude použita pro pozadí obrazovky přehrávání. Pokud je nastavení vypnuto, bude použit výchozí přechod pozadí",
        "useBlurForNowPlayingSub":
            "Bude použito rozmazání s nižší průhledností jako pozadí sekce Právě hraje",
        "useDominantAndDarkerColors":
            "Použít dominantní a tmavší barvy pro obrazovku přehrávání",
        "useDominantAndDarkerColorsSub":
            "Pro pozadí obrazovky přehrávání bude použita dominantní a tmavší barva z obrázku. Dostupné pouze při zapnutém nastavení Použít dominantní barvu (lepší výsledky při zapnutí Použít dominantní barvu na celou obrazovku)",
        "useDominantFullScreen":
            "Použít dominantní barvu na celou obrazovku přehrávání",
        "useDownSub":
            "Pokud je skladba již stažena, bude místo streamování online použita daná skladba",
        "useHome": "Použít hlavní sekci pro podporu stahování a lepší kvalitu",
        "version": "Verze",
        "versionSub": "Klepněte pro kontrolu aktualizací",
        "year": "Rok",
        "yes": "Ano",
        "others": "Ostatní",
        "or": "NEBO",
        "search": "Hledat",
        "playNext": "Přehrát jako další",
        "aboard": "Na palubu",
        "play": "Přehrát",
        "playSomething": "Něco si pusťte",
        "noLangSelected":
            "Nebyl vybrán žádný jazyk hudby. Vyberte jazyk pro zobrazení skladeb na domovské stránce",
        "notAvailable": "Nedostupné",
        "nothingIs": "Nic ",
        "nowPlaying": "Právě hraje",
        "ok": "OK",
        "pause": "Pozastavit",
        "playlists": "Playlisty",
        "saveTheme": "Uložit motiv",
        "searchYt": "Hledat na YouTube",
        "shuffle": "Náhodně",
        "playingCap": "PŘEHRÁVÁNÍ",
        "port": "Port",
        "showQr": "Zobrazit QR kód",
        "sleepAfterSub":
            "Hudba bude pozastavena po přehrání vybraného počtu skladeb",
        "spotifyPublic": "Veřejné Spotify",
        "playlistShareText": "Mrkni na můj playlist!",
        "popularity": "Popularita",
        "selectBackLocation": "Vyberte umístění zálohy",
        "selectDownLocation": "Vyberte umístění stahování",
        "sleepDur": "Uspat aplikaci po době hh:mm",
        "spotifyTopCharts": "Žebříčky nejlepších Spotify",
        "sleepDurSub": "Hudba bude pozastavena po vybrané době",
        "songs": "Skladby",
        "useProxy": "Použít proxy",
        "successTagEdit": "Štítky úspěšně upraveny!",
        "tg": "Telegram",
        "tgCh": "Kanál Telegram",
        "themeDeleted": "Motiv odstraněn!",
        "themeSaved": "Motiv uložen!",
        "title": "Název",
        "undo": "Zrušit",
        "unknown": "Neznámé",
        "unlike": "Odebrat z oblíbených",
        "update": "Aktualizace",
        "useDominantFullScreenSub":
            "Dominantní barva z obrázku bude použita na celé pozadí obrazovky přehrávání. Dostupné pouze při zapnutém nastavení Použít dominantní barvu",
        "ytDownQuality": "Kvalita stahování z YouTube",
        "ytLiveAlert":
            "Buď je video právě živě vysílané, nebo se vyskytla chyba. Počkejte, dokud živý přenos neskončí, nebo to zkuste znovu.",
        "welcome": "Vítejte",
        "ytDownQualitySub": "Vyšší kvalita využívá více místa na disku",
        "ytStreamQualitySub": "Vyšší kvalita využívá více dat",
        "useDown": "Streamovat stažené skladby, pokud je to možné",
        "useProxySub":
            "Pokud nejste z Indie a máte problémy s vyhledáváním, jako například zobrazování pouze indických skladeb nebo žádných výsledků apod., můžete použít VPN s indickým serverem\n",
        "useVpn": "Nejste z Indie? Zkuste použít VPN s indickým serverem",
        "willPlayNext": "bude přehráváno jako další",
        "upNext": "Další",
        "autoBackLocation": "Umístění automatické zálohy",
        "yourPlaylists": "Vaše playlisty",
        "showPlaylists": "Zobrazit playlisty na domovské obrazovce",
        "resetOnSkip": "Znovu přehrát při přeskočení zpět",
        "resetOnSkipSub":
            "Znovu přehrát od začátku místo přeskočení na předchozí skladbu",
        "importJioSaavn": "Importovat z JioSaavn",
        "playerScreenBackground": "Pozadí obrazovky přehrávání",
        "playerScreenBackgroundSub":
            "Vybrané pozadí bude zobrazeno v obrazovce přehrávání",
        "topCharts": "Žebříčky nejlepších",
        "playRadio": "Přehrát rádio",
        "mergePlaylists": "Sloučit playlisty",
        "importPlaylist": "Importovat playlist",
        "top": "Nejlepší",
        "viral": "Virální",
        "openInSpotify": "Otevřít ve službě Spotify",
        "signInSpotify": "Přihlásit se ke Spotify",
        "shareLogsSub": "Sdílet protokoly aktuálních relací",
        "shareLogs": "Sdílet protokoly",
        "radio": "Rádio",
        "cantFind": "Nemůžete najít, co hledáte? ",
        "showTopCharts": "Zobrazit žebříčky nejlepších",
        "showTopChartsSub":
            "Zobrazit žebříčky nejlepších Spotify na domovské obrazovce",
        "mostPlayedSong": "Nejhranější skladba",
        "songsPlayed": "Přehrané skladby",
        "stats": "Statistiky",
        "compactNotificationButtonsSub":
            "Tlačítka pro zobrazení v kompaktním zobrazení oznámení",
        "compactNotificationButtons": "Kompaktní tlačítka oznámení",
        "compactNotificationButtonsHeader":
            "Můžete vybrat maximálně 3 tlačítka",
      };
}
