class KO {
  static Map<String, String> get keys => {
        "addNew": "새로 추가하기",
        "addToPlaylist": "플레이리스트에 추가하기",
        "appTitle": "BlackHole",
        "albumArtist": "앨범 아티스트",
        "backNRest": "백업 & 복원",
        "album": "앨범",
        "about": "정보",
        "addToQueue": "재생목록에 추가하기",
        "accent": "색 선택",
        "aboard": "초기 설정",
        "addSomething": "플레이리스트를 채워보세요",
        "aboutLine1": "BlackHole은 오픈소스 프로젝트 입니다. GitHub에서 찾으실 수 있습니다",
        "aboutLine2": "BlackHole이 마음에 들었다면\nGitHub에 ♥와 ⭐ 눌러주세요",
        "adjustSpeed": "속도 조절",
        "addedToPlaylists": "플레이리스트에 추가됨",
        "albums": "앨범 목록",
        "backupSuccess": "백업 완료",
        "addedToFav": "좋아요 표시한 곡에 추가됨",
        "addedToQueue": "재생목록에 추가됨",
        "alreadyInQueue": "재생목록에 이미 존재함",
        "artist": "아티스트",
        "back": "뒤로가기",
        "alphabetical": "가나다순",
        "alreadyExists": "이미 존재함",
        "autoBack": "자동 백업",
        "buyCoffee": "커피 한잔 사주세요",
        "cache": "캐시",
        "autoplaySub": "자동으로 재생목록에 연관된 노래 추가하기",
        "artists": "아티스트",
        "bgGrad": "배경 그라데이션",
        "bgGradSub": "배경에 사용되는 그라데이션",
        "bottomGradSub": "하단 팝업에 사용되는 그라데이션",
        "bottomGrad": "하단 팝업 그라데이션",
        "blacklistedHomeSections": "홈 섹션 커스텀",
        "autoBackSub": "데이터 자동 백업",
        "addedBy": "추가한 사람",
        "addedTo": "에 추가됨",
        "cancel": "취소",
        "checkingUpdate": "업데이트 확인 중…",
        "darkMode": "다크 모드",
        "copy": "복사",
        "date": "날짜",
        "createPlaylist": "플레이리스트 만들기",
        "countryQue": "어느 스포티파이 국가 차트를 보시겠습니까?",
        "connectingRadio": "라디오 연결 중…",
        "currentTheme": "현재 테마",
        "changeOrder": "길게 눌러서 순서 변경\n",
        "chartLocation": "스포티파이 차트 국가 설정",
        "chartLocationSub": "국가 설정",
        "cardGrad": "팝업 그라데이션",
        "cardGradSub": "팝업에 사용되는 그라데이션",
        "canvasColor": "캔버스 색상",
        "cardColor": "카드 색상",
        "createYtFold": "YouTube 다운로드 별도 폴더 사용",
        "createYtFoldSub": "YouTube에서 다운로드한 노래들은 별도의 폴더에 저장합니다",
        "createBack": "백업 만들기",
        "copied": "클립보드에 복사됨!",
        "convertingSongs": "노래 변환 중",
        "contactUsSub": "피드백은 환영입니다!",
        "contactUs": "문의",
        "clearCache": "상세 캐시 삭제",
        "checkUpdate": "업데이트 자동 확인",
        "cantAddToQueue": "온라인 곡은 오프라인 재생목록에 추가할 수 없습니다",
        "clear": "지우기",
        "clearAll": "모두 지우기",
        "cardColorSub": "검색, 알림, 팝업 색상",
        "canvasColorSub": "캔버스 배경 색상",
        "cacheSong": "곡 캐시하기",
        "cacheSongSub": "앞으로 재생할 곡들이 기기에 캐시됩니다. 이에 따라 기기에 용량이 소유됩니다",
        "downAgain": "파일이 이미 존재합니다.\n그래도 다운로드하시겠습니까?",
        "downDone": "다운로드 완료",
        "dateAdded": "추가된 날짜",
        "delete": "삭제",
        "deleted": "삭제됨",
        "deleteTheme": "테마 삭제하기",
        "deleteThemeSubtitle": "삭제하시겠습니까?",
        "downs": "다운로드",
        "duration": "재생 시간",
        "displayName": "노래 제목",
        "dec": "가나다 역순",
        "downFilename": "이름 형식",
        "donateGpaySub": "작은 금액도 저를 웃게 합니다\n길게 누르면 UPI ID를 복사할 수 있습니다",
        "downFilenameSub": "파일을 다운로드할 때 이름 형식을 설정합니다",
        "downingAlbum": "앨범 다운로드 중",
        "downloadSomething": "다운로드 중",
        "enableGestureSub": "앨범 표지에 탭, 길게 누르기, 스와이프 등을 활성화합니다",
        "enforceRepeat": "반복 옵션 유지",
        "enforceRepeatSub": "설정한 반복 옵션을 계속 유지합니다",
        "enterPlaylistLink": "플레이리스트 링크를 입력하세요",
        "equalizer": "이퀄라이저",
        "excluded": "제외됨",
        "failedExport": "내보내기에 실패하였습니다",
        "failedDelete": "삭제하는 것을 실패하였습니다",
        "failedCreateBackup": "백업에 실패하였습니다",
        "failedTagEdit": "태그 수정에 실패하였습니다",
        "getLyricsOnline": "오프라인 곡 가사 검색",
        "failedImport": "가져오는데 실패하였습니다",
        "from": "에서",
        "exitConfirm": "뒤로가기 버튼을 한 번 더 누르면 종료됩니다",
        "excludedDetails": "선택된 폴더의 곡은 제외됩니다",
        "enterThemeName": "테마 이름을 입력하세요",
        "enterText": "텍스트를 입력하세요",
        "enterSongsCount": "곡 수를 입력하세요",
        "downed": "이(가) 다운로드되었습니다",
        "insta": "Instagram",
        "home": "홈",
        "homeGreet": "안녕하세요,",
        "genres": "장르",
        "inc": "가나다순",
        "global": "글로벌",
        "importSuccess": "가져오는데 성공하였습니다",
        "importYt": "YouTube에서 가져오기",
        "includeExcludeFolder": "폴더 포함/ 제외하기",
        "includeExcludeFolderSub": "'내 음악'에서 선택한 폴더들 포함/ 제외하기",
        "included": "포함됨",
        "includedDetails": "선택된 폴더의 곡들만 나타납니다",
        "joinTg": "Telegram에 가입하세요",
        "latest": "축하합니다! 최신 버전을 사용 중입니다 :)",
        "lang": "언어",
        "langQue": "어떤 언어 노래를 듣고 싶으세요?",
        "lastSession": "최근에 재생한 곡",
        "library": "라이브러리",
        "joinTgSub": "베타 버전을 사용하고 싶나요? 지금 가입하세요!",
        "langSub": "앱 언어",
        "lastAdded": "마지막으로 추가된",
        "lastModified": "마지막으로 수정된",
        "like": "좋아요",
        "live": "LIVE NOW",
        "liveSearch": "라이브 검색",
        "likedWork": "어때요?",
        "lyrics": "가사",
        "no": "아니요",
        "myMusic": "내 음악",
        "liveSearchSub": "입력을 멈추는 순간 바로 검색 결과가 나타납니다",
        "loadLast": "앱 실행 시 마지막 세션 실행",
        "miniButtons": "미니 플레이어 버튼 커스텀",
        "miniButtonsSub": "미니 플레이어에 사용하고 싶은 버튼을 커스텀하세요",
        "minutes": "분",
        "musicPlayback": "음악 & 재생",
        "noFolderSelected": "선택된 폴더가 없습니다",
        "notAvailable": "사용할 수 없습니다",
        "noLangSelected": "음악 언어가 선택되지 않았습니다. 홈에서 곡을 보기 위해 언어를 선택하세요",
        "musicLangSub": "홈에 곡을 표시하기 위해",
        "minAudioAlert": "오디오 길이",
        "minAudioLen": "음악 검색을 위한 오디오 길이",
        "minAudioLenSub": "이보다 짧은 곡은 \"내 음악'에 표시되지 않습니다",
        "prefReq": "몇 가지 알려드릴까요?",
        "ok": "확인",
        "searchText": "노래, 앨범 또는 아티스트 검색",
        "nowPlaying": "지금 재생 중",
        "nothingTo": "플레이리스트가 ",
        "or": "또는",
        "playlists": "재생목록",
        "searchYt": "YouTube 검색",
        "searchHome": "홈 검색",
        "share": "공유",
        "nothingPlaying": "재생 중이 아닙니다",
        "playRadio": "라디오 재생",
        "playing": "재생 중",
        "playingCap": "재생 중",
        "proxySetSub": "프록시 IP와 포트 변경",
        "rememberChoice": "내 설정 기억하기",
        "reset": "초기화",
        "restoreSub": "백업 데이터를 복원하세요.\n이후에 앱을 재실행해야 할 수 있습니다\n",
        "resultsNotFound": "결과를 찾을 수 없습니다",
        "savePlaylist": "플레이리스트 저장",
        "saveTheme": "테마 저장하기",
        "searchVideo": "동영상 검색",
        "selectBackFile": "백업 파일 선택하기",
        "selectDownLocation": "다운로드 위치",
        "selectBackLocation": "백업 위치",
        "selectJsonImport": "가져올 JSON 파일을 선택하세요",
        "settings": "설정",
        "selectExportLocation": "내보낼 위치를 선택하세요",
        "selectDur": "구간을 선택하세요",
        "resetOnSkipSub": "이전 곡으로 넘어가지 말고, 앞부터 다시 재생하기",
        "resetOnSkip": "이전 건너뛰기에서 다시 재생하기",
        "removedFromFav": "좋아요 표시한 곡에서 제거됨",
        "removedFrom": "제거됨",
        "popularity": "인기",
        "playSomething": "뭔가를 재생해보세요",
        "others": "기타",
        "nothingIs": "재생 중인 곡이 없습니다 ",
        "playlistShareText": "플레이리스트를 확인해보세요!",
        "skip": "건너뛰기",
        "skipNext": "다음 곡 건너뛰기",
        "skipPrevious": "이전 곡 건너뛰기",
        "showHere": "비었습니다",
        "sponsor": "BlackHole 후원하기",
        "size": "크기",
        "sleepAfter": "재생할 곡 개수 설정하기",
        "sleepAfterSub": "선택한 노래 수를 재생하면 음악이 중지됩니다",
        "sleepDur": "재생 시간 정하기",
        "shuffle": "셔플 재생",
        "shareApp": "앱 공유",
        "shareAppSub": "BlackHole을 공유해주세요",
        "showHistory": "검색 기록 보이기",
        "showHistorySub": "검색 할 때 검색 기록 보이기",
        "showLast": "마지막 세션 보이기",
        "showLastSub": "홈에 마지막 세션 보이게 하기",
        "showPlaylists": "홈에 플레이리스트 보이기",
        "showQr": "QR 코드 보이기",
        "sorry": "오류",
        "sleepTimerSetFor": "취침 타이머를 설정합니다",
        "shareAppText": "멋진 앱 확인해 봐",
        "update": "업데이트",
        "tgGp": "Telegram 그룹",
        "ui": "UI",
        "undo": "취소",
        "unknown": "알 수 없음",
        "unlike": "좋아요 취소",
        "stopDown": "다운로드 정지",
        "stopOnClose": "앱 종료 시 음악 정지",
        "streamQuality": "스트리밍 음질",
        "successTagEdit": "태그를 성공적으로 수정했습니다!",
        "topCharts": "차트",
        "top": "인기 차트",
        "upNext": "재생목록",
        "spotifyTopCharts": "Spotify 차트",
        "upiCopied": "UPI ID 복사 성공!",
        "useProxy": "프록시 사용하기",
        "useHome": "메인 섹션을 고음질과 다운로드 서포트에 사용하기",
        "useDownSub": "곡이 다운로드된 경우, 온라인 재생 대신에 기기에 저장된 곡이 재생됩니다",
        "useDown": "가능할 경우 다운로드한 곡 재생하기",
        "useBlurForNowPlayingSub": "현재 재생 중 섹션에 블러 처리된 이미지가 사용됩니다",
        "useDenseMiniSub": "미니 플레이어의 높이가 줄어듭니다",
        "useDenseMini": "미니 플레이어 높이 줄이기",
        "supportEq": "이퀄라이저 사용하기",
        "spotifyPublic": "스포티파이 공개",
        "viewArtist": "아티스트 보기",
        "youTube": "유튜브",
        "version": "버전",
        "versionSub": "업데이트 확인하기",
        "viewAlbum": "앨범 보기",
        "yourPlaylists": "내 플레이리스트",
        "useSystemTheme": "시스템 설정 사용",
        "watchVideo": "동영상 보기",
        "ytDownQuality": "YouTube 다운로드 화질",
        "ytStreamQuality": "YouTube 스트리밍 화질",
        "ytLiveAlert": "실시간 영상입니다. 스트리밍이 끝날 때까지 기다렸다가 다시 시도해주세요.",
        "year": "연도",
        "useVpn":
            "YouTube Music은 한국에서 무료 요금제를 지원하지 않습니다. BlackHole을 이용하기 위해서는 VPN을 사용해주세요",
        "yesReplace": "덮어쓰기",
        "welcome": "BlackHole",
        "viral": "바이러스성",
        "yes": "예",
        "viewAll": "더보기",
        "willPlayNext": "가(이) 재생됩니다",
        "ytStreamQualitySub": "음질이 높을수록 데이터를 더 많이 사용합니다",
        "ytDownQualitySub": "음질이 높을수록 용량이 더 커집니다",
        "changeDefault": "기본값으로 설정",
        "export": "내보내기",
        "down": "다운로드",
        "createNewPlaylist": "새 플레이리스트 만들기",
        "moreInfo": "더보기",
        "musicLang": "음악 언어",
        "mergePlaylists": "플레이리스트 합치기",
        "genre": "장르",
        "edit": "수정",
        "madeBy": "Ankit Sangwan이 ♥으로 만듬",
        "autoplay": "자동 재생",
        "autoBackLocation": "자동 백업 위치",
        "tgCh": "Telegram 채널",
        "theme": "테마",
        "themeDeleted": "테마가 삭제되었습니다!",
        "title": "제목",
        "stopOnCloseSub": "이 설정을 끌 경우 앱을 닫아도 음악이 정지되지 않습니다\n",
        "songPath": "곡 경로",
        "spotifyCharts": "스포티파이 차트",
        "streamQualitySub": "높은 음질은 더 많은 데이터를 사용합니다",
        "sleepDurSub": "선택한 지속시간이 지나면 음악이 중지됩니다",
        "themeSaved": "테마가 저장되었습니다!",
        "sleepTimer": "취침 타이머",
        "song": "곡",
        "songInfo": "곡 정보",
        "tg": "Telegram",
        "trendingSearch": "인기 차트 검색",
        "songs": "곡",
        "updateAvailable": "새 버전 설치 가능!",
        "useAmoled": "AMOLDED 다크 모드 사용하기",
        "downQuality": "음질 설정",
        "downQualitySub": "높은 음질은 더 많은 디스크 공간을 사용합니다",
        "enableGesture": "앨범 표지에 제스처 활성화",
        "exported": "내보내기 완료",
        "ipAdd": "IP 주소",
        "play": "재생",
        "supportEqSub": "(온라인 및 오프라인 모드에서) 재생이 불가능할 경우 이 설정을 끄세요",
        "downLocation": "다운로드 위치",
        "downLyrics": "가사 다운로드",
        "disclaimer": "참고 :",
        "donateGpay": "GPay로 기부하기",
        "importFile": "파일 가져오기",
        "pause": "일시 정지",
        "enterName": "이름을 입력하세요",
        "downLyricsSub": "가능할 경우 노래와 함께 가사도 같이 다운로드",
        "importJioSaavn": "JioSaavn에서 가져오기",
        "importPublicPlaylist": "공개 플레이리스트 가져오기",
        "importResso": "Resso에서 가져오기",
        "importSpotify": "Spotify에서 가져오기",
        "remove": "제거",
        "playerScreenBackground": "음악 플레이어 배경 스타일",
        "importPlaylist": "플레이리스트 가져오기",
        "gmail": "Gmail",
        "playerScreenBackgroundSub": "선택한 배경이 플레이어 화면에 표시됩니다.",
        "guest": "손님",
        "removed": "제거됨",
        "getStarted": "시작하기",
        "search": "검색",
        "restore": "복원",
        "disclaimerText": "BlackHole은 여러분의 프라이버시를 우선시합니다. 사용자의 이름만 기록됩니다.",
        "checkUpdateSub":
            "BlackHole을 'F-Droid'나 'IzzyOnDroid'처럼 자동 업데이트를 지원하는 스토어에서 다운로드했다면, 이 옵션을 꺼주세요. GitHub나 다른 데에서 다운로드한 경우는 업데이트 알림을 받기 위해 이 옵션 켜두세요.\n",
        "createBackSub": "내 데이터를 백업합니다",
        "playNext": "다음 곡으로 재생하기",
        "createAlbumFold": "앨범 & 플레이리스트 별도 폴더 생성",
        "fetchingStream": "오디오 스트림 가져오는 중",
        "createAlbumFoldSub": "앨범이나 플레이리스트가 다운로드됐을 때 별도 폴더를 생성합니다",
        "confirmViewable": "플레이리스트가 공개로 되어있는지 확인해주세요",
        "clearCacheSub":
            "상세 캐시는 홈, Spotify 차트, YouTube와 마지막 세션을 포함합니다. 보통은 용량이 커지면 자동으로 삭제됩니다\n",
        "favorites": "좋아요 표시한 곡",
        "getLyricsOnlineSub": "가사가 없는 경우 온라인에서 검색하세요",
        "blacklistedHomeSectionsSub": "홈 탭에 있는 섹션들을 삭제할 수 있습니다",
        "favSongs": "좋아요 표시한 곡",
        "finish": "완료",
        "loadLastSub": "저번에 앱을 사용하다가 닫은 상태로 다시 엽니다",
        "proxySet": "프록시 설정",
        "rename": "이름 수정하기",
        "local": "오프라인",
        "useProxySub": "인도 외의 국가에서 사용 중이고, 인도 노래만 검색되는 등의 경우에 이 옵션을 켜세요.\n",
        "port": "포트",
      };
}
