class SQ {
  static Map<String, String> get keys => {
        "artists": "Artistët",
        "addNew": "Shto nje te ri",
        "aboard": "Në bord",
        "about": "Rreth",
        "aboutLine2": "Nëse ju pëlqeu puna ime\ntregoni disa ♥ dhe ⭐ depon",
        "accent": "Ngjyra dhe nuanca e theksit",
        "addedBy": "Shtuar nga",
        "addedTo": "Shtuar në",
        "addedToFav": "Shtuar te të preferuarat",
        "addedToPlaylists": "Shtuar në Playlist-a",
        "addedToQueue": "Shtuar në Rradhë",
        "adjustSpeed": "Rregulloni shpejtësinë",
        "album": "Album",
        "albumArtist": "Artisti i albumit",
        "albums": "Albume",
        "alphabetical": "Alfabetike",
        "alreadyExists": "Tashmë Ekziston",
        "alreadyInQueue": "Tashmë në Rradhë",
        "appTitle": "BlackHole",
        "autoBackLocation": "Backupi automatik i vendndodhjes",
        "addSomething": "Shkoni dhe shtoni diçka",
        "addToQueue": "Shto në Rradhë",
        "aboutLine1":
            "Ky është një projekt me burim të hapur dhe mund të gjendet në",
        "addToPlaylist": "Shto në Playlist",
        "artist": "Artisti",
      };
}
