class FR {
  static Map<String, String> get keys => {
        "aboard": "à bord",
        "about": "À propos",
        "aboutLine1":
            "Ceci est un projet à code source ouvert qui peut être trouvé sur",
        "aboutLine2":
            "Si vous avez aimé mon travail\nmontrez du ♥ et ⭐ la repo",
        "accent": "Couleur d'accentuation et teinte",
        "addNew": "Ajouter un nouveau",
        "addSomething": "Allez-y et ajoutez quelque chose",
        "addToPlaylist": "Ajouter à une liste de lecture",
        "addToQueue": "Ajouter à la file d'attente",
        "addedBy": "Ajouté par",
        "addedTo": "Ajouté à",
        "addedToFav": "Ajouté aux Favoris",
        "addedToPlaylists": "Ajouté aux listes de lecture",
        "addedToQueue": "Ajouté à la file d'attente",
        "adjustSpeed": "Ajuster la vitesse",
        "album": "Album",
        "albumArtist": "Artiste de l'album",
        "albums": "Albums",
        "alphabetical": "Alphabétique",
        "alreadyExists": "Existe déjà",
        "alreadyInQueue": "Déjà dans la file d'attente",
        "appTitle": "BlackHole",
        "artist": "Artiste",
        "artists": "Artistes",
        "autoBack": "Sauvegarde auto",
        "autoBackSub": "Sauvegarder automatiquement les données",
        "autoplay": "Lecture automatique",
        "autoplaySub":
            "Ajouter automatiquement des morceaux similaires à la file d'attente",
        "back": "Retour",
        "backNRest": "Sauvegarde et restauration",
        "backupSuccess": "Sauvegarde réussie",
        "bgGrad": "Dégradé d'arrière-plan",
        "bgGradSub": "Dégradé utilisé en arrière-plan partout",
        "blacklistedHomeSections": "Sections de l'accueil en liste noire",
        "blacklistedHomeSectionsSub":
            "Les sections avec ces titres ne seront pas affichées sur l'écran d'accueil",
        "bottomGrad": "Dégradé du bas",
        "bottomGradSub": "Dégradé utilisé en bas",
        "buyCoffee": "Payez-moi un café",
        "cache": "Cache",
        "cacheSong": "Morceaux en cache",
        "cacheSongSub":
            "Les morceaux seront mis en cache pour les prochaines lectures. De l'espace supplémentaire sera pris sur votre appareil",
        "cancel": "Annuler",
        "cantAddToQueue":
            "Impossible d'ajouter des morceaux en ligne à une liste de lecture hors-ligne",
        "canvasColor": "Couleur de la toile de fond",
        "canvasColorSub": "Couleur de la toile de fond",
        "cardColor": "Couleur des cartes",
        "cardColorSub":
            "Couleur de la barre de recherche, des boîtes de dialogue d'alerte et des cartes",
        "cardGrad": "Dégradé des cartes",
        "cardGradSub": "Dégradés utilisés dans les cartes",
        "changeDefault": "Changer par les valeurs par défaut",
        "changeOrder": "Appui long pour changer l'ordre\n",
        "chartLocation": "Localisation des classements locaux Spotify",
        "chartLocationSub": "Pays pour les classements locaux Spotify",
        "checkingUpdate": "Vérification des mises à jours…",
        "checkUpdate": "Vérification automatique des mises à jours",
        "checkUpdateSub":
            "Si vous avez téléchargé BlackHole à partir d'un dépôt d'applications comme F-Droid, IzzyOnDroid, etc. qui fournissent des options de mise à jour, gardez cette option désactivée. Si vous l'avez téléchargé depuis GitHub ou toute autre source qui ne fournit pas de mises à jour automatiques, activez cette option pour recevoir des alertes de mise à jour\n",
        "clear": "Effacer",
        "clearAll": "Tout effacer",
        "clearCache": "Effacer les détails en cache",
        "clearCacheSub":
            "Supprime les détails mis en cache, y compris la page d'accueil, les Meilleurs classements Spotify, YouTube et les données de la dernière session. En général, l'application les efface automatiquement lorsque les données deviennent importantes\n",
        "connectingRadio": "Connexion à la radio…",
        "contactUs": "Nous contacter",
        "contactUsSub": "Les commentaires sont les bienvenus !",
        "convertingSongs": "Conversion des morceaux",
        "copied": "Copié dans le presse-papiers !",
        "copy": "Copier",
        "countryQue":
            "Pour quel pays aimeriez-vous voir les classements locaux de Spotify ?",
        "createAlbumFold":
            "Créer un dossier pour le téléchargement d'albums et de listes de lecture",
        "createAlbumFoldSub":
            "Créer un dossier pour les morceaux lorsqu'un album ou une liste de lecture est téléchargée",
        "createBack": "Créer une sauvegarde",
        "createBackSub": "Créer une sauvegarde des données",
        "createNewPlaylist": "Créer une nouvelle liste de lecture",
        "createPlaylist": "Créer une liste de lecture",
        "createYtFold":
            "Créer un dossier différent pour les téléchargements YouTube",
        "createYtFoldSub":
            "Créer un dossier différent pour les morceaux téléchargées depuis YouTube",
        "currentTheme": "Thème actuel",
        "darkMode": "Mode sombre",
        "date": "Date",
        "dateAdded": "Date d'ajout",
        "dec": "Décroissant",
        "delete": "Supprimer",
        "deleted": "Supprimé",
        "deleteTheme": "Supprimer le thème",
        "deleteThemeSubtitle": "Voulez-vous vraiment supprimer ?",
        "disclaimer": "Clause de non-responsabilité :",
        "disclaimerText":
            "Nous respectons votre vie privée plus que toute autre chose. Seul votre nom, que vous allez entrez ici, sera enregistré.",
        "displayName": "Nom d'affichage",
        "donateGpay": "Donner avec GPay",
        "donateGpaySub":
            "Chaque petit montant me fait sourire :)\nTapez pour faire un don ou appuyez longuement pour copier l'identifiant UPI",
        "down": "Télécharger",
        "downAgain": "existe déjà.\nVoulez-vous le retélécharger ?",
        "downDone": "Téléchargement terminé",
        "downLocation": "Emplacement du téléchargement",
        "downLyrics": "Télécharger les paroles",
        "downLyricsSub":
            "Télécharger les paroles avec le morceau, si disponible",
        "downQuality": "Qualité du téléchargement",
        "downQualitySub": "Une qualité supérieure utilise plus d'espace disque",
        "downed": "a été téléchargé",
        "downingAlbum": "Téléchargement de l'album",
        "downloadSomething": "Télécharger quelque chose",
        "downs": "Téléchargements",
        "duration": "Durée",
        "edit": "Modifier",
        "enableGesture": "Activer les gestes de l'image",
        "enableGestureSub":
            "Activer l'appui, l'appui long, le glissement, etc. sur l'image dans l'écran du lecteur",
        "enforceRepeat": "Planifier la répétition",
        "enforceRepeatSub":
            "Garder le même paramètre de répétition pour toutes les sessions",
        "enterName": "Entrez votre nom",
        "enterPlaylistLink": "Entrez le lien de la liste de lecture",
        "enterSongsCount": "Entrez le nombre de morceaux",
        "enterText": "Entrez du texte",
        "enterThemeName": "Entrez le nom du thème",
        "equalizer": "Égaliseur",
        "exitConfirm": "Rappuyez sur Retour pour quitter l'application",
        "export": "Exporter",
        "exported": "Exporté",
        "failedCreateBackup": "Échec de la création de la sauvegarde",
        "failedDelete": "Échec de la suppresion",
        "failedExport": "Échec de l'exportation",
        "failedImport": "Échec de l'importation",
        "failedTagEdit": "Échec de la modification des étiquettes",
        "favorites": "Favoris",
        "fetchingStream": "Récupération du flux audio",
        "finish": "Terminer",
        "from": "depuis",
        "genre": "Genre",
        "genres": "Genres",
        "getStarted": "Commencer",
        "global": "Global",
        "gmail": "Gmail",
        "guest": "Invité",
        "home": "Accueil",
        "homeGreet": "Bonjour,",
        "importFile": "Importer depuis un fichier",
        "importPublicPlaylist": "Importer une liste de lecture publique",
        "importSpotify": "Importer depuis Spotify",
        "importSuccess": "Importation réussie",
        "importYt": "Importer depuis YouTube",
        "inc": "Croissant",
        "insta": "Instagram",
        "ipAdd": "Adresse IP",
        "joinTg": "Rejoignez-nous sur Telegram",
        "joinTgSub":
            "Vous voulez tester les versions bêta ? Rejoignez-nous dès maintenant !",
        "lang": "Langue",
        "langQue": "Dans quelle langue préférez-vous écouter les chansons ?",
        "langSub": "Langue du texte de l'appli",
        "lastAdded": "Dernier ajout",
        "lastModified": "Dernière modification",
        "lastSession": "Session précédente",
        "latest": "Félicitations ! Vous utilisez la dernière version :)",
        "library": "Bibliothèque",
        "like": "J'aime",
        "likedWork": "Vous avez aimé mon travail ?",
        "live": "EN DIRECT",
        "liveSearch": "Recherche en direct",
        "liveSearchSub":
            "Rechercher des morceaux dès que l'utilisateur arrête d'écrire",
        "loadLast": "Charger la dernière session au démarrage de l'application",
        "loadLastSub":
            "Charger automatiquement la dernière session lors du lancement de l'application",
        "local": "Local",
        "lyrics": "Paroles",
        "madeBy": "Fait avec ♥ par Ankit Sangwan",
        "minAudioAlert": "Taille minimale de l'audio (en sec)",
        "minAudioLen": "Taille minimale de l'audio pour rechercher",
        "minAudioLenSub":
            "Les audios dont la longueur est inférieure à celle-ci ne seront pas affichés dans la section « Ma musique »",
        "miniButtons": "Boutons à afficher dans le mini-lecteur",
        "miniButtonsSub":
            "Appuyez pour changer les boutons affichés du mini-lecteur",
        "minutes": "minutes",
        "moreInfo": "Plus d'infos",
        "musicLang": "Langue de la musique",
        "musicLangSub": "Pour afficher des morceaux sur l'écran d'accueil",
        "musicPlayback": "Musique et lecture",
        "myMusic": "Ma musique",
        "no": "Non",
        "noFolderSelected": "Aucun dossier sélectionné",
        "noLangSelected":
            "Aucune langue de musique sélectionnée. Sélectionnez une langue pour afficher les chansons sur l'écran d'accueil",
        "notAvailable": "Indisponible",
        "nothingIs": "Rien est ",
        "nothingPlaying": "Aucune lecture en cours",
        "nothingTo": "Rien à ",
        "nowPlaying": "En lecture",
        "ok": "OK",
        "or": "OU",
        "others": "Autres",
        "pause": "Pause",
        "play": "Lecture",
        "playNext": "Écouter ensuite",
        "playSomething": "Faites jouer quelque chose",
        "playing": "En lecture",
        "playingCap": "EN LECTURE",
        "playlistShareText": "Jette un œil à ma liste de lecture !",
        "playlists": "Listes de lecture",
        "popularity": "Popularité",
        "port": "Port",
        "prefReq": "Voulez-vous nous dire quelque chose ?",
        "proxySet": "Paramètres du proxy",
        "proxySetSub": "Changer l'IP et le port du proxy",
        "rememberChoice": "Se souvenir de mon choix",
        "remove": "Retirer",
        "removed": "Retiré",
        "removedFrom": "Retiré de",
        "removedFromFav": "Retiré des Favoris",
        "rename": "Renommer",
        "reset": "Réinitialiser",
        "restore": "Restaurer",
        "restoreSub":
            "Restaurer vos données depuis une sauvegarde.\nVous devrez probablement relancer l'application\n",
        "resultsNotFound": "Aucun résultat trouvé",
        "savePlaylist": "Sauvegarder la liste de lecture",
        "saveTheme": "Sauvegarder le thème",
        "search": "Rechercher",
        "searchHome": "Accueil des recherches",
        "searchText": "Chansons, albums ou artistes",
        "searchVideo": "Rechercher la vidéo",
        "searchYt": "Rechercher sur YouTube",
        "selectBackFile": "Sélectionner un fichier de sauvegarde",
        "selectBackLocation": "Sélectionner l'emplacement de sauvegarde",
        "selectDownLocation": "Sélectionner l'emplcament des téléchargements",
        "selectDur": "Sélectionner une durée",
        "selectExportLocation": "Sélectionner l'emplacement d'exportation",
        "selectJsonImport": "Sélectionner le fichier JSON à importer",
        "settings": "Réglages",
        "share": "Partager",
        "shareApp": "Partager l'application",
        "shareAppSub": "Faites-nous connaître à vos amis",
        "shareAppText": "Coucou ! Jette un œil à ce lecteur de musique",
        "showHere": "Afficher ici",
        "showHistory": "Afficher l'historique de recherche",
        "showHistorySub":
            "Afficher l'historique de recherche sous la barre de recherche",
        "showLast": "Afficher la dernière session",
        "showLastSub": "Afficher la dernière session sur l'écran d'accueil",
        "showQr": "Afficher le code QR",
        "shuffle": "Aléatoire",
        "size": "Taille",
        "skip": "Passer",
        "skipNext": "Passer au suivant",
        "skipPrevious": "Passer au précédent",
        "sleepAfter": "Arrêter après N titres",
        "sleepAfterSub":
            "La musique s'arrêtera après la lecture du nombre de titres séléctionnés",
        "sleepDur": "Arrêter après une durée de hh:mm",
        "sleepDurSub": "La musique s'arrêtera à la fin de cette durée",
        "sleepTimer": "Minuterie de veille",
        "sleepTimerSetFor": "Minuterie de veille réglée sur",
        "song": "Morceau",
        "songInfo": "Infos sur le morceau",
        "songPath": "Chemin d'accès du morceau",
        "songs": "Morceaux",
        "sorry": "DÉSOLÉ",
        "sponsor": "Parrainez ce projet",
        "spotifyCharts": "Classements Spotify",
        "spotifyPublic": "Spotify public",
        "spotifyTopCharts": "Palmarès Spotify",
        "stopDown": "Arrêter le téléchargement",
        "stopOnClose": "Arrêter la musique à la fermeture de l'appli",
        "stopOnCloseSub":
            "Si ceci est désactivé, la musique ne s'arrêtera pas, même après la fermeture de l'application, tant que vous n'aurez pas appuyé sur le bouton « Arrêter ». Cette option s'applique à la fermeture de l'application et non à son arrière-plan. La musique sera toujours diffusée en arrière-plan, vous n'avez pas besoin de modifier les paramètres pour cela.\n",
        "streamQuality": "Qualité du flux",
        "streamQualitySub": "Une meilleure qualité utilise plus de données",
        "successTagEdit": "Les étiquettes ont bien été modifiées !",
        "supportEq": "Utiliser l'égaliseur",
        "supportEqSub":
            "Désactivez cette option si vous ne pouvez pas lire la musique (en mode en ligne et hors ligne)",
        "tg": "Telegram",
        "tgCh": "Canal Telegram",
        "tgGp": "Groupe Telegram",
        "theme": "Thème",
        "themeDeleted": "Thème supprimé !",
        "themeSaved": "Thème sauvegardé !",
        "title": "Titre",
        "trendingSearch": "Tendances",
        "ui": "Interface utilisateur",
        "undo": "Annuler",
        "unknown": "Inconnu",
        "unlike": "Je n'aime plus",
        "update": "Mettre à jour",
        "updateAvailable": "Mise à jour disponible !",
        "upiCopied": "UPI ID copié !",
        "useAmoled": "Utiliser les paramètres du mode sombre AMOLED",
        "useDenseMini": "Utiliser un mini-lecteur compact",
        "useDenseMiniSub": "La taille du mini-lecteur sera réduite",
        "useDominant": "Utiliser la couleur principale pour le Lecteur",
        "useDominantSub":
            "La couleur dominante de l'image sera utilisée pour l'arrière-plan du lecteur. Si ceci est désactivé, le dégradé par défaut sera utilisé",
        "useDown": "Jouer la musique téléchargée, si disponible",
        "useDownSub":
            "Si la musique est déjà téléchargée, elle sera jouée au lieu du flux en ligne",
        "useHome":
            "Utilisez la section principale pour une meilleure qualité et les téléchargements",
        "useProxy": "Utiliser un proxy",
        "useProxySub":
            "Activez cette option si vous ne venez pas d'Inde et que vous rencontrez des problèmes de recherche, comme obtenir uniquement des chansons indiennes ou ne pas obtenir de résultats, etc. Vous pouvez même utiliser RPV avec serveur indien\n",
        "useSystemTheme": "Utiliser le thème du système",
        "useVpn":
            "Vous ne venez pas d'Inde ? Essayez d'utiliser un RPV avec un serveur indien",
        "version": "Version",
        "versionSub": "Appuyer pour vérifier les mises à jour",
        "viewAlbum": "Voir l'album",
        "viewAll": "Tout afficher",
        "watchVideo": "Regarder la vidéo",
        "welcome": "Bienvenue",
        "willPlayNext": "sera joué ensuite",
        "year": "Année",
        "yes": "Oui",
        "yesReplace": "Oui, mais remplacer l'ancienne",
        "youTube": "YouTube",
        "ytLiveAlert":
            "Soit la vidéo est en direct, soit une erreur s'est produite. Veuillez attendre la fin de la diffusion en direct ou réessayer.",
        "useDominantFullScreen":
            "Utiliser une couleur dominante pour l'ensemble de l'écran de lecture",
        "useDominantFullScreenSub":
            "La couleur dominante de l'image sera utilisée pour l'arrière-plan de tout l'écran de lecture. Disponible uniquement si l'option Utiliser la dominante est activée",
        "favSongs": "Morceaux favoris",
        "viewArtist": "Voir l'artiste",
        "excluded": "Exclus",
        "excludedDetails":
            "Les morceaux des dossiers sélectionnés ne seront pas affichés",
        "includeExcludeFolder": "Inclure/exclure des dossiers",
        "includeExcludeFolderSub":
            "Inclure/exclure les dossiers sélectionnés de la section « Ma musique »",
        "includedDetails":
            "Seuls les morceaux des dossiers sélectionnés seront affichés",
        "downFilename": "Format du nom de téléchargement",
        "downFilenameSub":
            "Les morceaux seront téléchargés selon le format de nom de fichier suivant",
        "included": "Inclus",
        "getLyricsOnline": "Recherche de paroles de chansons locales",
        "getLyricsOnlineSub":
            "Recherchez en ligne si les paroles ne sont pas disponibles/téléchargées pour une chanson hors ligne",
        "importResso": "Importer depuis Resso",
        "ytStreamQuality": "Qualité du streaming sur YouTube",
        "ytDownQuality": "Qualité de téléchargement de YouTube",
        "ytDownQualitySub":
            "Une qualité supérieure utilise plus d'espace disque",
        "ytStreamQualitySub": "Une qualité supérieure utilise plus de données",
        "useDominantAndDarkerColorsSub":
            "La couleur dominante et la couleur la plus foncée de l'image seront utilisées comme dégradé de l'arrière-plan de l'écran du lecteur. Disponible uniquement si l'option Utiliser la dominante est activée (les résultats sont meilleurs si l'option Utiliser la dominante pour tout l'écran est activée)",
        "useBlurForNowPlayingSub":
            "Un floutage avec une opacité plus faible sera utilisé comme arrière-plan de la section À l'écoute",
        "useBlurForNowPlaying":
            "Utiliser le floutage à l'arrière-plan de la section À l'écoute",
        "useDominantAndDarkerColors":
            "Utiliser des couleurs dominantes et plus sombres pour l'écran de lecture",
        "upNext": "Juste après",
        "confirmViewable": "Assurez-vous que la liste de lecture est visible",
        "autoBackLocation": "Emplacement de la sauvegarde automatique",
        "showPlaylists": "Afficher les listes de lecture sur l'écran d'accueil",
        "yourPlaylists": "Vos listes de lecture",
        "playerScreenBackground": "Arrière-plan de l'écran du lecteur",
        "importJioSaavn": "Importer de JioSaavn",
        "playerScreenBackgroundSub":
            "L'arrière-plan sélectionné sera affiché dans l'écran du lecteur",
        "resetOnSkip": "Rejouer quand on passe au précédent",
        "resetOnSkipSub":
            "Rejouer depuis le début au lieu de passer à la chanson précédente",
        "topCharts": "Meilleurs classements",
        "playRadio": "Écouter la radio",
        "importPlaylist": "Importer une liste de lecture",
        "mergePlaylists": "Fusionner les listes de lectures",
        "top": "Haut",
        "viral": "Viral",
        "openInSpotify": "Ouvrir dans Spotify",
        "signInSpotify": "Se connecter à Spotify",
        "shareLogs": "Partager les journaux",
        "shareLogsSub": "Partager les journaux des sessions en cours",
        "radio": "Radio",
        "cantFind": "Vous ne trouvez pas ce que vous cherchez ? ",
        "showTopCharts": "Afficher les classements",
        "showTopChartsSub":
            "Afficher les classements de Spotify sur l'écran d'accueil",
        "songsPlayed": "Musiques jouées",
        "stats": "Statistiques",
        "mostPlayedSong": "Musique la plus jouée",
        "compactNotificationButtonsSub":
            "Boutons à afficher dans la vue de notification compacte",
        "compactNotificationButtons": "Boutons de notification compacts",
        "compactNotificationButtonsHeader":
            "Vous pouvez sélectionner au maximum 3 boutons",
      };
}
