class HE {
  static Map<String, String> get keys => {
        "about": "על אודות",
        "aboutLine1": "זה מיזם קוד פתוח שניתן למצוא תחת",
        "addToPlaylist": "הוספה לרשימת נגינה",
        "addToQueue": "הוספה לתור",
        "bgGradSub": "מדרג שישמש כרקע בכל מקום",
        "aboutLine2": "אם אהבת את היצירה שלי.\nאשמח לקצת ♥ ו־⭐ למאגר",
        "addedBy": "נוסף על ידי",
        "addedTo": "נוסף אל",
        "addedToFav": "נוסף למועדפים",
        "addedToPlaylists": "נוסף לרשימות נגינה",
        "addedToQueue": "נוסף לתור",
        "adjustSpeed": "כוונון המהירות",
        "album": "אלבום",
        "albumArtist": "אומן האלבום",
        "albums": "אלבומים",
        "alphabetical": "לפי אלפבית",
        "alreadyExists": "כבר קיים",
        "alreadyInQueue": "כבר בתור",
        "appTitle": "BlackHole",
        "artist": "אומן",
        "artists": "אומנים",
        "autoBack": "גיבוי אוטומטי",
        "autoBackLocation": "מיקום הגיבוי האוטומטי",
        "autoBackSub": "לגבות את הנתונים אוטומטית",
        "autoplay": "נגינה אוטומטית",
        "autoplaySub": "להוסיף את השירים המתאימים לתור אוטומטית",
        "backNRest": "גיבוי ושחזור",
        "backupSuccess": "הגיבוי הצליח",
        "blacklistedHomeSectionsSub":
            "אזורים עם הכותרות האלו לא יופיעו במסך הבית",
        "bottomGrad": "מדרג הגיליונות התחתונים",
        "bottomGradSub": "מדרג שישמש את הגיליונות התחתונים",
        "buyCoffee": "להזמין אותי לקפה",
        "cache": "מטמון",
        "cacheSong": "שירים במטמון",
        "cacheSongSub":
            "שירים יישמרו במטמון לנגינה עתידית. נדרש מקום נוסף במכשיר שלך",
        "cantAddToQueue": "לא ניתן להוסיף שירים מקוונים לתור בלתי מקוון",
        "canvasColor": "צבע משטח הציור",
        "cardColorSub": "צבע סרגל החיפוש, חלוניות ההתראה, כרטיסים",
        "cardGrad": "מדרג כרטיס",
        "cardGradSub": "מדרג שישמש את הכרטיסים",
        "changeDefault": "החלפה לברירת מחדל",
        "changeOrder": "אפשר לסדר מחדש בלחיצה ארוכה\n",
        "chartLocationSub": "מדינת המצעדים המקומיים המובילים של Spotify",
        "checkUpdate": "לבדוק אוטומטית אם יש עדכונים",
        "clear": "פינוי",
        "confirmViewable": "יש לוודא שרשימת הנגינה גלויה",
        "connectingRadio": "מתבצעת התחברות לרדיו…",
        "contactUs": "ליצור אתנו קשר",
        "convertingSongs": "שירים מומרים",
        "copied": "הועתק ללוח הגזירים!",
        "copy": "העתקה",
        "countryQue": "לאיזו מדינה להציג את המצעדים המקומיים של Spotify?",
        "createAlbumFold": "ליצור תיקייה להורדת אלבומים ורשימות נגינה",
        "createBack": "יצירת גיבוי",
        "createBackSub": "יצירת גיבוי של הנתונים שלך",
        "createYtFold": "יצירת תיקייה שונה עבור הורדות מ־YouTube",
        "createYtFoldSub": "יצירת תיקייה שונה עבור שירים שנשמרים מ־YouTube",
        "darkMode": "מצב כהה",
        "deleteThemeSubtitle": "למחוק?",
        "disclaimer": "כתב ויתור:",
        "disclaimerText":
            "אנו מכבדים את הפרטיות שלך יותר מכל דבר אחר. רק השם, שימולא כאן, יתועד.",
        "displayName": "שם התצוגה",
        "donateGpay": "תרומה עם GPay",
        "donateGpaySub":
            "כל סכום קטן גורם לי לחייך :)\nאפשר לתרום בנגיעה או בלחיצה ארוכה להעתקת מחרוזת הזיהוי",
        "down": "הורדה",
        "downAgain": "כבר קיים.\nלהוריד שוב?",
        "downDone": "ההורדה הושלמה",
        "downFilenameSub": "השירים יישמרו לפי תבנית שם קובץ זו",
        "downFilename": "תבנית שם ההורדה",
        "downLyricsSub": "מילות השירים יורדו לצד השיר, אם הן זמינות",
        "downQuality": "איכות ההורדה",
        "downingAlbum": "אלבום יורד",
        "downs": "הורדות",
        "duration": "משך",
        "edit": "עריכה",
        "enforceRepeat": "אילוץ חזרה",
        "enableGesture": "הפעלת מחוות על יצירת אומנות",
        "enforceRepeatSub": "לשמור על אותה אפשרות חזרה בכל הפעלה",
        "enterName": "נא למלא את השם שלך",
        "enterPlaylistLink": "מילוי קישור לרשימת נגינה",
        "enterSongsCount": "מילוי מספר שירים",
        "enterThemeName": "מילוי שם הסגנון",
        "equalizer": "אקוולייזר",
        "excluded": "הוחרג",
        "exitConfirm": "חזרה פעם נוספת תצא מהיישומון",
        "export": "ייצוא",
        "failedDelete": "המחיקה נכשלה",
        "failedExport": "הייצוא נכשל",
        "failedImport": "הייבוא נכשל",
        "failedTagEdit": "עריכת התגיות נכשלה",
        "fetchingStream": "תזרימי השמע מתקבלים",
        "finish": "סיום",
        "getLyricsOnline": "חיפוש מילים של שירים מקומיים",
        "accent": "צבע וגוון משניים",
        "addSomething": "קדימה, להוסיף לפה משהו",
        "back": "חזרה",
        "bgGrad": "מדרג רקע",
        "addNew": "הוספת חדש",
        "blacklistedHomeSections": "אזורים בעמוד הבית שנחסמו",
        "canvasColorSub": "צבע רקע משטח הציור",
        "cardColor": "צבע כרטיס",
        "chartLocation": "מיקום המצעדים המקומיים של Spotify",
        "cancel": "ביטול",
        "checkingUpdate": "מתבצע איתור עדכונים…",
        "contactUsSub": "המשוב שלך חשוב!",
        "dateAdded": "תאריך ההוספה",
        "downed": "הורד",
        "enableGestureSub":
            "הפעלת נגיעה, לחיצה ארוכה, החלקה ועוד על יצירת האומנות במסך הנגן",
        "clearAll": "פינוי של הכול",
        "date": "תאריך",
        "downQualitySub": "איכות גבוהה יותר משתמשת ביותר מקום בכונן",
        "clearCache": "פינוי הפרטים שנשמרו",
        "createAlbumFoldSub":
            "יצירת תיקייה משותפת לשירים להורדת אלבום או רשימת נגינה",
        "createNewPlaylist": "יצירת רשימת נגינה חדשה",
        "createPlaylist": "יצירת רשימת נגינה",
        "currentTheme": "ערכת עיצוב נוכחית",
        "dec": "יורד",
        "delete": "מחיקה",
        "deleteTheme": "מחיקת ערכת עיצוב",
        "deleted": "נמחק",
        "downLyrics": "הורדת מילות שירים",
        "enterText": "מילוי טקסט",
        "favorites": "מועדפים",
        "from": "מתוך",
        "downLocation": "מיקום הורדה",
        "excludedDetails": "שירים מהתיקיות הנבחרות לא יופיעו",
        "exported": "עבר ייצוא",
        "downloadSomething": "להוריד משהו",
        "failedCreateBackup": "יצירת הגיבוי נכשלה",
        "favSongs": "שירים מועדפים",
        "getLyricsOnlineSub":
            "לחפש באינטרנט אם מילות השיר לא זמינות/התקבלו עבור שיר בלתי מקוון כלשהו",
        "genre": "סגנון",
        "genres": "סגנונות",
        "getStarted": "מתחילים",
        "global": "כללי",
        "gmail": "Gmail",
        "guest": "אורח",
        "home": "בית",
        "homeGreet": "שלום,",
        "importFile": "ייבוא מקובץ",
        "importJioSaavn": "ייבוא מ־JioSaavn",
        "importPublicPlaylist": "ייבוא רשימת נגינה ציבורית",
        "importResso": "ייבוא מ־Resso",
        "importSpotify": "ייבוא מ־Spotify",
        "importSuccess": "הייבוא הצליח",
        "includedDetails": "רק שירים מהתיקיות הנבחרות יופיעו",
        "importYt": "ייבוא מ־YouTube",
        "includeExcludeFolder": "לכלול/להחריג תיקיות",
        "includeExcludeFolderSub":
            "להכליל/להחריג את התיקיות הנבחרות מאזור ‚המוזיקה שלי’",
        "insta": "אינסטגרם",
        "ipAdd": "כתובת IP",
        "joinTg": "ניתן להצטרף אלינו בטלגרם",
        "joinTgSub":
            "מעניין אותך לבדוק גרסאות ניסיוניות? אפשר להצטרף אלינו כעת!",
        "lang": "שפה",
        "langQue": "לשירים באילו שפות ברצונך להאזין?",
        "langSub": "שפת כיתוב היישומון",
        "included": "כלול",
        "madeBy": "נוצר ב־♥ על ידי אנקיט סנגוואן",
        "minAudioAlert": "אורך מקטע השמע המזערי (בשניות)",
        "minAudioLen": "אורך מקטע שמע מזערי לחיפוש מוזיקה",
        "minAudioLenSub":
            "קטעי שמע קצרים מהגדרה זו לא יופיעו באזור ‚המוזיקה שלי’",
        "miniButtons": "כפתורים להצגה בנגן המוקטן",
        "miniButtonsSub": "נגיעה תחליף את הכפתורים שמופיעים בנגן המוקטן",
        "minutes": "דקות",
        "moreInfo": "מידע נוסף",
        "musicLang": "שפת המוזיקה",
        "lastSession": "הפעלה אחרונה",
        "latest": "ברכות! זאת הגרסה העדכנית ביותר :)",
        "library": "ספריה",
        "like": "לייק",
        "likedWork": "אהבת את היצירה שלי?",
        "live": "חי כעת",
        "liveSearch": "חיפוש חי",
        "liveSearchSub": "לחפש שירים מיד בתום ההקלדה",
        "loadLast": "לטעון את ההפעלה האחרונה עם פתיחת היישומון",
        "local": "מקומי",
        "lyrics": "מילות השירים",
        "myMusic": "המוזיקה שלי",
        "musicLangSub": "כדי להציג שירים במסך הבית",
        "musicPlayback": "מוזיקה ונגינה",
        "no": "לא",
        "noFolderSelected": "לא נבחרה תיקייה",
        "noLangSelected":
            "לא נבחרה שפה למוזיקה. נא לבחור שפה כדי לצפות בשירים במסך הבית",
        "notAvailable": "לא זמין",
        "nothingIs": "כלום לא ",
        "nothingPlaying": "כלום לא מתנגן",
        "nothingTo": "אין מה ",
        "nowPlaying": "מתנגן כעת",
        "ok": "אישור",
        "or": "או",
        "others": "אחרים",
        "pause": "השהיה",
        "play": "נגינה",
        "playerScreenBackground": "רקע מסך הנגן",
        "playerScreenBackgroundSub": "הרקע הנבחר יופיע במסך הנגן",
        "playNext": "לנגן את הבא",
        "playSomething": "קדימה, לנגן משהו",
        "playing": "מתנגן",
        "playingCap": "מתנגן",
        "playlistShareText": "הנה רשימת הנגינה שלי!",
        "playlists": "רשימות נגינה",
        "popularity": "נפוצות",
        "port": "פתחה",
        "prefReq": "נוכל לשאול אותך כמה שאלות?",
        "proxySet": "הגדרות מתוך",
        "proxySetSub": "החלפת הפתחה וה־IP של המתווך",
        "rememberChoice": "שמירת הבחירה שלי",
        "remove": "הסרה",
        "removed": "הוסר",
        "removedFrom": "הוסר מתוך",
        "removedFromFav": "הוסר מהמועדפים",
        "rename": "שינוי שם",
        "reset": "איפוס",
        "yes": "כן",
        "welcome": "ברוך בואך",
        "willPlayNext": "הבא שיתנגן",
        "year": "שנה",
        "watchVideo": "הצגת הסרטון",
        "viewAlbum": "הצגת אלבום",
        "versionSub": "נגיעה לבדיקת עדכונים",
        "version": "גרסה",
        "useVpn": "לא מהודו? כדאי לנסות להשתמש ב־VPN עם שרת הודי",
        "ytStreamQuality": "איכות התזרים מ־YouTube",
        "ytStreamQualitySub": "איכות גבוהה יותר דורשת יותר נתונים",
        "ytDownQuality": "איכות ההורדה מ־YouTube",
        "ytDownQualitySub": "איכות גבוהה יותר דורשת יותר נפח בכונן",
        "yourPlaylists": "רשימות הנגינה שלך",
        "youTube": "‎YouTube",
        "yesReplace": "כן, אבל להחליף את הישן",
        "viewAll": "להציג הכול",
        "viewArtist": "הצגת אומן",
        "loadLastSub": "לטעון את ההפעלה האחרונה אוטומטית עם פתיחת היישומון",
        "checkUpdateSub":
            "אם הורדת את BlackHole מכל חנות יישומונים כגון ‚F-Droid‚, 'IzzyOnDroid’ וכו׳ שמספקות אפשרות לעדכון, יש לכבות אותה! עם זאת, אם הורדת אותו מ־‚GitHub’ או מכל מקור אחר שלא מספק עדכונים אוטומטיים כדאי להפעי את זה על מנת שיתקבלו התראות עדכון\n",
        "inc": "עולה",
        "lastAdded": "נוסף לאחרונה",
        "lastModified": "שונה לאחרונה",
        "restore": "שחזור",
        "resultsNotFound": "לא נמצאו תוצאות",
        "useBlurForNowPlayingSub":
            "ייעשה שימוש בטשטוש עם אטימות נמוכה בתור הרקע של האזור של מה שמתנגן כרגע",
        "useDenseMini": "להשתמש בנגן ממוזער צפוף",
        "useAmoled": "להשתמש בהגדרות המצב הכהה של ה־Amoled",
        "supportEqSub":
            "יש להשאיר את זה כבוי אם ניגון שירים נכשל (במצבים מקוון ובלתי מקוון)",
        "streamQualitySub": "איכות גבוהה יותר צורכת יותר תעבורה",
        "streamQuality": "איכות תזרים",
        "saveTheme": "שמירת ערכת העיצוב",
        "savePlaylist": "שמירת רשימת הנגינה",
        "search": "חיפוש",
        "searchHome": "עמוד הבית של החיפוש",
        "searchText": "שירים, אלבומים או אומנים",
        "searchVideo": "חיפוש סרטון",
        "searchYt": "חיפוש ב־YouTube",
        "selectBackFile": "בחירת קובץ גיבוי",
        "resetOnSkip": "לנגן שוב בדילוג על הקודם",
        "resetOnSkipSub": "לנגן שוב מההתחלה במקום לדלג לשיר הקודם",
        "selectBackLocation": "בחירת מיקום גיבוי",
        "selectDownLocation": "בחירת מיקום הורדה",
        "selectDur": "בחירת משך",
        "selectExportLocation": "בחירת מיקום לייצוא",
        "selectJsonImport": "בחירת קובץ JSON לייבוא",
        "settings": "הגדרות",
        "share": "שיתוף",
        "shareApp": "שיתוף היישומון",
        "shareAppSub": "לספר עלינו לחבר׳ה",
        "shareAppText": "היי! תראו איזה נגן מוזיקה מעולה מצאתי",
        "showHere": "להציג כאן",
        "showHistory": "הצגת היסטוריית החיפוש",
        "showHistorySub": "הצגת היסטוריית החיפוש מתחת לסרגל החיפוש",
        "showLast": "הצגת ההפעלה האחרונה",
        "showPlaylists": "הצגת רשימות נגינה במסך הבית",
        "showQr": "הצגת קוד QR",
        "shuffle": "ערבול",
        "skip": "דילוג",
        "skipNext": "דילוג על הבא",
        "skipPrevious": "דילוג על הקודם",
        "useDown": "להזרים שירים שהורדו, אם יש",
        "useDenseMiniSub": "גובה הנגן הממוזער יוקטן",
        "successTagEdit": "התגיות נערכו בהצלחה!",
        "tg": "טלגרם",
        "tgGp": "קבוצה בטלגרם",
        "themeSaved": "ערכת העיצוב נשמרה!",
        "title": "כותרת",
        "trendingSearch": "חיפוש במובילים",
        "ui": "מנשק המשתמש של היישומון",
        "undo": "ביטול",
        "unknown": "לא ידוע",
        "unlike": "לא משהו",
        "update": "עדכון",
        "updateAvailable": "יש עדכון!",
        "upNext": "הבא בתור",
        "useSystemTheme": "להשתמש בערכת העיצוב של המערכת",
        "useProxySub":
            "יש לכבות את זה אם מיקומך אינו הודו ויש לך בעיות עם החיפוש, כמו למשל אם מתקבלים רק שירים הודיים או שלא מתקבלות תוצאות וכו׳. אפשר אפילו להשתמש ב־VPN עם שרת הודי.\n",
        "useHome": "להשתמש באזור המרכזי לשיפור האיכות ולתמיכה בהורדה",
        "useProxy": "להשתמש במתווך",
        "useDownSub":
            "אם שיר כבר ירד בעבר, השיר שירד יתנגן במקום להזרים מהאינטרנט",
        "showLastSub": "הצגת ההפעלה האחרונה במסך הבית",
        "size": "גודל",
        "sleepAfter": "מצב שינה אחרי N שירים",
        "theme": "ערכת עיצוב",
        "themeDeleted": "ערכת העיצוב נמחקה!",
        "tgCh": "ערוץ בטלגרם",
        "restoreSub":
            "שחזור הנתונים שלך מגיבוי.\nיתכן שיהיה עליך להפעיל את היישומון מחדש\n",
        "spotifyPublic": "Spotify ציבורי",
        "spotifyCharts": "מצעדי Spotify",
        "sponsor": "מימון המיזם הזה",
        "sorry": "סליחה",
        "songs": "שירים",
        "songPath": "נתיב השיר",
        "song": "שיר",
        "spotifyTopCharts": "המצעדים המובילים ב־Spotify",
        "upiCopied": "מזהה UPI הועתק!",
        "stopOnClose": "עצירת המוזיקה עם סגירת היישומון",
        "stopDown": "עצירת ההורדה",
        "ytLiveAlert":
            "או שהווידאו בשידור חי או שקרתה איזו תקלה. נא להמתין לסיום השידור החי או לנסות שוב.",
        "sleepTimer": "מתזמן שינה",
        "sleepDurSub": "המוזיקה תיעצר לאחר משך הזמן שנבחר",
        "sleepAfterSub": "המוזיקה תיעצר לאחר נגינת מספר נבחר של שירים",
        "songInfo": "פרטי השיר",
        "sleepTimerSetFor": "מתזמן השינה הוגדר לשעה",
        "sleepDur": "להירדם לאחר משך של hh:mm",
        "stopOnCloseSub":
            "אם האפשרות כבויה, המוזיקה לא תיעצר גם אחרי ‚סגירת’ היישומון עד ללחיצה על כפתור העצירה. אפשרות זו מיועדת ל‚סגירה’ ולא כאשר היישומון ב‚רקע’. המוזיקה תמיד תתנגן ברקע ואין צורך לשנות אף הגדרה כדי שכך זה יהיה.\n",
        "clearCacheSub":
            "מוחק פרטים שמורים כולל עמוד הבית, המצעדים המובילים של Spotify,‏ YouTube ונתוני ההפעלה האחרונה. בדרך כלל היישומון מפנה את הנתונים האלו כשהם מתנפחים\n",
        "topCharts": "מצעדים מובילים",
        "playRadio": "השמעת רדיו",
        "importPlaylist": "ייבוא רשימת נגינה",
        "mergePlaylists": "מיזוג רשימות נגינה",
        "viral": "ויראלי",
        "top": "עליון",
        "openInSpotify": "פתיחה ב־Spotify",
        "signInSpotify": "כניסה ל־Spotify",
        "shareLogs": "שיתוף יומנים",
        "shareLogsSub": "שיתוף יומני הפעילות הנוכחית",
        "radio": "רדיו",
        "aboard": "ממריאים",
        "cantFind": "לא מצאת את מבוקשך? ",
        "supportEq": "תמיכה באקוולייזר",
        "showTopCharts": "הצגת טבלת המובילים",
        "showTopChartsSub": "להציג את טבלאות המובילים של Spotify במסך הבית",
        "mostPlayedSong": "השיר שנוגן הכי הרבה",
        "songsPlayed": "שירים שנוגנו",
        "stats": "סטטיסטיקה",
        "compactNotificationButtons": "כפתורים מצומצמים בהתראה",
        "compactNotificationButtonsSub": "כפתורים שיופיעו בתצוגת התראה מצומצמת",
        "compactNotificationButtonsHeader": "ניתן לבחור עד 3 כפתורים",
      };
}
