class PL {
  static Map<String, String> get keys => {
        "aboutLine1": "To jest otwartoźródłowy projekt który można znaleźć na",
        "albums": "Albumy",
        "album": "Album",
        "artist": "Artysta",
        "artists": "Artyści",
        "about": "O aplikacji",
        "accent": "Kolor Akcentów i odcień",
        "addSomething": "Przejdź i Dodaj Coś",
        "addedTo": "Dodane do",
        "addedToFav": "Dodane do Ulubionych",
        "addedToPlaylists": "Dodane do Playlist",
        "addedToQueue": "Dodane do Kolejki",
        "adjustSpeed": "Ustaw Prędkość",
        "alreadyInQueue": "Już jest w Kolejce",
        "autoBack": "Automatyczna Kopia zapasowa",
        "autoBackSub": "Automatycznie twórz kopię zapasową",
        "autoplay": "Autoodtwarzanie",
        "autoplaySub": "Automatycznie dodaj powiązane utwory do kolejki",
        "back": "Powrót",
        "backNRest": "Kopia zapasowa & Przywracanie",
        "backupSuccess": "Udało się utworzyć Kopię zapasową",
        "bgGrad": "Gradient Tła",
        "bgGradSub": "Gradient jest używany wszędzie jako tło",
        "blacklistedHomeSectionsSub":
            "Sekcje z tymi tytułami nie będą się pojawiać na Stronie głównej",
        "buyCoffee": "Kup mi kawę",
        "bottomGradSub": "Gradient używany jest w Dolnych Warstwach",
        "bottomGrad": "Gradient Dolnych Warstw",
        "cache": "Pamięć Podręczna",
        "cacheSong": "Trzymaj Utwory w Pamięci Podręcznej",
        "cantAddToQueue": "Nie można dodać Utworu Online do Kolejki Offline",
        "aboutLine2":
            "Jeżeli podoba ci się moja praca\npokaż trochę ♥ i ⭐ repozytorium",
        "addNew": "Dodaj Nowy",
        "addToQueue": "Dodaj do Kolejki",
        "addedBy": "Dodane przez",
        "addToPlaylist": "Dodaj do Playlisty",
        "albumArtist": "Artysta Albumu",
        "alphabetical": "Alfabetycznie",
        "alreadyExists": "Już Istnieje",
        "appTitle": "BlackHole",
        "blacklistedHomeSections": "Sekcje Strony głównej na Czarnej liście",
        "cacheSongSub":
            "Utwory będą zapisywane aby odtworzyć je później. Dodatkowa pamięci na urządzeniu zostanie zajęta",
        "cancel": "Anuluj",
        "ytLiveAlert":
            "Wideo jest na żywo. Poczekaj aż transmisja zakończy się i spróbuj ponownie",
        "useVpn": "Nie z Indii? Spróbuj użyć VPN z Indyjskim serwerem",
        "useDown": "Streamuj pobrane utwory, jeśli to możliwe",
        "viewAll": "Zobacz wszystkie",
        "useProxySub":
            "Włącz to jeśli nie jesteś z Indii i masz problem z wyszukiwaniem, np. jeśli dostajesz tylko Indyjskie utwory lub nie masz żadnych wyników wyszukiwania. Możesz nawet użyć VPN z Indyjskim serwerem\n",
        "useDownSub":
            "Jeżeli utwór jest już pobrany, będzie on odtworzony lokalnie zamiast online",
        "youTube": "YouTube",
        "yes": "Tak",
        "year": "Rok",
        "ytStreamQuality": "Jakość streamowania YouTube",
        "ytDownQualitySub": "Wyższa jakość zużywa więcej pamięci",
        "ytDownQuality": "Jakość pobierania YouTube",
        "ytStreamQualitySub": "Wyższa jakość zużywa więcej danych",
        "welcome": "Witaj",
        "watchVideo": "Oglądaj film",
        "viewArtist": "Zobacz artystę",
        "viewAlbum": "Zobacz album",
        "versionSub": "Kliknij by sprawdzić dostępność aktualizacji",
        "version": "Wersja",
        "useSystemTheme": "Użyj motywu systemowego",
        "useProxy": "Użyj proxy",
        "tgGp": "Grupa Telegram",
        "theme": "Motyw",
        "tg": "Telegram",
        "tgCh": "Kanał Telegram",
        "themeDeleted": "Motyw usunięty!",
        "themeSaved": "Motyw zapisany!",
        "title": "Tytuł",
        "ui": "Interfejs aplikacji",
        "undo": "Cofnij",
        "unknown": "Nieznane",
        "update": "Aktualizuj",
        "updateAvailable": "Aktualizacja dostępna!",
        "yesReplace": "Tak, ale zamień stary",
        "ipAdd": "Adres IP",
        "lang": "Język",
        "langQue": "W jakim języku preferujesz słuchać utworów?",
        "langSub": "Język Tekstu Aplikacji",
        "lastAdded": "Ostatnio Dodane",
        "lastModified": "Ostatnio Zmodyfikowane",
        "lastSession": "Ostatnia Sesja",
        "latest": "Gratulacje! Używasz najnowszej wersji :)",
        "likedWork": "Podoba Ci się moja praca?",
        "live": "NA ŻYWO",
        "loadLast": "Załaduj Ostatnią Sesję przy Starcie Aplikacji",
        "loadLastSub":
            "Automatycznie załaduj ostatnią sesję kiedy aplikacja się uruchamia",
        "lyrics": "Tekst Utworu",
        "minAudioAlert": "Minimalna Długość Utworu (w sekundach)",
        "minAudioLen": "Minimalna Długość Utworu do szukania muzyki",
        "aboard": "Na pokładzie",
        "canvasColor": "Kolor Płótna",
        "canvasColorSub": "Kolor Płótna w Tle",
        "cardColor": "Kolor Karty",
        "cardColorSub":
            "Kolor Paska Wyszukiwania, Okien Dialogowych z Ostrzeżeniami, Kart",
        "cardGrad": "Gradient Karty",
        "cardGradSub": "Gradient używany w Kartach",
        "clear": "Wyczyść",
        "clearAll": "Wyczyść Wszystko",
        "clearCache": "Wyczyść Szczegóły z Pamięci Podręcznej",
        "clearCacheSub":
            "Usuwa szczegóły z Pamięci Podręcznej, w tym Stronę Główną, Najlepsze Listy Przebojów Spotify, YouTube oraz Dane Ostatniej Sesji. Zwykle aplikacja automatycznie je usuwa gdy dane zajmują zbyt wiele miejsca\n",
        "disclaimer": "Zastrzeżenie :",
        "disclaimerText":
            "Szanujemy Twoją prywatność bardziej niż cokolwiek innego. Tylko Twoje imię, które tutaj wpiszesz, zostanie zapisane.",
        "autoBackLocation": "Lokalizacja Automatycznej Kopii Zapasowej",
        "checkUpdateSub":
            "Jeśli aplikacja BlackHole została przez Ciebie pobrana z dowolnego repozytorium aplikacji, takiego jak 'F-Droid', 'IzzyOnDroid',itp.,które zapewniają opcje aktualizacji, pozostaw to WYŁĄCZONE. W przypadku pobrania z 'GitHub' lub innego źródła, które nie zapewnia automatycznych aktualizacji, WŁĄCZ tą opcję, aby otrzymywać powiadomienia o aktualizacjach\n",
        "copy": "Skopiuj",
        "contactUsSub": "Opinie Mile Widziane!",
        "createAlbumFoldSub":
            "Tworzy wspólny folder dla Utworów, gdy pobierany jest Album lub Playlista",
        "enterName": "Wpisz Swoję Imię",
        "donateGpaySub":
            "Każda mała kwota sprawia, że się uśmiecham :)\nStuknij, aby wesprzeć lub przytrzymaj, aby skopiować UPI ID",
        "downLyrics": "Pobierz Tekst Utworu",
        "downFilenameSub":
            "Utwory będą pobierane zgodnie z tym formatem nazwy pliku",
        "equalizer": "Equalizer",
        "failedExport": "Nie udało się Wyeksportować",
        "getStarted": "Rozpocznij",
        "failedCreateBackup": "Nie udało się utworzyć Kopii Zapasowej",
        "failedImport": "Nie udało się Zaimportować",
        "getLyricsOnlineSub":
            "Wyszukaj online, jeśli tekst utworu nie jest dostępny/pobrany dla żadnego z utworów offline",
        "joinTg": "Dołącz do nas na Telegram",
        "joinTgSub": "Chcesz Stestować wersje beta? Dołącz do nas już teraz!",
        "importJioSaavn": "Zaimportuj z JioSaavn",
        "global": "Globalne",
        "gmail": "Gmail",
        "madeBy": "Zrobione z ♥ przez Ankit Sangwan",
        "local": "Lokalne",
        "changeDefault": "Zmień na Domyślne",
        "changeOrder": "Długie Naciśnięcie, aby zmienić kolejność\n",
        "chartLocation": "Lokalizacja Lokalnych List Przebojów Spotify",
        "chartLocationSub": "Kraj Najlepszych Lokalnych List Przebojów Spotify",
        "checkingUpdate": "Sprawdzanie Dostępności Aktualizacji…",
        "checkUpdate": "Automatycznie sprawdzaj Dostępność Aktualizacji",
        "confirmViewable": "Upewnij się, że playlista jest widoczna",
        "connectingRadio": "Łączenie z Radiem…",
        "contactUs": "Skontaktuj się z nami",
        "convertingSongs": "Konwertowanie Utworów",
        "copied": "Skopiowano do Schowka!",
        "countryQue":
            "Dla którego kraju chcesz zobaczyć Lokalne Listy Przebojów Spotify?",
        "createAlbumFold": "Utwórz folder do Pobierania Albumów i Playlist",
        "createBack": "Utwórz Kopię Zapasową",
        "createBackSub": "Utwórz kopię zapasową swoich danych",
        "createNewPlaylist": "Utwórz Nową Playlistę",
        "createPlaylist": "Utwórz Playlistę",
        "createYtFold": "Utwórz inny folder dla Pobranych z YouTube",
        "createYtFoldSub": "Tworzy inny folder dla Utworów pobranych z YouTube",
        "currentTheme": "Aktualny Motyw",
        "darkMode": "Tryb Ciemny",
        "date": "Data",
        "dateAdded": "Data Dodania",
        "delete": "Usuń",
        "deleted": "Usunięte",
        "deleteTheme": "Usuń Motyw",
        "deleteThemeSubtitle": "Czy na pewno chcesz usunąć?",
        "displayName": "Wyświetlana Nazwa",
        "donateGpay": "Wesprzyj używając GPay",
        "down": "Pobierz",
        "downAgain": "już istnieje.\nCzy chcesz pobrać to ponownie?",
        "downDone": "Pobieranie Zakończone",
        "downFilename": "Format Nazwy Pobranych Plików",
        "downLocation": "Lokalizacja Pobierania",
        "downLyricsSub":
            "Pobieranie tekstu utworu razem z utworem, jeśli jest dostępny",
        "downQualitySub": "Wyższa jakość zużywa więcej miejsca na dysku",
        "downed": "został pobrany",
        "downs": "Pobrane",
        "duration": "Czas trwania",
        "edit": "Edytuj",
        "enforceRepeat": "Wymuś Powtarzanie",
        "enforceRepeatSub":
            "Zachowaj tę samą opcję powtarzania dla każdej sesji",
        "enterPlaylistLink": "Wpisz Link do Playlisty",
        "enterSongsCount": "Wpisz ilość Utworów",
        "enterText": "Wpisz Tekst",
        "enterThemeName": "Wpisz nazwę motywu",
        "excluded": "Wykluczone",
        "excludedDetails": "Utwory z wybranych folderów nie będą wyświetlane",
        "export": "Eksportuj",
        "exported": "Wyeksportowano",
        "failedDelete": "Nie udało się Usunąć",
        "failedTagEdit": "Nie udało się zedytować tagów",
        "favorites": "Ulubione",
        "favSongs": "Ulubione Utwory",
        "fetchingStream": "Pobieranie Strumienia Audio",
        "finish": "Zakończ",
        "from": "z",
        "getLyricsOnline": "Wyszukaj teksty lokalnych utworów",
        "importSpotify": "Zaimportuj ze Spotify",
        "importSuccess": "Pomyślnie zaimportowano",
        "importYt": "Zaimportuj z YouTube",
        "includeExcludeFolder": "Uwzględnij/Wyklucz Foldery",
        "includeExcludeFolderSub":
            "Uwzględnia/Wyklucza wybrane foldery z Sekcji 'Moja Muzyka'",
        "included": "Uwzględnione",
        "insta": "Instagram",
        "genre": "Gatunek",
        "genres": "Gatunki",
        "guest": "Gość",
        "home": "Dom",
        "homeGreet": "Witaj,",
        "importFile": "Zaimportuj z Pliku",
        "importPublicPlaylist": "Zaimportuj Publiczne Playlisty",
        "importResso": "Zaimportuj z Resso",
        "includedDetails": "Tylko utwory z wybranych folderów będą wyświetlane",
        "library": "Biblioteka",
        "like": "Polub",
        "share": "Udostępnij",
        "liveSearch": "Wyszukiwanie Na Żywo",
        "liveSearchSub":
            "Szukaj utworów, gdy tylko użytkownik przestanie pisać",
        "minAudioLenSub":
            "Utwory o długości mniejszej niż ta nie będą wyświetlane w sekcji 'Moja Muzyka'",
        "miniButtonsSub":
            "Stuknij, aby zmienić przyciski wyświetlane w Miniodtwarzaczu",
        "moreInfo": "Więcej Informacji",
        "musicLang": "Język Muzyki",
        "musicLangSub": "Aby wyświetlić utwory na Ekranie Głównym",
        "musicPlayback": "Muzyka & Odtwarzanie",
        "myMusic": "Moja Muzyka",
        "noLangSelected":
            "Nie wybrano języka Muzyki. Wybierz język, aby zobaczyć utwory na Ekranie Głównym",
        "notAvailable": "Niedostępne",
        "nothingTo": "Nic do ",
        "nowPlaying": "Teraz Odtwarzany",
        "others": "Inni",
        "play": "Odtwórz",
        "playing": "Odtwarzanie",
        "playlistShareText": "Spójrz na moją playlistę!",
        "playlists": "Playlisty",
        "rememberChoice": "Zapamiętaj mój wybór",
        "removedFrom": "Usunięto z",
        "removedFromFav": "Usunięto z Ulubionych",
        "rename": "Zmień Nazwę",
        "resetOnSkip": "Powtórz przy Pomiń Poprzednie",
        "resetOnSkipSub":
            "Odtwórz od początku zamiast przeskakiwać do poprzedniego utworu",
        "resultsNotFound": "Nie Znaleziono Wyników",
        "savePlaylist": "Zapisz Playlistę",
        "saveTheme": "Zapisz Motyw",
        "search": "Szukaj",
        "searchHome": "Szukaj na Stronie Głównej",
        "searchText": "Utwory, albumy lub artyści",
        "searchVideo": "Szukaj Filmu",
        "searchYt": "Szukaj na YouTube",
        "selectBackFile": "Wybierz Plik Kopii Zapasowej",
        "selectDownLocation": "Wybierz Lokalizację Pobierania",
        "selectDur": "Wybierz Czas Trwania",
        "selectExportLocation": "Wybierz Lokalizację Eksportu",
        "showLast": "Wyświetlaj Ostatnią Sesję",
        "sleepTimer": "Timer Snu",
        "song": "Utwór",
        "stopDown": "Zatrzymaj Pobieranie",
        "stopOnClose": "Zatrzymaj muzykę przy Zamknięciu Aplikacji",
        "supportEq": "Wspieraj Equalizer",
        "supportEqSub":
            "Zostaw to wyłączone jeżeli nie możesz odtwarzać utworów (zarówno w trybie online, jak i offline)",
        "unlike": "Przestań Lubić",
        "upiCopied": "Skopiowano UPI ID!",
        "useAmoled": "Użyj Ustawień Trybu Ciemnego Amoled",
        "useDenseMini": "Użyj Gęstego Miniodtwarzacza",
        "useDenseMiniSub": "Wysokość miniodtwarzacza zostanie zmniejszona",
        "useHome":
            "Użyj Sekcji Głównej dla Lepszej Jakości oraz Wsparcia Pobierania",
        "yourPlaylists": "Twoje Playlisty",
        "restore": "Przywróć",
        "reset": "Zresetuj",
        "stopOnCloseSub":
            "Jeśli ta opcja jest wyłączona, muzyka nie zatrzyma się nawet kiedy aplikacja jest 'wyłączona', dopóki nie naciśniesz przycisku zatrzymania. Ta opcja dotyczy 'wyłączania' aplikacji, a nie jej działania 'w tle'. Muzyka zawsze będzie odtwarzana w tle, nie trzeba w tym celu zmieniać żadnych ustawień.\n",
        "streamQuality": "Jakość Streamingu",
        "streamQualitySub": "Wyższa jakość zużywa więcej danych",
        "successTagEdit": "Pomyślnie zedytowano tagi !",
        "dec": "Malejąco",
        "downQuality": "Jakość Pobierania",
        "downingAlbum": "Pobieranie Albumu",
        "downloadSomething": "Pobierz Coś",
        "enableGestureSub":
            "Włącza dotknięcie, długie naciśnięcie, przeciągnięcie, itp. na Okładce na Ekranie Odtwarzacza",
        "exitConfirm": "Naciśnij Ponownie Wstecz, aby Wyjść z Aplikacji",
        "enableGesture": "Włącz Gesty Okładki",
        "inc": "Rosnąco",
        "proxySet": "Ustawienia Serwera Proxy",
        "proxySetSub": "Zmień IP oraz Port Serwera Proxy",
        "showPlaylists": "Pokazuj Playlisty na Ekranie Głównym",
        "showQr": "Wyświetl Kod QR",
        "shuffle": "Pomieszaj",
        "size": "Rozmiar",
        "skipNext": "Pomiń Następny",
        "skipPrevious": "Pomiń Poprzedni",
        "sleepAfter": "Zaśnij po N Utworach",
        "sleepAfterSub":
            "Muzyka zatrzyma się po odtworzeniu wybranej liczby utworów",
        "sleepDur": "Zaśnij po upływie hh:mm",
        "sleepDurSub": "Muzyka zatrzyma się po upływie wybranego czasu",
        "songPath": "Ścieżka Utworu",
        "songs": "Utwory",
        "sorry": "PRZEPRASZAM",
        "sponsor": "Zasponsoruj ten projekt",
        "spotifyCharts": "Listy Przebojów Spotify",
        "spotifyPublic": "Publiczne Spotify",
        "spotifyTopCharts": "Najlepsze Listy Przebojów Spotify",
        "trendingSearch": "Szukaj Zyskujące Popularność",
        "upNext": "Następny W Górę",
        "skip": "Pomiń",
        "songInfo": "Informacje o Utworze",
        "sleepTimerSetFor": "Timer Snu ustawiony na",
        "prefReq": "Chcesz nam powiedzieć kilka rzeczy?",
        "miniButtons": "Przyciski wyświetlane w Miniodtwarzaczu",
        "minutes": "minuty",
        "no": "Nie",
        "noFolderSelected": "Nie wybrano Folderu",
        "or": "LUB",
        "selectJsonImport": "Wybierz plik JSON do importu",
        "nothingPlaying": "Nic nie jest Odtwarzane",
        "ok": "Ok",
        "playerScreenBackground": "Tło Ekranu Odtwarzacza",
        "playNext": "Odtwórz Następny",
        "nothingIs": "Nic nie jest ",
        "pause": "Pauza",
        "playSomething": "Idź i Odtwórz Coś",
        "playingCap": "ODTWARZANIE",
        "port": "Port",
        "remove": "Usuń",
        "removed": "Usunięto",
        "playerScreenBackgroundSub":
            "Wybrane Tło będzie wyświetlane na Ekranie Odtwarzacza",
        "popularity": "Popularność",
        "restoreSub":
            "Przywróć swoje dane z Kopii Zapasowej.\nKonieczne może być zrestartowanie aplikacji\n",
        "settings": "Ustawienia",
        "shareApp": "Udostępnij Aplikację",
        "showHistorySub":
            "Wyświetlaj Historię Wyszukiwania pod Paskiem Wyszukiwania",
        "shareAppSub": "Powiedz o nas swoim znajomym",
        "shareAppText": "Hej! Sprawdź tę fajną aplikację do odtwarzania muzyki",
        "showHistory": "Wyświetlaj Historię Wyszukiwania",
        "selectBackLocation": "Wybierz Lokalizację Kopii Zapasowej",
        "showHere": "Pokaż Tutaj",
        "showLastSub": "Pokazuj Ostatnią sesję na Ekranie Głównym",
        "useBlurForNowPlayingSub":
            "Rozmycie z mniejszą Przezroczystością będzie używane jako Tło Sekcji Teraz Odtwarzane",
        "willPlayNext": "Odtworzy Następny",
        "cantFind": "Nie możesz znaleźć tego czego szukasz? ",
      };
}
