class NL {
  static Map<String, String> get keys => {
        "autoplay": "Automatisch afspelen",
        "autoplaySub":
            "Gerelateerde nummers automatisch toevoegen aan wachtrij",
        "buyCoffee": "Doneren",
        "aboard": "Aboard",
        "about": "Over",
        "aboutLine1": "Dit opensourceproject is te vinden op",
        "addedToPlaylists": "Toegevoegd aan afspeellijsten",
        "addedToQueue": "Toegevoegd aan wachtrij",
        "appTitle": "BlackHole",
        "artists": "Artiesten",
        "backNRest": "Back-up en herstel",
        "bgGradSub":
            "Het kleurverloop dat overal als achtergrond wordt gebruikt",
        "addSomething": "Voeg iets toe",
        "backupSuccess": "Het back-uppen is voltooid",
        "aboutLine2":
            "Als je mijn werk aan deze app waardeert,\ndeel dan de ♥ en voeg de repo toe aan je ⭐",
        "addNew": "Toevoegen",
        "addToPlaylist": "Toevoegen aan afspeellijst",
        "addedBy": "Toegevoegd door",
        "albumArtist": "Albumartiest",
        "alreadyInQueue": "Staat al in de wachtrij",
        "artist": "Artiest",
        "blacklistedHomeSections": "Genegeerde startsecties",
        "addToQueue": "Toevoegen aan wachtrij",
        "addedToFav": "Toegevoegd aan favorieten",
        "adjustSpeed": "Snelheid aanpassen",
        "accent": "Accentkleur en tint",
        "addedTo": "Toegevoegd aan",
        "autoBackSub": "Gegevens automatisch back-uppen",
        "album": "Album",
        "albums": "Albums",
        "alphabetical": "Alfabetisch",
        "alreadyExists": "Is al toegevoegd",
        "autoBack": "Automatisch back-uppen",
        "back": "Terug",
        "bgGrad": "Achtergrondverloop",
        "blacklistedHomeSectionsSub":
            "Secties met deze namen worden niet getoond op de startpagina",
        "bottomGradSub":
            "Het kleurverloop dat op de onderste pagina wordt gebruikt",
        "cache": "Cache",
        "cacheSong": "Nummers opslaan in cache",
        "bottomGrad": "Verloop van onderste pagina",
        "convertingSongs": "Nummers converteren",
        "cardColorSub": "De kleur van de zoekbalk, meldingsvensters en kaarten",
        "changeDefault": "Standaardwaarde herstellen",
        "cardGradSub": "Het kleurverloop van kaarten",
        "copied": "Gekopieerd naar het klembord!",
        "changeOrder": "Houd ingedrukt om de volgorde aan te passen\n",
        "contactUsSub": "Feedback wordt zeer gewaardeerd!",
        "chartLocation": "Locatie van lokale Spotify-hitlijst",
        "copy": "Kopiëren",
        "createNewPlaylist": "Afspeellijst samenstellen",
        "date": "Datum",
        "dec": "Aflopend",
        "dateAdded": "Toegevoegd",
        "cacheSongSub":
            "Nummers worden opgeslagen in de cache zodat ze later kunnen worden afgespeeld. Let op: dit neemt extra ruimte in beslag.",
        "cancel": "Annuleren",
        "cantAddToQueue":
            "Online-nummers kunnen niet offline worden opgeslagen",
        "canvasColor": "Canvaskleur",
        "canvasColorSub": "De kleur van het achtergrondcanvas",
        "cardColor": "Kaartkleur",
        "cardGrad": "Kleurverloop",
        "chartLocationSub": "Land van Spotify-hitlijst",
        "checkingUpdate": "Bezig met controleren…",
        "checkUpdate": "Automatisch controleren op updates",
        "clear": "Wissen",
        "clearAll": "Alles wissen",
        "clearCache": "Informatie uit cache wissen",
        "confirmViewable": "Zorg er voor dat de afspeellijst in te zien is",
        "connectingRadio": "Bezig met verbinden…",
        "contactUs": "Contact opnemen",
        "countryQue": "Van welk land wil je de lokale Spotify-hitlijst zien?",
        "createAlbumFold": "Map aanmaken voor album en afspeellijst downloaden",
        "createAlbumFoldSub":
            "Maakt een algemene map aan voor nummers zodra een album of afspeellijst offline wordt opgeslagen",
        "createBack": "Back-up maken",
        "createBackSub": "Maak een back-up van je gegevens",
        "createPlaylist": "Afspeellijst samenstellen",
        "createYtFold": "Andere map gebruiken voor YouTube-downloads",
        "createYtFoldSub":
            "Maak een andere map aan voor nummers die worden gedownload van YouTube",
        "currentTheme": "Huidig thema",
        "darkMode": "Donker thema",
        "delete": "Verwijderen",
        "deleted": "Verwijderd",
        "deleteTheme": "Thema verwijderen",
        "deleteThemeSubtitle":
            "Weet je zeker dat je dit thema wilt verwijderen?",
        "disclaimer": "Vrijwaring:",
        "enterSongsCount": "Voer het aantal nummers in",
        "enterPlaylistLink": "Voer een afspeellijstlink in",
        "downQualitySub": "Hogere kwaliteit neemt meer ruimte in beslag",
        "failedDelete": "Het verwijderen is mislukt",
        "downFilenameSub":
            "Nummers worden gedownload met deze bestandsnaamopmaak",
        "downLyricsSub":
            "Download songteksten tegelijk met nummers (indien beschikbaar)",
        "downQuality": "Downloadkwaliteit",
        "enableGestureSub":
            "Schakel drukken, ingedrukt houden, vegen, etc. in op albumhoezen op het afspeelscherm",
        "enterThemeName": "Voer een themanaam in",
        "equalizer": "Equalizer",
        "exported": "Het exporteren is voltooid",
        "failedImport": "Het importeren is mislukt",
        "downed": "is gedownload",
        "downingAlbum": "Bezig met downloaden van album…",
        "downloadSomething": "Download iets",
        "downs": "Downloads",
        "duration": "Duur",
        "edit": "Bewerken",
        "enableGesture": "Gebaren inschakelen op albumhoezen",
        "downLocation": "Downloadlocatie",
        "downLyrics": "Songteksten ophalen",
        "excluded": "Uitgesloten",
        "excludedDetails": "Nummers uit de gekozen mappen worden niet getoond",
        "exitConfirm": "Druk nogmaals op de terugknop om af te sluiten",
        "export": "Exporteren",
        "failedCreateBackup": "Er kan geen back-up worden gemaakt",
        "enforceRepeat": "Altijd herhalen",
        "enforceRepeatSub": "Herhaal standaard alle nummers",
        "enterName": "Voer je naam in",
        "failedExport": "Het exporteren is mislukt",
        "failedTagEdit": "De tags kunnen niet worden bewerkt",
        "favorites": "Favorieten",
        "favSongs": "Favoriete nummers",
        "fetchingStream": "Bezig met ophalen van audiostream…",
        "finish": "Afronden",
        "enterText": "Voer tekst in",
        "disclaimerText":
            "Privacy staat bij ons hoog in het vaandel. Het enige wat we vastleggen is de naam die je hier opgeeft.",
        "displayName": "Getoonde naam",
        "donateGpay": "Doneren met GPay",
        "donateGpaySub":
            "Zelfs met de kleinste donatie maak je me al blij. 🙂\nDruk om te doneren of houd ingedrukt om te kopiëren",
        "down": "Downloaden",
        "downAgain":
            "is al gedownload.\nWil je dit bestand opnieuw downloaden?",
        "downDone": "Het downloaden is afgerond",
        "downFilename": "Bestandsnaamopmaak van download",
        "from": "van",
        "getLyricsOnline": "Songteksten van offline-nummers zoeken",
        "global": "Algemeen",
        "guest": "Gast",
        "genres": "Genres",
        "getStarted": "Aan de slag",
        "inc": "Oplopend",
        "includeExcludeFolder": "Mappen tonen/verbergen",
        "myMusic": "Mijn muziek",
        "pause": "Pauzeren",
        "loadLastSub":
            "Herstel automatisch de vorige sessie na het opstarten van de app",
        "minAudioLenSub":
            "Audio met een kortere duur wordt niet getoond in de sectie ‘Mijn muziek’",
        "notAvailable": "Niet beschikbaar",
        "no": "Nee",
        "play": "Afspelen",
        "playNext": "Volgende afspelen",
        "musicLangSub": "Om nummers te tonen op de startpagina",
        "musicLang": "Muziektaal",
        "noLangSelected":
            "Je hebt geen muziektaal ingesteld. Stel een taal in om nummers te tonen op de startpagina.",
        "size": "Grootte",
        "skipNext": "Volgende overslaan",
        "skipPrevious": "Vorige overslaan",
        "sleepAfterSub":
            "De muziek wordt onderbroken na het gekozen aantal nummers",
        "showHistory": "Zoekgeschiedenis tonen",
        "showLastSub": "Toon de vorige sessie op de startpagina",
        "skip": "Overslaan",
        "sleepAfter": "Slaapstand na x-aantal nummers",
        "streamQualitySub": "Hogere kwaliteit verbruikt meer mb's",
        "streamQuality": "Streamingkwaliteit",
        "successTagEdit": "De tags zijn bewerkt!",
        "supportEq": "Equalizer",
        "useProxySub":
            "Schakel in als je niet in India woont en problemen ervaart bij het zoeken, zoals geen resultaten, alleen Indiase nummers, etc. Je kunt tevens een vpn gebruiken.\n",
        "checkUpdateSub":
            "Als je BlackHole hebt gedownload uit een pakketbron, zoals F-Droid, IzzyOnDroid, etc., schakel deze optie dan NIET in. Als je BlackHole hebt gedownload van GitHub of een andere bron zonder automatische updates, schakel deze optie dan in om updatemeldingen te ontvangen.\n",
        "clearCacheSub":
            "Verwijder de cache van de startpagina, Spotify-hitlijsten, YouTube en vorige sessie. Normaliter doet de app dit automatisch als de cache-omvang te groot is geworden.\n",
        "getLyricsOnlineSub":
            "Zoek online naar songteksten als deze niet beschikbaar/gedownload zijn",
        "genre": "Genre",
        "gmail": "Gmail",
        "home": "Startpagina",
        "homeGreet": "Hallo,",
        "importFile": "Importeren uit bestand",
        "importPublicPlaylist": "Openbare afspeellijst importeren",
        "importResso": "Importeren uit Resso",
        "importSpotify": "Importeren uit Spotify",
        "importSuccess": "Het importeren is voltooid",
        "importYt": "Importeren van YouTube",
        "includeExcludeFolderSub":
            "Toon/Verberg de gekozen mappen in de sectie ‘Mijn muziek’",
        "included": "Tonen",
        "includedDetails":
            "Er worden alleen nummers uit de gekozen mappen getoond",
        "insta": "Instagram",
        "ipAdd": "IP-adres",
        "joinTg": "Praat met ons op Telegram",
        "joinTgSub": "Wil je bètaversies testen?",
        "lang": "Taal",
        "langQue": "In welke taal hoor je graag muziek?",
        "langSub": "Apptaal",
        "lastAdded": "Onlangs toegevoegd",
        "lastSession": "Vorige sessie",
        "lastModified": "Onlangs gewijzigd",
        "latest": "Gefeliciteerd! Je beschikt over de nieuwste versie. 🙂",
        "library": "Verzameling",
        "like": "Vind ik leuk",
        "likedWork": "Wat vind je van mijn app?",
        "live": "NU LIVE",
        "liveSearch": "Direct zoeken",
        "liveSearchSub":
            "Start een zoekopdracht zonder op enter te hoeven drukken",
        "loadLast": "Vorige sessie herstellen na opstarten",
        "local": "Lokaal",
        "lyrics": "Songtekst",
        "madeBy": "Met ♥ gemaakt door Ankit Sangwan",
        "minAudioAlert": "Min. audioduur (in sec.)",
        "minAudioLen": "De minimale audioduur waarnaar moet worden gezocht",
        "miniButtons": "Knoppen op minispeler",
        "miniButtonsSub":
            "Raak aan om de op de minispeler getoonde knoppen te wijzigen",
        "minutes": "minuten",
        "moreInfo": "Meer informatie",
        "musicPlayback": "Muziek en afspelen",
        "noFolderSelected": "Geen map gekozen",
        "nothingIs": "Er wordt niets ",
        "nothingPlaying": "Er wordt niets afgespeeld",
        "nothingTo": "Er valt hier niks te ",
        "ok": "Oké",
        "or": "OF",
        "others": "Overig",
        "playSomething": "Zet een nummer op",
        "playing": "Je luistert naar",
        "playingCap": "JE LUISTERT NAAR",
        "nowPlaying": "Aan het afspelen",
        "playlistShareText": "Bekijk mijn afspeellijst eens!",
        "playlists": "Afspeellijsten",
        "popularity": "Populariteit",
        "port": "Poort",
        "prefReq": "Heb je een momentje?",
        "proxySet": "Proxy-instellingen",
        "proxySetSub": "Proxy-ip-adres en -poort wijzigen",
        "rememberChoice": "Keuze onthouden",
        "remove": "Verwijderen",
        "removed": "Verwijderd",
        "removedFrom": "Verwijderd uit",
        "removedFromFav": "Verwijderd uit favorieten",
        "rename": "Naam wijzigen",
        "reset": "Standaardwaarden",
        "restore": "Herstellen",
        "restoreSub":
            "Herstel je gegevens uit een back-up.\nHerstart nadien de app.\n",
        "resultsNotFound": "Er zijn geen zoekresultaten",
        "savePlaylist": "Afspeellijst opslaan",
        "saveTheme": "Thema opslaan",
        "search": "Zoeken",
        "searchText": "Nummers, albums of artiesten",
        "searchVideo": "Video zoeken",
        "searchYt": "Zoeken op YouTube",
        "selectBackFile": "Kies een back-upbestand",
        "selectBackLocation": "Kies een back-uplocatie",
        "selectDownLocation": "Kies een downloadlocatie",
        "selectDur": "Kies een afspeelduur",
        "selectExportLocation": "Kies een exportlocatie",
        "selectJsonImport": "Kies een te importeren json-bestand",
        "settings": "Instellingen",
        "share": "Delen",
        "shareApp": "Deel de app",
        "shareAppSub": "Vertel je vrienden over deze app",
        "shareAppText": "Hé, probeer deze coole muziekapp eens!",
        "showHere": "Hier tonen",
        "searchHome": "Startpagina doorzoeken",
        "showHistorySub": "Toon zoekgeschiedenis onder de zoekbalk",
        "showLast": "Vorige sessie tonen",
        "showQr": "QR-code tonen",
        "shuffle": "Willekeurig",
        "sleepDur": "Slaapstand na uu:mm",
        "sleepDurSub": "De muziek wordt onderbroken na de ingestelde duur",
        "sleepTimer": "Slaapklok",
        "sleepTimerSetFor": "De slaapklok is ingesteld op",
        "song": "Nummer",
        "songInfo": "Nummerinformatie",
        "songPath": "Nummerlocatie",
        "songs": "Nummers",
        "sorry": "ONZE EXCUSES",
        "sponsor": "Word sponsor van dit project",
        "spotifyCharts": "Spotify-hitlijsten",
        "spotifyPublic": "Spotify-publiek",
        "spotifyTopCharts": "Spotify-hitlijst",
        "stopDown": "Downloaden afbreken",
        "stopOnClose": "Muziek onderbreken na afsluiten",
        "stopOnCloseSub":
            "Schakel uit om muziek te blijven luisteren als de app wordt afgesloten. Let op: deze optie is van toepassing op het volledig afsluiten van de app, dus niet op het minimaliseren. Muziek wordt sowieso altijd op de achtergrond afgespeeld als de app geminimaliseerd is.\n",
        "supportEqSub":
            "Schakel uit als je geen nummers kunt afspelen (zowel on- als offline)",
        "tg": "Telegram",
        "tgCh": "Telegramkanaal",
        "tgGp": "Telegramgroep",
        "theme": "Thema",
        "themeDeleted": "Het thema is verwijderd!",
        "themeSaved": "Het thema is opgeslagen!",
        "title": "Titel",
        "trendingSearch": "Populaire zoekopdrachten",
        "ui": "Vormgeving",
        "undo": "Ongedaan maken",
        "unknown": "Onbekend",
        "unlike": "Vind ik niet meer leuk",
        "update": "Updaten",
        "updateAvailable": "Er is een update beschikbaar!",
        "upiCopied": "De UPI-id is gekopieerd!",
        "upNext": "Hierna",
        "useAmoled": "Amoledthema gebruiken",
        "useDenseMini": "Compacte minispeler gebruiken",
        "useDenseMiniSub": "De hoogte van de minispeler wordt verlaagd",
        "useDominant": "Dominante kleur gebruiken op afspeelscherm",
        "useDominantSub":
            "De dominante kleur op de albumhoes wordt ingesteld als afspeelachtergrond. Schakel uit om de standaardachtergrond te gebruiken.",
        "useBlurForNowPlayingSub": "Achtergrond van afspeelscherm vervagen",
        "useDominantAndDarkerColorsSub":
            "De dominante kleur op de albumhoes wordt ingesteld als afspeelachtergrond, maar verduisterd. Deze optie is alleen beschikbaar als je de optie omtrent de dominante kleur hebt ingeschakeld.",
        "useDominantAndDarkerColors":
            "Dominante kleur gebruiken op afspeelscherm (verduisterd)",
        "useDominantFullScreen":
            "Dominante kleur gebruiken op het gehele afspeelscherm",
        "useDominantFullScreenSub":
            "De dominante kleur op de albumhoes wordt ingesteld op het gehele afspeelscherm. Deze optie is alleen beschikbaar als je de optie omtrent de dominante kleur hebt ingeschakeld.",
        "useDown": "Gedownloade nummers streamen (indien beschikbaar)",
        "useDownSub":
            "Als een nummer reeds is gedownload, dan wordt dat nummer afgespeeld in plaats van het online te streamen",
        "useHome": "Hoofdsectie gebruiken voor betere kwaliteit en downloads",
        "useProxy": "Proxy gebruiken",
        "useSystemTheme": "Systeemthema gebruiken",
        "useVpn":
            "Ben je niet woonachtig in India? Probeer dan een vpn met Indiase server!",
        "version": "Versie",
        "versionSub": "Raak aan om te controleren op updates",
        "viewAlbum": "Album bekijken",
        "viewArtist": "Artiest bekijken",
        "viewAll": "Alles bekijken",
        "watchVideo": "Video bekijken",
        "welcome": "Welkom",
        "willPlayNext": "wordt hierna afgespeeld",
        "year": "Jaar",
        "yes": "Ja",
        "yesReplace": "Ja, maar oude vervangen",
        "youTube": "YouTube",
        "ytDownQuality": "YouTube-downloadkwaliteit",
        "ytDownQualitySub": "Hogere kwaliteit neemt meer ruimte in beslag",
        "ytLiveAlert":
            "Deze video wordt gelivestreamd of er is een fout opgetreden. Wacht tot de livestream is afgelopen of probeer het opnieuw.",
        "ytStreamQuality": "YouTube-streamingkwaliteit",
        "ytStreamQualitySub": "Hogere kwaliteit verbruikt meer mb's",
        "autoBackLocation": "Automatische back-uplocatie",
        "yourPlaylists": "Mijn afspeellijsten",
        "showPlaylists": "Afspeellijsten tonen op startscherm",
        "playerScreenBackground": "Achtergrond van afspeelscherm",
        "playerScreenBackgroundSub":
            "De gekozen achtergrond wordt gebruikt op het afspeelscherm",
        "resetOnSkip": "Nummer herhalen in plaats van vorige nummer afspelen",
        "resetOnSkipSub":
            "Herhaal het huidige nummer in plaats van het vorige nummer af te spelen",
        "importJioSaavn": "Importeren uit JioSaavn",
        "topCharts": "Hitlijsten",
        "playRadio": "Beluisteren",
        "importPlaylist": "Afspeellijst importeren",
        "mergePlaylists": "Afspeellijsten samenvoegen",
        "top": "Top",
        "viral": "Viral",
        "openInSpotify": "Openen met Spotify",
        "signInSpotify": "Inloggen op Spotify",
        "shareLogs": "Logboeken delen",
        "shareLogsSub": "Deel de logboeken van de huidige sessies",
        "radio": "Radio",
        "cantFind": "Kun je niet vinden wat je zoekt? ",
        "showTopCharts": "Toplijsten tonen",
        "showTopChartsSub": "Toon Spotify-toplijsten op het startscherm",
        "mostPlayedSong": "Meest beluisterde nummer",
        "stats": "Statistieken",
        "songsPlayed": "Beluisterde nummers",
        "compactNotificationButtonsSub":
            "Te tonen knoppen in de compacte meldingsweergave",
        "compactNotificationButtons": "Compacte meldingsknoppen",
        "compactNotificationButtonsHeader": "Je kunt maximaal 3 knoppen kiezen",
      };
}
