class PT {
  static Map<String, String> get keys => {
        "aboard": "A bordo",
        "about": "Sobre",
        "aboutLine1":
            "Este projeto é de código aberto e pode ser encontrado em",
        "aboutLine2":
            "Se você gostou do meu trabalho\ndemonstre algum ♥ e ⭐ o repositório",
        "accent": "Cor de destaque & Matiz",
        "addNew": "Adicionar novo",
        "addSomething": "Escolha e Adicione algo",
        "addToPlaylist": "Adicionar à Playlist",
        "addToQueue": "Adicionar à Fila",
        "addedBy": "Adicionado por",
        "addedTo": "Adicionado a",
        "addedToFav": "Adicionado para os Favoritos",
        "addedToPlaylists": "Adicionado às Playlists",
        "addedToQueue": "Adicionado à Fila",
        "adjustSpeed": "Ajustar Velocidade",
        "album": "Álbum",
        "albumArtist": "Artista do álbum",
        "albums": "Álbuns",
        "alphabetical": "Ordem alfabética",
        "alreadyExists": "Já existe",
        "alreadyInQueue": "Já está na fila",
        "appTitle": "BlackHole",
        "artist": "Artista",
        "artists": "Artistas",
        "autoBack": "Backup automático",
        "autoBackSub": "Backup automático de dados",
        "autoplay": "Reprodução automática",
        "autoplaySub": "Adicionar músicas relacionadas à fila automaticamente",
        "back": "Voltar",
        "backNRest": "Backup e restaurar",
        "backupSuccess": "Backup completado",
        "bgGrad": "Gradiente do plano de fundo",
        "bgGradSub": "Gradiente usado como plano de fundo em todos os lugares",
        "blacklistedHomeSections": "Seções de casa na lista negra",
        "blacklistedHomeSectionsSub":
            "As seções com esses títulos não serão mostradas na tela inicial",
        "bottomGrad": "Gradiente do Painel",
        "bottomGradSub": "Gradiente usado nos Paineis",
        "buyCoffee": "Me compre um café",
        "cache": "Cache",
        "cacheSong": "Músicas em cachê",
        "cacheSongSub":
            "As músicas serão armazenadas em cache para reprodução futura. Espaço adicional no seu dispositivo será ocupado",
        "cancel": "Cancelar",
        "cantAddToQueue":
            "Não pode adicionar Músicas Online para a fila Offline",
        "canvasColor": "Cor de tela",
        "canvasColorSub": "Cor da tela de fundo",
        "cardColor": "Cor do Card",
        "cardColorSub": "Cor da Barra de Pesquisa, Diálogos de Alerta, Cards",
        "cardGrad": "Gradiente do Card",
        "cardGradSub": "Gradiente usado nos Cards",
        "changeDefault": "Predefinir",
        "changeOrder": "Pressione e segure para alterar o pedido\n",
        "chartLocation": "Localização dos gráficos locais do Spotify",
        "chartLocationSub": "País para Top Spotify Local Charts",
        "checkingUpdate": "Verificando atualizações…",
        "checkUpdate": "Checar automaticamente por atualizações",
        "checkUpdateSub":
            "Se você baixou BlackHole por qualquer repositório como 'F-Droid', 'IzzyOnDroid', etc que dispõe de checagem de atualizações, mantenha essa opção DESATIVADA. E se você baixou pelo 'GitHub' ou qualquer outro local em que não dispõe de atualizações automáticas deixe essa opção ATIVADA, para que possa receber alertas de atualização.\n",
        "clear": "Limpar",
        "clearAll": "Limpar Tudo",
        "clearCache": "Limpar informações salvas",
        "clearCacheSub":
            "Exclui informações salvas incluindo Página inicial, Spotify Top Charts, YouTube e informações da última sessão. Normalmente o aplicativo limpa automaticamente essas informações quando se tornam muito grandes.\n",
        "connectingRadio": "Conectando com o Rádio…",
        "contactUs": "Entre em contato conosco",
        "contactUsSub": "Comentários são apreciados!",
        "convertingSongs": "Convertendo as Músicas",
        "copied": "Copiado para a área de transferência!",
        "copy": "Copiar",
        "countryQue":
            "Para qual país você gostaria de ver os Spotify Local Charts?",
        "createAlbumFold":
            "Criar pasta para Album & Download da lista de reprodução",
        "createAlbumFoldSub":
            "Cria pasta comum para as Músicas quando Album ou Playlist é baixada",
        "createBack": "Criar Backup",
        "createBackSub": "Criar backup de seus dados",
        "createNewPlaylist": "Criar uma Nova Playlist",
        "createPlaylist": "Criar Playlist",
        "createYtFold": "Criar pastas diferentes para YouTube Downloads",
        "createYtFoldSub":
            "Cria uma pasta diferente para as Músicas baixadas pelo YouTube",
        "currentTheme": "Tema Atual",
        "darkMode": "Modo Escuro",
        "date": "Encontro",
        "dateAdded": "Data Adicionada",
        "dec": "Decrescente",
        "delete": "Apagar",
        "deleted": "Apagado",
        "deleteTheme": "Apagar Tema",
        "deleteThemeSubtitle": "Você tem certeza que quer apagar?",
        "disclaimer": "Isenção de Responsabilidade :",
        "disclaimerText":
            "Nós respeitamos sua privacidade mais que qualquer outra coisa. Apenas o seu nome, o qual você irá adicionar aqui, será salvo.",
        "displayName": "Nome em Exibição",
        "donateGpay": "Doar com GPay",
        "donateGpaySub":
            "Qualquer quantia me faz sorrir :)\nToque para doar ou clique e segure para copiar o ID da UPI",
        "down": "Download",
        "downAgain": "já existe.\nVocê quer baixar novamente?",
        "downDone": "Download Concluído",
        "downLocation": "Local de Download",
        "downLyrics": "Download de Letras",
        "downLyricsSub": "Baixar as letras junto com a música, se possível",
        "downQuality": "Qualidade do Download",
        "downQualitySub": "Qualidade alta usa mais espaço na memória",
        "downed": "foi baixada",
        "downingAlbum": "Baixando o Album",
        "downloadSomething": "Baixe algo",
        "downs": "Downloads",
        "duration": "Duração",
        "edit": "Editar",
        "enableGesture": "Habilitar Gestos de Arte",
        "enableGestureSub":
            "Permite tocar, soltar e deslizar na artwork da tela do player",
        "enforceRepeat": "Forçar repetição",
        "enforceRepeatSub":
            "Manter a mesma opção de repetição para cada sessão",
        "enterName": "Digite o seu nome",
        "enterPlaylistLink": "Coloque o link da Playlist",
        "enterSongsCount": "Digite o número de músicas",
        "enterText": "Digite o texto",
        "enterThemeName": "Coloque o nome do tema",
        "equalizer": "Equalizador",
        "exitConfirm": "Pressione novamente para sair do aplicativo",
        "export": "Exportar",
        "exported": "Exportado",
        "failedCreateBackup": "Falha ao criar o Backup",
        "failedDelete": "Falha ao deletar o arquivo",
        "failedExport": "Falha ao Exportar",
        "failedImport": "Falha ao Importar",
        "failedTagEdit": "Falha ao tentar editar as tags",
        "favorites": "Favoritos",
        "fetchingStream": "Buscando fluxo de áudio",
        "finish": "Terminado",
        "from": "de",
        "genre": "Gênero",
        "genres": "Gêneros",
        "getStarted": "Começar",
        "global": "Global",
        "gmail": "Gmail",
        "guest": "Hóspede",
        "home": "Inicio",
        "homeGreet": "Olá,",
        "importFile": "Importar de um arquivo",
        "importPublicPlaylist": "Importar uma Playlist pública",
        "importSpotify": "Importar do Spotify",
        "importSuccess": "Importado com sucesso",
        "importYt": "Importar do YouTube",
        "inc": "Crescente",
        "insta": "Instagram",
        "ipAdd": "Endereço de IP",
        "joinTg": "Junte-se a nós no Telegram",
        "joinTgSub": "Quer testar as versões Beta? Junte-se a nós!",
        "lang": "Linguagem",
        "langQue": "Em qual linguagem das músicas você gostaria de ouvir?",
        "langSub": "Linguagem dos textos do aplicativo",
        "lastAdded": "Adicionado por último",
        "lastModified": "Última modificação",
        "lastSession": "Última sessão",
        "latest": "Parabéns! Você está usando a última versão :)",
        "library": "Biblioteca",
        "like": "Gostar",
        "likedWork": "Gostou do meu trabalho?",
        "live": "AO VIVO AGORA",
        "liveSearch": "Pesquisa em tempo real",
        "liveSearchSub":
            "Pesquise músicas assim que o usuário parar de digitar",
        "loadLast": "Carregar última sessão quando o Aplicativo iniciar",
        "loadLastSub":
            "Automaticamente carregar última sessão quando o aplicativo iniciar",
        "local": "Local",
        "lyrics": "Letras",
        "madeBy": "Feito com ♥ por Ankit Sangwan",
        "minAudioAlert": "Mínimo tamanho dos audios (em segundos)",
        "minAudioLen": "Tamanho mínimo das Músicas",
        "minAudioLenSub":
            "Audios com tamanho menor não serão mostradas na sessão de 'Minhas Músicas'",
        "miniButtons": "Botões para mostrar no Mini Player",
        "miniButtonsSub":
            "Toque para alterar os botões mostrados no miniplayer",
        "minutes": "minutos",
        "moreInfo": "Mais informações",
        "musicLang": "Linguagem da música",
        "musicLangSub": "Para exibir músicas na tela inicial",
        "musicPlayback": "Músicas & Reprodução",
        "myMusic": "Minhas Músicas",
        "no": "Não",
        "noFolderSelected": "Nenhuma pasta selecionada",
        "noLangSelected":
            "Nenhuma linguagem de música selecionada. Selecione uma linguagem para ver músicas na Tela Inicial",
        "notAvailable": "Não disponível",
        "nothingIs": "Nada está ",
        "nothingPlaying": "Nada está tocando",
        "nothingTo": "Nada para ",
        "nowPlaying": "Tocando agora",
        "ok": "Ok",
        "or": "OU",
        "others": "Outros",
        "pause": "Pausar",
        "play": "Tocar",
        "playNext": "Tocar próximo",
        "playSomething": "Vá e Toque Algo",
        "playing": "Tocando",
        "playingCap": "TOCANDO",
        "playlistShareText": "Olhe minha Playlist!",
        "playlists": "Listas de reprodução (Playlists)",
        "popularity": "Popularidade",
        "port": "Porta",
        "prefReq": "Quer nos contar algo?",
        "proxySet": "Configurações de proxy",
        "proxySetSub": "Alterar IP e porta do proxy",
        "rememberChoice": "Lembrar minhas escolhas",
        "remove": "Remover",
        "removed": "Removido",
        "removedFrom": "Removido do",
        "removedFromFav": "Removido dos Favoritos",
        "rename": "Trocar o nome",
        "reset": "Redefinir",
        "restore": "Restaurar",
        "restoreSub":
            "Restaure suas informações usando um Backup.\nPode ser necessário reiniciar o aplicativo\n",
        "resultsNotFound": "Resultados não encontrados",
        "savePlaylist": "Salvar lista de reprodução",
        "saveTheme": "Salvar lista de reprodução",
        "search": "Procurar",
        "searchHome": "Página inicial da pesquisa",
        "searchText": "Músicas, albums ou artistas",
        "searchVideo": "Procurar Vídeo",
        "searchYt": "Procurar no YouTube",
        "selectBackFile": "Selecione o arquivo de Backup",
        "selectBackLocation": "Selecionar local de backup",
        "selectDownLocation": "Selecione o local de Download",
        "selectDur": "Selecione a Duração",
        "selectExportLocation": "Selecione o local de Exportação",
        "selectJsonImport": "Selecione um arquivo JSON para importar",
        "settings": "Configurações",
        "share": "Compartilhar",
        "shareApp": "Compartilhar o aplicativo",
        "shareAppSub": "Fale sobre nós para seus amigos",
        "shareAppText": "Ei! Confira esse incrível aplicativo de música",
        "showHere": "Mostrar aqui",
        "showHistory": "Mostrar histórico",
        "showHistorySub": "Mostrar histórico abaixo da barra de pesquisa",
        "showLast": "Mostrar última sessão",
        "showLastSub": "Mostrar última sessão na Tela Inicial",
        "showQr": "Mostrar QR Code",
        "shuffle": "Misturar",
        "size": "Tamanho",
        "skip": "Pular",
        "skipNext": "Pular",
        "skipPrevious": "Voltar",
        "sleepAfter": "Dormir depois de N Músicas",
        "sleepAfterSub":
            "Música irá parar depois de tocar as músicas selecionadas",
        "sleepDur": "Dormir depois de hh:mm",
        "sleepDurSub": "Música irá parar depois do tempo selecionado",
        "sleepTimer": "Despertador",
        "sleepTimerSetFor": "Despertador configurado para",
        "song": "Música",
        "songInfo": "Informações sobre a música",
        "songPath": "Caminho da música",
        "songs": "Músicas",
        "sorry": "DESCULPE",
        "sponsor": "Patrocine este projeto",
        "spotifyCharts": "Paradas do Spotify",
        "spotifyPublic": "Spotify Público",
        "spotifyTopCharts": "Top Charts do Spotify",
        "stopDown": "Parar Download",
        "stopOnClose": "Parar música quando o aplicativo for fechado",
        "stopOnCloseSub":
            "Se desativado, a música não irá parar mesmo depois que o aplicativo estiver 'fechado', até você clicar no botão de parar. Esta opção é para 'fechar' o aplicativo, não quando o aplicativo está em 'plano de fundo'. A música sempre tocará em segundo plano, você não precisa alterar nenhuma configuração para isso.\n",
        "streamQuality": "Qualidade do Streaming",
        "streamQualitySub": "Qualidades altas usam mais data",
        "successTagEdit": "Tags editadas com sucesso !",
        "supportEq": "Equalizador de suporte",
        "supportEqSub":
            "Desligue se você não conseguir reproduzir músicas (no modo online e offline)",
        "tg": "Telegram",
        "tgCh": "Canal do Telegram",
        "tgGp": "Grupo no Telegram",
        "theme": "Tema",
        "themeDeleted": "Tema apagado!",
        "themeSaved": "Tema salvo!",
        "title": "Título",
        "trendingSearch": "Tendências de pesquisa",
        "ui": "Interface do Aplicativo",
        "undo": "Desfazer",
        "unknown": "Desconhecido(a)",
        "unlike": "Diferente",
        "update": "Atualizar",
        "updateAvailable": "Atualização disponível!",
        "upiCopied": "UPI ID Copiado!",
        "useAmoled": "Use as configurações do modo escuro Amoled",
        "useDenseMini": "Usar miniplayer denso",
        "useDenseMiniSub": "A altura do miniplayer será reduzida",
        "useDominant": "Use a cor dominante para Play Screen",
        "useDominantSub":
            "A cor dominante da imagem será usada para o fundo da tela de reprodução. Se desligado, o gradiente de fundo padrão será usado",
        "useDown": "Transmitir músicas baixadas, se disponível",
        "useDownSub":
            "Se a música já estiver baixada a mesma será reproduzida em vez de streaming online",
        "useHome":
            "Use a seção principal para obter melhor qualidade e suporte para download",
        "useProxy": "Usar Proxy",
        "useProxySub":
            "Ative esta opção se você não for da Índia e estiver tendo problemas com pesquisa, encontrando apenas músicas indianas ou não obtendo nenhum resultado, etc. Você pode até usar VPN com servidor indiano\n",
        "useSystemTheme": "Usar o tema do sistema",
        "useVpn": "Não é da Índia? Tente usar VPN com servidor indiano",
        "version": "Versão",
        "versionSub": "Clique para verificar atualizações",
        "viewAlbum": "Ver álbum",
        "viewAll": "Ver tudo",
        "watchVideo": "Ver Vídeo",
        "welcome": "Bem Vindo",
        "willPlayNext": "vai tocar a seguir",
        "year": "Ano",
        "yes": "Sim",
        "yesReplace": "Sim, mas substitua o antigo",
        "youTube": "YouTube",
        "ytLiveAlert":
            "Video está ao vivo ou ocorreu algum erro. Por favor espere até o vídeo acabar ou tente novamente.",
        "useDominantFullScreen":
            "Usar a cor dominante para toda a tela do reprodução",
        "useDominantFullScreenSub":
            "A cor dominante da imagem será usada para o fundo da tela inteira do jogo. Disponível apenas se Usar dominante estiver ATIVADO",
        "favSongs": "Músicas favoritas",
        "viewArtist": "Ver Artista",
        "downFilename": "Formato de nome para download",
        "downFilenameSub":
            "As músicas serão baixadas de acordo com este formato de nome de arquivo",
        "excluded": "Excluídos",
        "excludedDetails": "Músicas das pastas selecionadas não serão exibidas",
        "includeExcludeFolder": "Incluir/Excluir pastas",
        "includeExcludeFolderSub":
            "Inclui/Exclui pastas selecionadas da seção «Minha música»",
        "included": "Incluído",
        "includedDetails":
            "Somente músicas das pastas selecionadas serão exibidas",
        "ytStreamQualitySub": "Qualidade superior usa mais dados",
        "importResso": "Importar do Resso",
        "ytDownQualitySub": "Maior qualidade necessita mais espaço no disco",
        "getLyricsOnlineSub":
            "Pesquisar online se as letras não estão disponíveis/descarregadas para qualquer música offline",
        "getLyricsOnline": "Pesquisar letras de canções locais",
        "ytDownQuality": "Qualidade de descarga do YouTube",
        "ytStreamQuality": "Qualidade de streaming do YouTube",
        "autoBackLocation": "Local de backup automático",
        "useBlurForNowPlayingSub":
            "Desfoque com uma opacidade mais baixa será usado como plano de fundo da seção de Tocando Agora",
        "useDominantAndDarkerColorsSub":
            "A cor dominante e mais escura da imagem será usada como gradiente do fundo da tela de reprodução. Somente disponível se Cores Dominantes estiver ativado (Melhores resultados se cores dominantes para a tela inteira estiver ativado)",
        "useDominantAndDarkerColors":
            "Usar cores dominantes e mais escuras na tela de reprodução",
        "showPlaylists": "Mostrar playlists na tela inicial",
        "confirmViewable": "Certifique-se que a playlist é visível",
        "yourPlaylists": "Suas Playlists",
        "upNext": "A Seguir",
        "playerScreenBackgroundSub":
            "O fundo selecionado será exibido na tela de reprodução",
        "playerScreenBackground": "Fundo da tela de reprodução",
        "importJioSaavn": "Importar de JioSaavn",
        "resetOnSkip": "Repetir ao pular anterior",
        "resetOnSkipSub":
            "Reproduzir desde o início ao invés de pular para a música anterior",
        "importPlaylist": "Importar Playlist",
        "mergePlaylists": "Mesclar Playlist",
        "playRadio": "Tocar Rádio",
        "top": "Topo",
        "viral": "Viral",
        "openInSpotify": "Abrir no Spotify",
        "signInSpotify": "Fazer login no Spotify",
        "topCharts": "Paradas",
        "cantFind": "Não encontrou o que procurava? ",
        "radio": "Rádio",
        "shareLogs": "Compartilhar Logs",
        "shareLogsSub": "Compartilhar logs da sessão atual",
      };
}
