class ID {
  static Map<String, String> get keys => {
        "aboard": "Luar Negeri",
        "about": "Tentang",
        "aboutLine1": "Ini adalah proyek sumber terbuka dan dapat ditemukan di",
        "aboutLine2":
            "Jika Anda menyukai pekerjaan saya\ntunjukkan beberapa ♥ dan ⭐ repo",
        "accent": "Warna Aksen & Rona",
        "addNew": "Tambah baru",
        "addSomething": "Pergi dan Tambahkan Sesuatu",
        "addToPlaylist": "Tambahkan ke Daftar Putar",
        "addToQueue": "Tambahkan ke Antrean",
        "addedBy": "Ditambahkan oleh",
        "addedTo": "Ditambahkan ke",
        "addedToFav": "Ditambahkan ke Favorit",
        "addedToPlaylists": "Ditambahkan ke Daftar Putar",
        "addedToQueue": "Ditambahkan ke Antrian",
        "adjustSpeed": "Sesuaikan Kecepatan",
        "album": "Album",
        "albumArtist": "Artis Album",
        "albums": "Album",
        "alphabetical": "Alfabetis",
        "alreadyExists": "Sudah ada",
        "alreadyInQueue": "Sudah di Antrian",
        "appTitle": "BlackHole",
        "artist": "Artis",
        "artists": "Artis",
        "autoBack": "Pencadangan Otomatis",
        "autoBackSub": "Cadangkan data secara otomatis",
        "autoplay": "Putar otomatis",
        "autoplaySub": "Secara otomatis menambahkan lagu terkait ke antrean",
        "back": "Kembali",
        "backNRest": "Cadangkan & Pulihkan",
        "backupSuccess": "Pencadangan Berhasil",
        "bgGrad": "Gradien Latar Belakang",
        "bgGradSub": "Gradien digunakan sebagai latar belakang di mana-mana",
        "blacklistedHomeSections": "Bagian Beranda yang Masuk Daftar Hitam",
        "blacklistedHomeSectionsSub":
            "Bagian dengan judul ini tidak akan ditampilkan di Layar Utama",
        "bottomGrad": "Gradien Lembar Bawah",
        "bottomGradSub": "Gradien yang digunakan di Lembar Bawah",
        "buyCoffee": "Belikan saya kopi",
        "cache": "Cache",
        "cacheSong": "Cache Lagu",
        "cacheSongSub":
            "Lagu akan di-cache untuk pemutaran yang akan datang. Ruang tambahan pada perangkat Anda akan digunakan",
        "cancel": "Batalkan",
        "cantAddToQueue":
            "Tidak dapat menambahkan Lagu Online ke Antrean Offline",
        "canvasColor": "Warna Kanvas",
        "canvasColorSub": "Warna Latar Belakang Kanvas",
        "cardColor": "Warna Kartu",
        "cardColorSub": "Warna Bilah Pencarian, Dialog Peringatan, Kartu",
        "cardGrad": "Gradien Kartu",
        "cardGradSub": "Gradien yang digunakan dalam Kartu",
        "changeDefault": "Ubah ke Default",
        "changeOrder": "Tekan lama untuk mengubah urutan\n",
        "chartLocation": "Lokasi Spotify Lokal Teratas",
        "chartLocationSub": "Negara untuk Charts Lagu Lokal Spotify Teratas",
        "checkingUpdate": "Memeriksa Pembaruan…",
        "checkUpdate": "Periksa Otomatis Pembaruan",
        "checkUpdateSub":
            "Jika Anda mengunduh BlackHole dari repositori aplikasi apa pun seperti 'F-Droid', 'IzzyOnDroid', dll yang menyediakan opsi pembaruan, MATIKAN ini. Sedangkan, Jika Anda mengunduhnya dari 'GitHub' atau sumber lain yang tidak menyediakan pembaruan otomatis, AKTIFKAN ini, untuk menerima peringatan pembaruan\n",
        "clear": "Bersihkan",
        "clearAll": "Bersihkan semua",
        "clearCache": "Hapus Detail Chache",
        "clearCacheSub":
            "Menghapus detail Cache termasuk Beranda, Lagu Teratas Spotify, YouTube, dan Data Sesi Terakhir. Biasanya aplikasi secara otomatis menghapusnya ketika data menjadi besar\n",
        "connectingRadio": "Menghubungkan ke Radio…",
        "contactUs": "Hubungi kami",
        "contactUsSub": "Umpan balik Anda dihargai!",
        "convertingSongs": "Mengonversi Lagu",
        "copied": "Disalin ke Papan Klip!",
        "copy": "Salin",
        "countryQue":
            "Untuk negara mana Anda ingin melihat Lagu Lokal Spotify Teratas?",
        "createAlbumFold": "Buat folder untuk Unduhan Album & Daftar Putar",
        "createAlbumFoldSub":
            "Membuat folder umum untuk Lagu saat Album atau Daftar Putar diunduh",
        "createBack": "Buat Cadangan",
        "createBackSub": "Buat cadangan data Anda",
        "createNewPlaylist": "Buat Daftar Putar Baru",
        "createPlaylist": "Buat Daftar Putar",
        "createYtFold": "Buat folder berbeda untuk Unduhan YouTube",
        "createYtFoldSub":
            "Membuat folder berbeda untuk Lagu yang diunduh dari YouTube",
        "currentTheme": "Tema Saat Ini",
        "darkMode": "Mode Gelap",
        "date": "Tanggal",
        "dateAdded": "Tanggal Ditambahkan",
        "dec": "menurun",
        "delete": "Menghapus",
        "deleted": "Dihapus",
        "deleteTheme": "Hapus Tema",
        "deleteThemeSubtitle": "Anda yakin ingin menghapus?",
        "disclaimer": "Penafian :",
        "disclaimerText":
            "Kami menghormati privasi Anda lebih dari apa pun. Hanya nama Anda, yang akan Anda masukkan di sini, yang akan dicatat.",
        "displayName": "Nama tampilan",
        "donateGpay": "Donasi dengan GPay",
        "donateGpaySub":
            "Bahkan sedikit membuatku tersenyum :)\nKetuk untuk menyumbang atau Tekan lama untuk menyalin ID UPI",
        "down": "Unduh",
        "downAgain": "sudah ada.\nApakah Anda ingin mengunduhnya lagi?",
        "downDone": "Pengunduhan Selesai",
        "downLocation": "Lokasi Unduhan",
        "downLyrics": "Unduh Lirik",
        "downLyricsSub": "Mengunduh lirik beserta lagu, jika tersedia",
        "downQuality": "Kualitas Unduhan",
        "downQualitySub":
            "Kualitas yang lebih tinggi menggunakan lebih banyak ruang penyimpanan",
        "downed": "telah diunduh",
        "downingAlbum": "Mengunduh Album",
        "downloadSomething": "Unduh Sesuatu",
        "downs": "Unduhan",
        "duration": "Durasi",
        "edit": "Sunting",
        "enableGesture": "Aktifkan Gerakan Karya Seni",
        "enableGestureSub":
            "Mengaktifkan tap, longpress, swipe, dll pada Artwork di Player Screen",
        "enforceRepeat": "Terapkan Pengulangan",
        "enforceRepeatSub":
            "Pertahankan opsi pengulangan yang sama untuk setiap sesi",
        "enterName": "Masukkan Nama Anda",
        "enterPlaylistLink": "Masukkan Tautan Daftar Putar",
        "enterSongsCount": "Masukkan jumlah Lagu",
        "enterText": "Masukkan teks",
        "enterThemeName": "Masukkan nama tema",
        "equalizer": "Ekualiser",
        "exitConfirm": "Tekan Kembali Lagi untuk Keluar dari Aplikasi",
        "export": "Ekspor",
        "exported": "Diekspor",
        "failedCreateBackup": "Gagal membuat Cadangan",
        "failedDelete": "Gagal Menghapus",
        "failedExport": "Gagal Mengekspor",
        "failedImport": "Gagal Mengimpor",
        "failedTagEdit": "Gagal mengedit tag",
        "favorites": "Favorit",
        "fetchingStream": "Mengambil Aliran Audio",
        "finish": "Menyelesaikan",
        "from": "dari",
        "genre": "Aliran",
        "genres": "Genre",
        "getStarted": "Memulai",
        "global": "Global",
        "gmail": "Gmail",
        "guest": "Tamu",
        "home": "Beranda",
        "homeGreet": "Halo,",
        "importFile": "Impor dari File",
        "importPublicPlaylist": "Impor Daftar Putar Publik",
        "importSpotify": "Impor dari Spotify",
        "importSuccess": "Berhasil diimpor",
        "importYt": "Impor dari YouTube",
        "inc": "meningkat",
        "insta": "Instagram",
        "ipAdd": "Alamat IP",
        "joinTg": "Bergabunglah dengan kami di Telegram",
        "joinTgSub":
            "Ingin Menguji versi beta? Bergabunglah Dengan Kami Sekarang!",
        "lang": "Bahasa",
        "langQue": "Lagu bahasa mana yang ingin Anda dengarkan?",
        "langSub": "Bahasa Teks Aplikasi",
        "lastAdded": "Terakhir Ditambahkan",
        "lastModified": "Terakhir diubah",
        "lastSession": "Sesi Terakhir",
        "latest": "Selamat! Anda menggunakan versi terbaru :)",
        "library": "Perpustakaan",
        "like": "Suka",
        "likedWork": "Suka pekerjaanku?",
        "live": "LIVE SEKARANG",
        "liveSearch": "Pencarian Langsung",
        "liveSearchSub": "Cari lagu segera setelah pengguna berhenti mengetik",
        "loadLast": "Muat Sesi Terakhir di Mulai Aplikasi",
        "loadLastSub":
            "Secara otomatis memuat sesi terakhir saat aplikasi dimulai",
        "local": "Lokal",
        "lyrics": "Lirik",
        "madeBy": "Dibuat dengan ♥ oleh Ankit Sangwan",
        "minAudioAlert": "Panjang Audio Min (dalam detik)",
        "minAudioLen": "Panjang Minimal Audio untuk mencari musik",
        "minAudioLenSub":
            "Audio dengan panjang lebih kecil dari ini tidak akan ditampilkan di Bagian 'Musik Saya'",
        "miniButtons": "Tombol untuk ditampilkan di Mini Player",
        "miniButtonsSub":
            "Ketuk untuk mengubah tombol yang ditampilkan di miniplayer",
        "minutes": "menit",
        "moreInfo": "Info lebih lanjut",
        "musicLang": "Bahasa Musik",
        "musicLangSub": "Untuk menampilkan lagu di Layar Utama",
        "musicPlayback": "Musik & Pemutaran",
        "myMusic": "Lagu Saya",
        "no": "Tidak",
        "noFolderSelected": "Tidak ada Folder yang dipilih",
        "noLangSelected":
            "Tidak ada bahasa Musik yang dipilih. Pilih bahasa untuk melihat lagu di Layar Utama",
        "notAvailable": "Tidak tersedia",
        "nothingIs": "Tidak ada yang ",
        "nothingPlaying": "Tidak Ada yang Dimainkan",
        "nothingTo": "Tidak ada ",
        "nowPlaying": "Sedang dimainkan",
        "ok": "Oke",
        "or": "ATAU",
        "others": "Lainnya",
        "pause": "Jeda",
        "play": "Putar",
        "playNext": "Putar Selanjutnya",
        "playSomething": "Pergi dan Mainkan Sesuatu",
        "playing": "Memutar",
        "playingCap": "MEMUTAR",
        "playlistShareText": "Lihat daftar putar saya!",
        "playlists": "Daftar putar",
        "popularity": "Popularitas",
        "port": "Port",
        "prefReq": "Keberatan memberi tahu kami beberapa hal?",
        "proxySet": "Pengaturan Proxy",
        "proxySetSub": "Ubah IP dan Port Proxy",
        "rememberChoice": "Ingat pilihan saya",
        "remove": "Hapus",
        "removed": "Dihapus",
        "removedFrom": "Dihapus dari",
        "removedFromFav": "Dihapus dari Favorit",
        "rename": "Ganti nama",
        "reset": "Atur Ulang",
        "restore": "Pulihkan",
        "restoreSub":
            "Pulihkan data Anda dari Cadangan.\nAnda mungkin perlu memulai ulang aplikasi\n",
        "resultsNotFound": "Hasil Tidak Ditemukan",
        "savePlaylist": "Simpan Daftar Putar",
        "saveTheme": "Simpan Tema",
        "search": "Cari",
        "searchHome": "Cari Beranda",
        "searchText": "Lagu, album, atau artis",
        "searchVideo": "Cari Video",
        "searchYt": "Cari di YouTube",
        "selectBackFile": "Pilih File Cadangan",
        "selectBackLocation": "Pilih Lokasi Cadangan",
        "selectDownLocation": "Pilih Lokasi Unduhan",
        "selectDur": "Pilih Durasi",
        "selectExportLocation": "Pilih Lokasi Ekspor",
        "selectJsonImport": "Pilih file JSON untuk diimpor",
        "settings": "Pengaturan",
        "share": "Bagikan",
        "shareApp": "Bagikan Aplikasi",
        "shareAppSub": "Beri tahu teman Anda tentang kami",
        "shareAppText": "Hai! Lihat aplikasi pemutar musik keren ini",
        "showHere": "Tampilkan Disini",
        "showHistory": "Tampilkan Riwayat Pencarian",
        "showHistorySub":
            "Tampilkan Riwayat Pencarian di bawah Bilah Pencarian",
        "showLast": "Tampilkan Sesi Terakhir",
        "showLastSub": "Tampilkan sesi Terakhir di Layar Beranda",
        "showQr": "Tampilkan Kode QR",
        "shuffle": "Acak",
        "size": "Ukuran",
        "skip": "Lewati",
        "skipNext": "Lewati Berikutnya",
        "skipPrevious": "Lewati Sebelumnya",
        "sleepAfter": "Tidur setelah N Lagu",
        "sleepAfterSub":
            "Musik akan berhenti setelah tidak ada lagu yang dipilih untuk diputar",
        "sleepDur": "Tidur setelah durasi jj:mm",
        "sleepDurSub": "Musik akan berhenti setelah durasi yang dipilih",
        "sleepTimer": "Pengatur Waktu Tidur",
        "sleepTimerSetFor": "Pengatur Waktu Tidur disetel untuk",
        "song": "Lagu",
        "songInfo": "Info Lagu",
        "songPath": "Lokasi Lagu",
        "songs": "Lagu",
        "sorry": "MAAF",
        "sponsor": "Sponsori proyek ini",
        "spotifyCharts": "Charts Lagu Spotify",
        "spotifyPublic": "Spotify Publik",
        "spotifyTopCharts": "Charts Lagu Teratas Spotify",
        "stopDown": "Hentikan Unduhan",
        "stopOnClose": "Hentikan musik saat aplikasi ditutup",
        "stopOnCloseSub":
            "Jika dimatikan, musik tidak akan berhenti bahkan setelah aplikasi 'ditutup', sampai Anda menekan tombol stop. Opsi ini untuk aplikasi 'tutup' bukan saat aplikasi berada di 'latar belakang'. Musik akan selalu diputar di latar belakang Anda tidak perlu mengubah pengaturan apa pun untuk itu.\n",
        "streamQuality": "Kualitas Streaming",
        "streamQualitySub":
            "Kualitas yang lebih tinggi menggunakan lebih banyak data",
        "successTagEdit": "Berhasil mengedit tag !",
        "supportEq": "Dukungan Ekualiser",
        "supportEqSub":
            "Matikan ini jika Anda tidak dapat memutar lagu (dalam mode online dan offline)",
        "tg": "Telegram",
        "tgCh": "Saluran Telegram",
        "tgGp": "Grup Telegram",
        "theme": "Tema",
        "themeDeleted": "Tema dihapus!",
        "themeSaved": "Tema disimpan!",
        "title": "Judul",
        "trendingSearch": "Pencarian Tren",
        "ui": "UI Aplikasi",
        "undo": "Batalkan",
        "unknown": "Tidak dikenal",
        "unlike": "Tidak seperti",
        "update": "Pembaruan",
        "updateAvailable": "Pembaruan tersedia!",
        "upiCopied": "ID UPI Disalin!",
        "useAmoled": "Gunakan Pengaturan Mode Gelap Amoled",
        "useDenseMini": "Gunakan miniplayer kompak",
        "useDenseMiniSub": "Tinggi miniplayer akan dikurangi",
        "useDominant": "Gunakan Warna Dominan untuk Layar Putar",
        "useDominantSub":
            "Warna Dominan dari Gambar akan digunakan untuk Play Screen Background. Jika dimatikan, Gradien latar belakang default akan digunakan",
        "useDown": "Streaming Lagu yang Diunduh, jika tersedia",
        "useDownSub":
            "Jika lagu sudah diunduh, lagu yang diunduh akan diputar alih-alih streaming online",
        "useHome":
            "Gunakan Bagian Utama untuk Kualitas Lebih Baik dan Dukungan Unduhan",
        "useProxy": "Gunakan proxy",
        "useProxySub":
            "Aktifkan ini jika Anda bukan dari India dan mengalami masalah dengan pencarian, seperti hanya mendapatkan Lagu India atau tidak mendapatkan hasil apa pun, dll. Anda bahkan dapat menggunakan VPN dengan Server India\n",
        "useSystemTheme": "Gunakan Tema Sistem",
        "useVpn": "Bukan dari India? Coba gunakan VPN dengan Server India",
        "version": "Versi",
        "versionSub": "Ketuk untuk memeriksa pembaruan",
        "viewAlbum": "Lihat album",
        "viewAll": "Lihat Semua",
        "watchVideo": "Tonton video",
        "welcome": "Selamat datang",
        "willPlayNext": "akan Memutar Selanjutnya",
        "year": "Tahun",
        "yes": "Ya",
        "yesReplace": "Ya, tapi timpa yang lama",
        "youTube": "YouTube",
        "ytLiveAlert":
            "Antara Video siaran langsung atau terjadi kesalahan. Harap tunggu hingga siaran langsung selesai atau coba lagi.",
        "favSongs": "Lagu favorit",
        "useDominantFullScreen":
            "Gunakan Warna Dominan untuk Seluruh Layar Putar",
        "useDominantFullScreenSub":
            "Warna Dominan dari Gambar akan digunakan untuk Seluruh Latar Layar Putar. Hanya tersedia jika Gunakan Dominan AKTIF",
        "viewArtist": "Lihat Artis",
        "excludedDetails":
            "Lagu dari folder yang terpilih tidak akan ditampilkan",
        "excluded": "Dikecualikan",
        "downFilename": "Format Nama Unduhan",
        "downFilenameSub":
            "Lagu akan diunduh sesuai dengan format nama file ini",
        "includeExcludeFolder": "Sertakan/Kecualikan Folder",
        "includeExcludeFolderSub":
            "Menyertakan/Mengecualikan folder yang dipilih dari Bagian “Musik Saya”",
        "included": "Termasuk",
        "includedDetails":
            "Hanya lagu dari folder yang dipilih yang akan ditampilkan",
        "ytDownQualitySub":
            "Kualitas yang lebih tinggi menggunakan lebih banyak ruang penyimpanan",
        "ytStreamQuality": "Kualitas Streaming YouTube",
        "ytDownQuality": "Kualitas Unduhan YouTube",
        "ytStreamQualitySub":
            "Kualitas yang lebih tinggi menggunakan lebih banyak data",
        "getLyricsOnlineSub":
            "Cari online jika lirik tidak tersedia/diunduh untuk semua lagu offline",
        "getLyricsOnline": "Cari lirik dari lagu lokal",
        "importResso": "Impor dari Resso",
        "useDominantAndDarkerColors":
            "Gunakan Warna Dominan dan Lebih Gelap untuk layar utama",
        "upNext": "Berikutnya",
        "importJioSaavn": "Import dari JioSaavn",
        "playerScreenBackground": "Latar Belakang Layar",
        "playerScreenBackgroundSub":
            "Latar belakang yang dipilih akan ditampilkan di Layar Putar",
        "resetOnSkip": "Ulangi pada Lewati sebelumnya",
        "resetOnSkipSub":
            "Putar ulang dari awal alih-alih melompat ke lagu sebelumnya",
        "useBlurForNowPlayingSub":
            "Blur dengan transparansi yang lebih rendah akan digunakan sebagai Latar Belakang bagian Sekarang Bermain",
        "yourPlaylists": "Daftar Putar Anda",
        "confirmViewable": "Pastikan playlist dapat dilihat",
        "showPlaylists": "Tampilkan Daftar Putar di Layar Utama",
        "autoBackLocation": "Lokasi Pencadangan Otomatis",
        "topCharts": "Tangga Lagu Teratas",
        "playRadio": "Mainkan Siaran",
        "importPlaylist": "Inpor Daftar Putar",
        "mergePlaylists": "Gabungkan Daftar Putar",
        "top": "Atas",
        "viral": "Viral",
        "signInSpotify": "Masuk ke Spotify",
        "openInSpotify": "Buka di Spotify",
        "shareLogs": "Bagi log",
        "shareLogsSub": "Bagi log sesi saat ini",
        "radio": "Radio",
        "cantFind": "Tidak bisa menemukan apa yang Anda cari? ",
      };
}
