class TR {
  static Map<String, String> get keys => {
        "aboard": "İçinde",
        "about": "Hakkında",
        "aboutLine1": "Bu açık kaynaklı bir projedir ve şu adreste bulunabilir",
        "aboutLine2": "Eğer çalışmamı beğendiysen\nbiraz ♥ göster ve depoyu⭐",
        "accent": "Vurgu Rengi ve Tonu",
        "addNew": "Yeni Ekle",
        "addSomething": "Git ve Bir Şey Ekle",
        "addToQueue": "Kuyruğa Ekle",
        "album": "Albüm",
        "albumArtist": "Albüm Sanatçısı",
        "albums": "Albümler",
        "artist": "Sanatçı",
        "addedToFav": "Favorilere eklendi",
        "artists": "Sanatçılar",
        "addedBy": "Tarafından eklendi",
        "addedTo": "Eklendi",
        "addedToQueue": "Kuyruğa Eklendi",
        "alphabetical": "Alfabetik",
        "alreadyInQueue": "Zaten Kuyrukta",
        "appTitle": "BlackHole",
        "autoBack": "Otomatik Yedekleme",
        "addToPlaylist": "Çalma listesine ekle",
        "addedToPlaylists": "Çalma Listelerine Eklendi",
        "adjustSpeed": "Hızı Ayarla",
        "alreadyExists": "Zaten Var",
        "autoBackSub": "Verileri otomatik olarak yedekle",
        "autoplay": "Otomatik yürütme",
        "autoplaySub": "İlgili şarkıları otomatik olarak kuyruğa ekle",
        "back": "Geri",
        "backNRest": "Yedekleme ve Geri Yükleme",
        "backupSuccess": "Yedekleme Başarılı",
        "bgGrad": "Arka Plan Gradyanı",
        "bgGradSub": "Her yerde arka plan olarak kullanılan gradyan",
        "blacklistedHomeSections": "Kara Listeye Alınmış Ana Sayfa Bölümleri",
        "blacklistedHomeSectionsSub":
            "Bu başlıklara sahip bölümler Ana Ekranda gösterilmeyecek",
        "bottomGrad": "Alt Sayfa Gradyanı",
        "bottomGradSub": "Alt sayfalarda kullanılan gradyan",
        "buyCoffee": "Bana bir kahve ısmarla",
        "cache": "Önbellek",
        "cacheSong": "Şarkıları önbellekle",
        "cardGradSub": "Kartlarda kullanılan gradyan",
        "cardGrad": "Kart Gradyanı",
        "cardColor": "Kart Rengi",
        "changeDefault": "Varsayılana Değiştir",
        "cacheSongSub":
            "Şarkılar ileride çalınmak üzere önbelleğe alınacaktır. Cihazınızda biraz daha yer kaplayacaktır",
        "cancel": "İptal et",
        "cantAddToQueue": "Çevrimiçi şarkı çevrimdışı kuyruğa eklenemiyor",
        "cardColorSub": "Arama çubuğunun, diyalogların, kartların rengi",
        "changeOrder": "Sırayı değiştirmek için uzun süre basın\n",
        "chartLocation": "Spotify Yerel Listeler Konumu",
        "chartLocationSub": "En İyi Spotify Yerel Listeleri için Ülke",
        "checkingUpdate": "Güncellemeler Denetleniyor…",
        "checkUpdate": "Güncellemeleri otomatik denetle",
        "countryQue":
            "Spotify Yerel Listelerini hangi ülke için görmek istersiniz?",
        "checkUpdateSub":
            "BlackHole'u güncelleme seçenekleri sunan 'F-Droid', 'IzzyOnDroid' gibi herhangi bir uygulama deposundan indirdiyseniz, bunu KAPALI tutun. Ancak, 'GitHub' veya otomatik güncelleme sağlamayan başka bir kaynaktan indirdiyseniz, güncelleme uyarıları almak için bunu AÇIK konuma getirin\n",
        "clearAll": "Hepsini temizle",
        "clear": "Temizle",
        "clearCache": "Önbelleğe Alınmış Ayrıntıları Temizle",
        "canvasColor": "Kanvas Rengi",
        "canvasColorSub": "Arka plan kanvasının rengi",
        "contactUs": "Bizimle iletişime geçin",
        "contactUsSub": "Geri bildirimler değerlidir!",
        "convertingSongs": "Şarkılar Dönüştürülüyor",
        "copied": "Panoya kopyalandı!",
        "copy": "Kopyala",
        "clearCacheSub":
            "Spotify Üst Sekmeler, YouTube ve Son Oturum verileri dahil önbelleğe alınmış ayrıntıları siler. Genellikle uygulama veriler büyük olunca otomatik bir şekilde siler\n",
        "connectingRadio": "Radyoya bağlanılıyor…",
        "createAlbumFold":
            "Albüm & Çalma Listesi indirmesi için bir klasör oluşturun",
        "createAlbumFoldSub":
            "Albüm veya Çalma Listesi indirildiğinde şarkılar için ortak klasör oluşturur",
        "createBack": "Yedek Oluştur",
        "createBackSub": "Verilerinizin yedeğini oluşturun",
        "createNewPlaylist": "Yeni Çalma Listesi Oluştur",
        "createPlaylist": "Çalma Listesi Oluştur",
        "createYtFold": "YouTube İndirmeleri için farklı klasör oluşturun",
        "createYtFoldSub":
            "YouTube'dan indirilen Şarkılar için farklı bir klasör oluşturur",
        "currentTheme": "Geçerli Tema",
        "darkMode": "Karanlık Mod",
        "date": "Tarih",
        "dateAdded": "Eklenme Tarihi",
        "dec": "Azalan",
        "delete": "Kaldır",
        "deleted": "Silindi",
        "deleteTheme": "Temayı Sil",
        "deleteThemeSubtitle": "Silmek istediğine emin misin?",
        "disclaimer": "Sorumluluk Reddi:",
        "disclaimerText":
            "Gizliliğinize her şeyden çok saygı duyuyoruz. Sadece buraya gireceğiniz adınız kaydedilecektir.",
        "displayName": "Görünen Ad",
        "donateGpay": "GPay ile bağış yapın",
        "downLyricsSub":
            "Eğer sözler varsa şarkı ile birlikte sözlerini indirir",
        "downQuality": "İndirme Kalitesi",
        "downQualitySub": "Daha yüksek kalite daha fazla disk alanı kullanır",
        "downs": "İndirilenler",
        "downed": "indirildi",
        "downingAlbum": "Albüm İndiriliyor",
        "downloadSomething": "Bir şey indir",
        "duration": "Süre",
        "edit": "Düzenle",
        "downFilenameSub": "Şarkılar bu dosya adı formatına göre indirilecek",
        "down": "İndir",
        "downAgain": "zaten var.\nTekrar indirmek istiyor musunuz?",
        "downDone": "İndirme Bitti",
        "downLocation": "İndirme Konumu",
        "donateGpaySub":
            "Her küçük miktar beni gülümsetiyor :)\nBağış yapmak için dokunun veya UPI kimliğini kopyalamak için uzun basın",
        "downLyrics": "Şarkı sözlerini indir",
        "excluded": "Dahil değil",
        "excludedDetails": "Seçili klasörlerdeki şarkılar gösterilmeyecek",
        "failedTagEdit": "Etiketler düzenlenemedi",
        "favorites": "Favoriler",
        "favSongs": "Favori şarkılar",
        "fetchingStream": "Ses akışı alınıyor",
        "finish": "Bitir",
        "genre": "Tür",
        "genres": "Türler",
        "getStarted": "Başlat",
        "global": "Dünya çapında",
        "gmail": "Gmail",
        "guest": "Misafir",
        "importSuccess": "Başarıyla içe aktarıldı",
        "importYt": "YouTube'dan içe aktar",
        "inc": "Artan",
        "includeExcludeFolder": "Klasörleri Dahil Et/Etme",
        "failedImport": "İçe aktarılamadı",
        "importSpotify": "Spotify'dan içe aktar",
        "homeGreet": "Merhaba,",
        "importFile": "Dosyadan içe aktar",
        "importPublicPlaylist": "Herkese açık çalma listesini içe aktar",
        "enforceRepeat": "Tekrarlamaya zorla",
        "enforceRepeatSub": "Her oturum için aynı tekrar seçeneğini koruyun",
        "enterName": "Adınızı Girin",
        "enterSongsCount": "Şarkıların sayısını girin",
        "enterText": "Metin girin",
        "enterPlaylistLink": "Çalma listesi bağlantısı girin",
        "enterThemeName": "Tema adını girin",
        "equalizer": "Ekolayzer",
        "exitConfirm": "Uygulamadan çıkmak için tekrar geri basın",
        "export": "Dışarı aktar",
        "exported": "Dışarı aktarıldı",
        "failedCreateBackup": "Yedek oluşturulamadı",
        "failedDelete": "Silinemedi",
        "failedExport": "Dışa aktarılamadı",
        "loadLastSub":
            "Uygulama başladığında otomatik olarak son oturumu yükle",
        "minutes": "dakika",
        "musicLang": "Müzik Dili",
        "myMusic": "Müziğim",
        "noFolderSelected": "Klasör seçilmedi",
        "notAvailable": "Mevcut değil",
        "included": "Dahil",
        "includedDetails":
            "Yalnızca seçili klasörlerdeki şarkılar gösterilecek",
        "insta": "Instagram",
        "ipAdd": "IP Adresi",
        "joinTg": "Telegram'da bize katılın",
        "lang": "Dil",
        "langQue": "Hangi dil şarkıları dinlemeyi tercih edersin?",
        "langSub": "Uygulama Metni Dili",
        "lastModified": "Son düzenleme",
        "lastAdded": "Son eklenen",
        "lastSession": "Son oturum",
        "library": "Kütüphane",
        "likedWork": "Çalışmamı beğendin mi?",
        "liveSearch": "Canlı Arama",
        "liveSearchSub": "Kullanıcı yazmayı bırakır bırakmaz şarkıları ara",
        "loadLast": "Uygulama başladığında son oturumu yükle",
        "local": "Yerel",
        "lyrics": "Şarkı sözleri",
        "madeBy": "Ankit Sangwan tarafından ♥ ile yapıldı",
        "minAudioAlert": "Asgari ses süresi (saniye)",
        "minAudioLen": "Müzik aramak için asgari ses uzunluğu",
        "miniButtons": "Küçük oynatıcıda gösterilecek tuşlar",
        "miniButtonsSub":
            "Küçük oynatıcıda gösterilen düğmeleri değiştirmek için dokunun",
        "moreInfo": "Daha fazla bilgi",
        "musicLangSub": "Ana Ekranda şarkıları görüntülemek için",
        "musicPlayback": "Müzik ve Oynatma",
        "includeExcludeFolderSub":
            "“Müziğim” bölümünden seçilen klasörleri dahil eder/etmez",
        "noLangSelected":
            "Müzik dili seçilmedi. Şarkıları ana ekranda görmek için bir dil seçin",
        "nothingPlaying": "Hiçbir şey çalmıyor",
        "joinTgSub":
            "Beta sürümlerini test etmek ister misiniz? Şimdi bize katılın!",
        "live": "ŞUAN CANLI",
        "latest": "Tebrikler! En son sürümü kullanıyorsun :)",
        "like": "Beğen",
        "enableGesture": "Çizim hareketlerini etkinleştir",
        "enableGestureSub":
            "Oynatıcı ekranındaki çizimde dokunma, uzun basma, kaydırma vb. etkinleştirir",
        "no": "Hayır",
        "showLastSub": "Ana ekranda son oturumu göster",
        "skip": "Geç",
        "spotifyPublic": "Spotify Herkese Açık",
        "spotifyCharts": "Spotify Sıralamaları",
        "streamQualitySub": "Daha yüksek kalite daha fazla veri kullanır",
        "theme": "Tema",
        "ok": "Tamam",
        "playingCap": "ÇALIYOR",
        "proxySet": "Vekil Sunucu Ayarları",
        "rememberChoice": "Seçimimi hatırla",
        "proxySetSub": "Proxy IP'sini ve bağlantı noktasını değiştirin",
        "tg": "Telegram",
        "tgGp": "Telegram grubu",
        "downFilename": "İndirme isim formatı",
        "home": "Ana Sayfa",
        "minAudioLenSub":
            "Bundan daha kısa uzunluktaki sesler 'Müziğim' bölümünde gösterilmeyecektir",
        "nothingIs": "Hiçbir şey ",
        "playing": "Çalıyor",
        "playlistShareText": "Çalma listeme bir bak!",
        "playlists": "Çalma Listeleri",
        "popularity": "Popülerlik",
        "port": "Port",
        "prefReq": "Bize birkaç şey söylemek ister misin?",
        "remove": "Kaldır",
        "removed": "Kaldırıldı",
        "removedFrom": "Kaldırıldığı yer",
        "removedFromFav": "Favorilerden kaldırıldı",
        "rename": "Yeniden adlandır",
        "restore": "Geri yükle",
        "restoreSub":
            "Verilerinizi yedeklemeden geri yükleyin.\nUygulamayı yeniden başlatmanız gerekebilir\n",
        "resultsNotFound": "Sonuçlar bulunamadı",
        "savePlaylist": "Çalma listesini kaydet",
        "saveTheme": "Temayı kaydet",
        "search": "Ara",
        "searchHome": "Ana Sayfada Ara",
        "searchVideo": "Video Ara",
        "searchYt": "Youtube'da ara",
        "selectBackFile": "Yedekleme dosyasını seçin",
        "selectBackLocation": "Yedekleme konumunu seçin",
        "selectDownLocation": "İndirme konumunu seçin",
        "selectDur": "Bir süre belirleyin",
        "selectJsonImport": "İçe aktarılacak JSON dosyasını seçin",
        "share": "Paylaş",
        "nothingTo": "hiçbir şey ",
        "shareAppText": "Hey! Bu harika müzik çalar uygulamasına göz at",
        "showQr": "QR kodunu göster",
        "shuffle": "Karıştır",
        "size": "Boyut",
        "skipNext": "Sonrakini geç",
        "skipPrevious": "Öncekini geç",
        "sleepAfter": "N şarkıdan sonra uyu",
        "sleepAfterSub": "Seçilen şarkı sayısı çalındıktan sonra müzik duracak",
        "sleepDur": "hh:mm süresinden sonra uyu",
        "sleepDurSub": "Belirlenen süreden sonra müzik duracak",
        "sleepTimer": "Uyku Zamanlayıcısı",
        "sleepTimerSetFor": "Uyku Zamanlayıcısı için ayarlandı",
        "song": "Şarkı",
        "songInfo": "Şarkı bilgisi",
        "songs": "Şarkılar",
        "sorry": "ÜZGÜNÜM",
        "sponsor": "Bu projeye sponsor olun",
        "spotifyTopCharts": "Spotify En İyiler Sıralaması",
        "stopDown": "İndirmeyi durdur",
        "stopOnClose": "Uygulama kapandığında müziği durdur",
        "streamQuality": "Yayın kalitesi",
        "successTagEdit": "Etiketler başarıyla düzenlendi!",
        "supportEqSub":
            "Şarkılar oynatılamıyorsa (hem çevrimiçi hem de çevrimdışı modda) bunu kapalı tutun",
        "tgCh": "Telegram kanalı",
        "unknown": "Bilinmeyen",
        "unlike": "Aksine",
        "update": "Güncelle",
        "updateAvailable": "Güncelleme mevcut!",
        "songPath": "Şarkının konumu",
        "supportEq": "Ekolayzır desteği",
        "useAmoled": "Amoled karanlık mod ayarlarını kullan",
        "useDenseMini": "Sıkışık küçük oynatıcıyı kullan",
        "useDenseMiniSub": "Küçük oynatıcı yüksekliği azaltılacak",
        "useDominant": "Oynatma ekranı için baskın renk kullan",
        "useDominantFullScreen": "Tüm oynatma ekranı için baskın rengi kullan",
        "useDominantFullScreenSub":
            "Görüntüdeki baskın renk tüm oynatıcı ekranın arka planı için kullanılacaktır. Yalnızca baskın kullanım açık ise kullanılabilir",
        "useDown": "Uygunsa indirilen şarkıları akışa ekle",
        "useHome":
            "Daha iyi kalite ve indirme desteği için ana bölümü kullanın",
        "useProxy": "Proxy kullan",
        "useSystemTheme": "Sistem temasını kullan",
        "useVpn":
            "Hindistan'dan değil misin? Hint sunucusu ile VPN kullanmayı deneyin",
        "version": "Sürüm",
        "versionSub": "Güncellemeleri denetlemek için dokunun",
        "youTube": "You Tube",
        "play": "Çal",
        "or": "VEYA",
        "others": "Diğerleri",
        "pause": "Duraklat",
        "playSomething": "Git ve bir şey çal",
        "searchText": "Şarkılar, albümler veya sanatçılar",
        "nowPlaying": "Şimdi çalıyor",
        "playNext": "Sonrakini çal",
        "shareAppSub": "Arkadaşlarınızın bizden haberdar olmasını sağlayın",
        "showHere": "Burada göster",
        "showLast": "Son oturumu göster",
        "shareApp": "Uygulamayı Paylaş",
        "reset": "Sıfırla",
        "selectExportLocation": "Dışa aktarma konumunu seçin",
        "settings": "Ayarlar",
        "showHistory": "Arama geçmişini göster",
        "showHistorySub": "Arama çubuğunun altında geçmişi göster",
        "upiCopied": "UPI kimliği kopyalandı!",
        "useDominantSub":
            "Görüntüdeki baskın renk, oynatma ekranı arka planı için kullanılacaktır. Eğer kapatılırsa, varsayılan arka plan gradyanı kullanılacaktır",
        "useDownSub":
            "Şarkı zaten indirilmişse, çevrimiçi akış yerine indirilen şarkı çalınır",
        "viewAlbum": "Albümü görüntüle",
        "useProxySub":
            "Hindistan'dan değilseniz ve aramada yalnızca Hint Şarkıları almak veya hiç sonuç alamamak gibi sorunlar yaşıyorsanız bunu açın. Hindistan Sunucusu ile VPN bile kullanabilirsiniz\n",
        "stopOnCloseSub":
            "Kapatılırsa, uygulama 'kapatıldıktan' sonra bile siz durdur düğmesine basana kadar müzik durmaz. Bu seçenek, uygulama 'arka planda' olduğunda değil, uygulamanın 'kapanması' içindir. Müzik her zaman arka planda çalacaktır, bunun için herhangi bir ayarı değiştirmenize gerek yoktur.\n",
        "themeDeleted": "Tema silindi!",
        "themeSaved": "Tema kaydedildi!",
        "title": "Başlık",
        "trendingSearch": "Trend Arama",
        "ui": "Uygulama arayüzü",
        "undo": "Geri al",
        "yes": "Evet",
        "ytLiveAlert":
            "Ya video yayında ya da bir hata oluştu. Lütfen canlı yayın bitene kadar bekleyin veya tekrar deneyin.",
        "viewArtist": "Sanatçıyı görüntüle",
        "viewAll": "Hepsini görüntüle",
        "watchVideo": "Video izle",
        "welcome": "Hoş geldin",
        "willPlayNext": "Sonraki oynayacak",
        "year": "Yıl",
        "yesReplace": "Evet ama eskisini değiştir",
        "ytDownQuality": "YouTube İndirme Kalitesi",
        "ytStreamQuality": "YouTube Akış Kalitesi",
        "ytStreamQualitySub": "Daha yüksek kalite daha fazla veri kullanır",
        "ytDownQualitySub": "Daha yüksek kalite daha fazla disk alanı kullanır",
        "getLyricsOnline": "Yerel şarkıların sözlerini ara",
        "getLyricsOnlineSub":
            "Herhangi bir çevrimdışı şarkı için şarkı sözleri mevcut değilse/indirilmediyse çevrimiçi arama yapın",
        "importResso": "Resso'dan içe aktar",
        "from": "form",
        "upNext": "Bir sonraki",
        "confirmViewable":
            "Çalma listesinin görüntülenebilir olduğundan emin olun",
        "useDominantAndDarkerColors":
            "Oynatma Ekranı için Baskın ve Daha Koyu Renkler Kullanın",
        "useDominantAndDarkerColorsSub":
            "Görüntüdeki Baskın ve Daha Koyu Renk, Oynatıcı Ekranı Arka Planının Gradyanı olarak kullanılacaktır. Yalnızca Baskın Kullanım AÇIK ise kullanılabilir (Dominantı Tüm Ekran için Kullan AÇIK ise daha iyi sonuçlar)",
        "useBlurForNowPlayingSub":
            "Daha düşük Opaklığa sahip Bulanıklık, Şu An Çalınan Bölümünün Arka Planı olarak kullanılacak",
        "autoBackLocation": "Otomatik Yedekleme Konumu",
        "yourPlaylists": "Çalma Listeleriniz",
        "showPlaylists": "Ana ekranda çalma listelerini göster",
        "resetOnSkip": "Öncekine Atlada Tekrar Oynat",
        "resetOnSkipSub": "Önceki şarkıya atlamak yerine baştan tekrar oynat",
        "playerScreenBackground": "Oynatıcı Ekranı Arka Planı",
        "playerScreenBackgroundSub":
            "Seçilen arka plan oynatıcı ekranında gösterilecektir",
        "importJioSaavn": "JioSaavn'dan içe aktar",
        "topCharts": "En İyiler",
        "playRadio": "Radyo çal",
        "importPlaylist": "Çalma Listesini İçe Aktar",
        "mergePlaylists": "Çalma Listelerini Birleştir",
        "top": "En iyi",
        "viral": "Viral",
        "openInSpotify": "Spotify'da aç",
        "signInSpotify": "Spotify'da oturum aç",
        "shareLogs": "Günlükleri Paylaş",
        "shareLogsSub": "Geçerli oturum günlüklerini paylaşın",
        "radio": "Radyo",
        "cantFind": "Aradığınızı bulamıyor musunuz? ",
      };
}
