class ES {
  static Map<String, String> get keys => {
        "about": "Acerca de",
        "aboutLine2": "Si te gusta mi trabajo\nMuestra ❤ y ⭐ el repositorio",
        "accent": "Color de acento y tono",
        "addNew": "Añadir nuevo",
        "addSomething": "Continuar y agregar algo",
        "addToQueue": "Añadir a la cola",
        "addedToFav": "Añadido a favoritos",
        "addedTo": "Añadido a",
        "addedBy": "Añadido por",
        "aboard": "A bordo",
        "addedToPlaylists": "Añadido a las Listas de reproducción",
        "addedToQueue": "Añadido a la Cola",
        "albums": "Álbumes",
        "bgGrad": "Degradado de fondo",
        "cacheSong": "Canciones en caché",
        "adjustSpeed": "Ajustar velocidad",
        "albumArtist": "Artista del álbum",
        "alphabetical": "Alfabético",
        "alreadyExists": "Ya existe",
        "alreadyInQueue": "Ya en la cola",
        "appTitle": "BlackHole",
        "artist": "Artista",
        "autoBack": "Copia de seguridad automática",
        "autoBackSub": "Copia de seguridad automática de los datos",
        "autoplay": "Reproducción automática",
        "autoplaySub":
            "Agregar canciones relacionadas automáticamente a la Cola",
        "back": "Atrás",
        "backNRest": "Copia de seguridad",
        "backupSuccess": "Copia de seguridad realizada",
        "bgGradSub": "Usar degradado como fondo en todas partes",
        "blacklistedHomeSections": "Secciones de Inicio en lista negra",
        "blacklistedHomeSectionsSub":
            "Las secciones con estos títulos no se mostrarán en la Pantalla de Inicio",
        "bottomGrad": "Degradado inferior",
        "buyCoffee": "Cómprame un café",
        "cache": "Caché",
        "cantAddToQueue":
            "Imposible añadir canción a una Lista de Reproducción sin conexión",
        "canvasColor": "Color del lienzo",
        "canvasColorSub": "Color de fondo del lienzo",
        "cardColor": "Color de la tarjeta",
        "cardColorSub":
            "Color de Barra de búsqueda, Diálogos de alerta, Tarjetas",
        "cardGrad": "Degradado de la Tarjeta",
        "cardGradSub": "Degradado empleado en las tarjetas",
        "changeDefault": "Cambiar a por defecto",
        "changeOrder": "Mantener presionado para cambiar el orden\n",
        "chartLocation": "Región de éxitos de Spotify",
        "chartLocationSub": "País para los éxitos de Spotify",
        "checkUpdate": "Comprobar actualizaciones automáticamente",
        "clear": "Limpiar",
        "clearAll": "Limpiar todo",
        "clearCache": "Limpiar los datos en Caché",
        "clearCacheSub":
            "Eliminar datos en Caché, como Página de Inicio, Rankings de Spotify, YouTube y datos de la última sesión. Se limpian automáticamente cuando son muchos\n",
        "connectingRadio": "Conectando a la Radio…",
        "convertingSongs": "Convirtiendo canciones",
        "copy": "Copiar",
        "countryQue":
            "¿Para que país desea mostrar los éxitos locales de Spotify?",
        "createAlbumFold":
            "Crear carpeta para descarga de Álbum y Lista de reproducción",
        "createBack": "Crear Copia de Seguridad",
        "createBackSub": "Crear Copia de Seguridad de sus datos",
        "createNewPlaylist": "Crear nueva Lista de Reproducción",
        "createPlaylist": "Crear Lista de Reproducción",
        "createYtFoldSub":
            "Crear una carpeta diferente para las canciones descargadas desde YouTube",
        "currentTheme": "Tema actual",
        "dateAdded": "Fecha añadida",
        "delete": "Eliminar",
        "deleted": "Eliminado",
        "deleteThemeSubtitle": "¿Segur@ que deseas eliminar?",
        "disclaimerText":
            "Respetamos su privacidad más que nada. Solo su nombre, el cual introducirá aquí, será guardado.",
        "displayName": "Nombre",
        "donateGpay": "Donar con GPay",
        "donateGpaySub":
            "Cualquier cantidad me hace sonreír :)\nToqua para donar o mantenga pulsado para copiar el ID de UPI",
        "downDone": "Descarga completada",
        "downLocation": "Destino de descarga",
        "edit": "Editar",
        "downQuality": "Calidad de descarga",
        "downs": "Descargas",
        "enterSongsCount": "Introduzca el número de canciones",
        "enterThemeName": "Escriba el nombre del Tema",
        "downQualitySub": "Mayor calidad usa más espacio en disco",
        "downed": "ha sido descargado",
        "downloadSomething": "Descargue algo",
        "duration": "Duración",
        "enforceRepeat": "Forzar repetición",
        "enforceRepeatSub":
            "Mantener la misma opción de repetir para cada sesión",
        "enterPlaylistLink": "Enlace de Lista de Reproducción",
        "export": "Exportar",
        "failedCreateBackup": "Falló la creación de la Copia de Seguridad",
        "failedExport": "Fallo al exportar",
        "exitConfirm": "Presione atrás nuevamente para salir de la aplicación",
        "favorites": "Favoritos",
        "fetchingStream": "Obteniendo audio en línea",
        "finish": "Terminar",
        "from": "de",
        "genre": "Género",
        "home": "Inicio",
        "importFile": "Importar desde archivo",
        "importPublicPlaylist": "Importar Lista de Reproducción pública",
        "aboutLine1":
            "Este es un proyecto de código abierto y puede ser encontrado en",
        "useProxy": "Usar proxy",
        "useSystemTheme": "Usar el Tema del sistema",
        "year": "Año",
        "yes": "Sí",
        "yesReplace": "Sí, sobreescribir",
        "youTube": "Youtube",
        "addToPlaylist": "Añadir a la Lista de reproducción",
        "album": "Álbum",
        "artists": "Artistas",
        "cacheSongSub":
            "Las canciones serán almacenadas en caché para su futura reproducción. Se empleará espacio adicional en el dispositivo",
        "cancel": "Cancelar",
        "bottomGradSub": "Degradado usado en la región inferior",
        "exported": "Exportado",
        "failedTagEdit": "Fallo al editar las etiquetas",
        "checkingUpdate": "Comprobando actualizaciones…",
        "checkUpdateSub":
            "Si descargó BlackHole desde algún repositorio de aplicaciones, como 'F-Droid', 'IzzyOnDroid', etc, los cuales proveen actualizaciones, mantenga esto desactivado. Por el contrario, si lo descargó desde 'GitHub' o alguna otra fuente que no ofrece actualizaciones automáticas, active esta opción para recibir alertas de actualizaciones\n",
        "contactUs": "Contáctanos",
        "createAlbumFoldSub":
            "Crear una carpeta común para las canciones cuando se descarguen Álbumes o Listas de Reproducción",
        "date": "Fecha",
        "deleteTheme": "Eliminar el tema",
        "contactUsSub": "¡Comentarios bienvenidos!",
        "copied": "¡Copiado al portapapeles!",
        "darkMode": "Modo oscuro",
        "createYtFold": "Crear carpetas diferentes para descargas de YouTube",
        "failedImport": "Fallo al importar",
        "enterText": "Escriba",
        "equalizer": "Ecualizador",
        "global": "Global",
        "down": "Descargar",
        "downAgain": "ya existe.\n¿Desea descargarlo nuevamente?",
        "downLyrics": "Descargar letras",
        "homeGreet": "Hola,",
        "getStarted": "Comenzar",
        "gmail": "Gmail",
        "guest": "Invitado",
        "genres": "Géneros",
        "failedDelete": "Fallo al eliminar",
        "useProxySub":
            "Activa está opción si no está en la India y tiene problemas con la búsqueda, como solo canciones indias o ningún resultado. Puede incluso usar una VPN con un servidor indio\n",
        "downingAlbum": "Descargando el álbum",
        "enterName": "Entre su nombre",
        "ytLiveAlert":
            "Este video se está transmitiendo en vivo o se produjo un error. Espere a que finalice la transmisión en vivo o vuelva a intentarlo.",
        "dec": "Descendente",
        "downLyricsSub":
            "Descargar las letras junto a la canción si están disponibles",
        "enableGesture": "Habilitar gestos en la Imagen",
        "viewAll": "Ver todo",
        "willPlayNext": "se reproducirá a continuación",
        "watchVideo": "Abrir el vídeo",
        "welcome": "Bienvenid@",
        "version": "Versión",
        "viewAlbum": "Ver álbum",
        "disclaimer": "Cláusula de no responsabilidad:",
        "enableGestureSub":
            "Habilitar gestos como presionar, pulsación prolongada, deslizar, etc en la portada del álbum en la vista del reproductor",
        "langSub": "Lenguaje de la aplicación",
        "importSuccess": "Importado satisfactoriamente",
        "inc": "Ascendente",
        "insta": "Instagram",
        "joinTgSub": "¿Quieres probar versiones beta? ¡Únete ahora!",
        "lang": "Idioma",
        "lastAdded": "Añadido recientemente",
        "lastModified": "Última modificación",
        "likedWork": "¿Le gusta mi trabajo?",
        "live": "EN VIVO",
        "liveSearchSub": "Buscar canciones mientras se escribe",
        "loadLast": "Restaurar última sesión al iniciar la aplicación",
        "loadLastSub":
            "Restaurar automáticamente la última sesión cuando la aplicación se inicia",
        "local": "Local",
        "lyrics": "Letras",
        "madeBy": "Hecho con ❤ por Ankit Sangwan",
        "minAudioAlert": "Longitud mínima de audio (en segundos)",
        "minAudioLen": "Longitud de audio mínima para incluir musica",
        "minAudioLenSub":
            "Audio con una duración más corta no será mostrado en la sección 'Mi Música'",
        "minutes": "minutos",
        "moreInfo": "Información",
        "musicLang": "Idioma de la Música",
        "musicLangSub": "Para mostrar canciones en la Vista de Inicio",
        "musicPlayback": "Música y Reproducción",
        "myMusic": "Mi Música",
        "noFolderSelected": "Ningún directorio seleccionado",
        "notAvailable": "No disponible",
        "miniButtonsSub":
            "Presiona para cambiar los botones mostrados en el Mini Reproductor",
        "favSongs": "Canciones Favoritas",
        "importSpotify": "Importar desde Spotify",
        "importYt": "Importar desde YouTube",
        "ipAdd": "Dirección IP",
        "joinTg": "Únete en Telegram",
        "langQue": "¿En qué idioma prefiere escuchar las canciones?",
        "lastSession": "Última sesión",
        "latest": "Está usando la última versión :)",
        "library": "Biblioteca",
        "like": "Me gusta",
        "liveSearch": "Búsqueda en vivo",
        "miniButtons": "Botones a mostrar en el Mini Reproductor",
        "no": "No",
        "noLangSelected":
            "No seleccionó un idioma de música. Seleccione un idioma para ver canciones en la Vista de Inicio",
        "playing": "Reproduciendo",
        "playingCap": "REPRODUCIENDO",
        "reset": "Reiniciar",
        "saveTheme": "Guardar Tema",
        "sleepAfterSub":
            "La música se detendrá después de reproducir N canciones",
        "songInfo": "Info de canción",
        "stopOnClose": "Detener música al cerrar App",
        "tg": "Telegram",
        "useDominant": "Usar color dominante para la Pantalla de reproducción",
        "useDown": "Reproducir música descargada, si está disponible",
        "ok": "Ok",
        "shareAppSub": "Comparte esta app con tus amigos",
        "downFilenameSub":
            "Las canciones serán descargadas de acuerdo a este formato de nombre de archivo",
        "excluded": "Excluidos",
        "excludedDetails":
            "Las canciones de los directorios seleccionados no se mostrarán",
        "included": "Incluido",
        "includedDetails":
            "Solo se mostrarán las canciones de los directorios seleccionados",
        "nothingIs": "Nada está ",
        "nothingPlaying": "No reproduciendo nada",
        "nothingTo": "Nada que ",
        "nowPlaying": "Reproduciendo",
        "or": "O",
        "others": "Otros",
        "play": "Reproducir",
        "playNext": "Escuchar a continuación",
        "playSomething": "Ir y escuchar algo",
        "playlistShareText": "¡Mira mi lista de reproducción!",
        "playlists": "Listas de reproducción",
        "prefReq": "¿Quieres decirnos alguna cosa?",
        "proxySet": "Configuración del Proxy",
        "proxySetSub": "Cambiar IP y Puerto de Proxy",
        "rememberChoice": "Recordar elección",
        "remove": "Eliminar",
        "removed": "Eliminado",
        "removedFromFav": "Eliminado de Favoritos",
        "rename": "Renombrar",
        "restore": "Restaurar",
        "resultsNotFound": "No hay resultados",
        "savePlaylist": "Guardar Playlist",
        "search": "Buscar",
        "searchHome": "Buscar en Inicio",
        "searchText": "Canciones, álbumes o artistas",
        "searchVideo": "Buscar Vídeo",
        "searchYt": "Buscar en YouTube",
        "selectBackFile": "Selecciona archivo de Backup",
        "selectBackLocation": "Selecciona ubicación de Backup",
        "selectDownLocation": "Selecciona ubicación de descarga",
        "selectDur": "Escoger duración",
        "selectExportLocation": "Selecciona ubicación para exportar",
        "share": "Compartir",
        "shareApp": "Compartir App",
        "showHere": "Mostrar aquí",
        "showHistory": "Mostrar historial de búsqueda",
        "showHistorySub": "Mostrar historial debajo de la barra de búsqueda",
        "showLast": "Mostrar última sesión",
        "showLastSub": "Mostrar última sesión en la pantalla de inicio",
        "showQr": "Mostrar código QR",
        "size": "Tamaño",
        "skip": "Saltar",
        "skipNext": "Siguiente canción",
        "skipPrevious": "Canción anterior",
        "sleepDur": "Dormir después de una duración de hh:mm",
        "sleepDurSub":
            "La música se detendrá cuando pase el tiempo seleccionado",
        "sleepTimerSetFor": "Temporizador de sueño fijado para",
        "songPath": "Ruta de la canción",
        "songs": "Canciones",
        "sorry": "LO SIENTO",
        "sponsor": "Patrocina este proyecto",
        "spotifyCharts": "Tops de Spotify",
        "spotifyPublic": "Spotify público",
        "spotifyTopCharts": "Top éxitos de Spotify",
        "stopDown": "Parar descarga",
        "streamQuality": "Calidad de reproducción",
        "streamQualitySub": "Más calidad consume más datos",
        "supportEq": "Usar Equalizador",
        "tgCh": "Canal de Telegram",
        "tgGp": "Grupo de Telegram",
        "theme": "Tema",
        "themeDeleted": "¡Tema eliminado!",
        "themeSaved": "¡Tema guardado!",
        "title": "Título",
        "trendingSearch": "Buscar tendencias",
        "ui": "Interfaz",
        "undo": "Deshacer",
        "unknown": "Desconocido",
        "unlike": "No me gusta",
        "update": "Actualizar",
        "upiCopied": "¡ID UPI Copiada!",
        "useAmoled": "Usar el Modo Oscuro para Amoled",
        "useDenseMini": "Usar minireproductor compacto",
        "useDenseMiniSub": "Disminuye la altura del Minireproductor",
        "useDominantFullScreen":
            "Usar color dominante para toda la pantalla de reproducción",
        "useDominantFullScreenSub":
            "El color dominante de la imagen será usado para el fondo de toda la pantalla de reproducción. Solo disponible si está activado Usar color dominante",
        "useDownSub":
            "Reproducir la copia local de las canciones en vez de la versión en línea",
        "useHome":
            "Usar sección principal para mejor calidad y soporte de descargas",
        "versionSub": "Toca para comprobar actualizaciones",
        "shuffle": "Aleatorio",
        "downFilename": "Formato de nombre de descargas",
        "includeExcludeFolder": "Incluir/Excluir directorios",
        "includeExcludeFolderSub":
            "Incluye/Excluye los directorios seleccionados de la sección 'Mi música'",
        "removedFrom": "Eliminado de",
        "pause": "Pause",
        "popularity": "Popularidad",
        "settings": "Ajustes",
        "sleepTimer": "Temporizador de sueño",
        "song": "Canción",
        "useDominantSub":
            "El color dominante de la imagen será usado para el fondo de la pantalla de reproducción. Sí está desactivado, de usará el fondo degradado por defecto",
        "shareAppText": "¡Hola! Mira este reproductor de música",
        "port": "Puerto",
        "selectJsonImport": "Selecciona archivo JSON a importar",
        "stopOnCloseSub":
            "Si se desactiva, la música no se detendrá al cerrar la aplicación, hasta que presiones el botón de detener. La música se reproduce en segundo plano, esta configuración es para cuando se cierra la applicación.\n",
        "restoreSub":
            "Restaura tus datos desde un Backup.\nPuede que necesites reiniciar la app\n",
        "sleepAfter": "Dormir después de N canciones",
        "successTagEdit": "¡Etiquetas editadas con éxito!",
        "supportEqSub":
            "Desactivar si no se reproduce música (tanto en línea cómo sin conexión)",
        "updateAvailable": "¡Actualización disponible!",
        "useVpn":
            "¿No está en la India? Intente usar una VPN con un servidor en la India",
        "viewArtist": "Ver artista",
        "confirmViewable":
            "Asegúrese de que la lista de reproducción es visible",
        "playerScreenBackgroundSub":
            "El color seleccionado se mostrará como fondo del reproductor",
        "importPlaylist": "Importar lista de reproducción",
        "importResso": "Importar desde Resso",
        "mergePlaylists": "Combinar listas de reproducción",
        "playerScreenBackground": "Color de fondo del reporoductor",
        "playRadio": "Radio",
        "importJioSaavn": "Importar desde JioSaavn",
        "useBlurForNowPlayingSub":
            "Se usará menor opacidad para el fondo de la sección Reproduciendo Ahora",
        "topCharts": "Listas de Éxitos",
        "ytStreamQualitySub": "Más calidad usa más datos",
        "ytStreamQuality": "Calidad de reprocucción de YouTube",
        "resetOnSkip": "Botón anterior reinicia canción",
        "resetOnSkipSub":
            "Ir al comienzo de la canción en vez de saltar a la anterior",
        "ytDownQualitySub": "Mayor calidad usa más espacio de almacenamiento",
        "getLyricsOnline": "Buscar letras de canciones locales",
        "autoBackLocation": "Ubicación de la copia de seguridad",
        "getLyricsOnlineSub":
            "Buscar letras en línea si las canciones descargadas no traen letras",
        "showPlaylists":
            "Mostrar listas de reproducción en la pantalla de inicio",
        "top": "Éxitos",
        "viral": "Popular",
        "yourPlaylists": "Tus Listas de Reproducción",
        "ytDownQuality": "Calidad de descarga de YouTube",
        "upNext": "Cola de reproducción",
        "openInSpotify": "Abrir en Spotify",
        "signInSpotify": "Inicia sesión en Spotify",
        "shareLogs": "Compartir los registros",
        "shareLogsSub": "Compartir los registros de las sesiones actuales",
        "radio": "Radio",
        "cantFind": "¿No encuentra lo que busca? ",
        "showTopChartsSub":
            "Mostrar las listas principales de Spotify en la pantalla de inicio",
        "showTopCharts": "Mostrar gráficos principales",
        "mostPlayedSong": "Canción más reproducida",
        "songsPlayed": "Canciones reproducidas",
        "stats": "Estadísticas",
        "compactNotificationButtons": "Botones de notificación compactos",
        "compactNotificationButtonsSub":
            "Botones para mostrar en la vista compacta de notificaciones",
        "compactNotificationButtonsHeader": "Puedes elegir hasta 3 botones",
      };
}
