class JA {
  static Map<String, String> get keys => {
        "addedToQueue": "キューに追加しました",
        "downs": "ダウンロード",
        "adjustSpeed": "速度を調整する",
        "album": "アルバム",
        "autoBackSub": "データの自動バックアップ",
        "autoplaySub": "関連する曲をキューに自動で追加",
        "backupSuccess": "バックアップ成功",
        "createNewPlaylist": "新規プレイリスト作成",
        "down": "ダウンロード",
        "enterName": "名前を入力",
        "failedCreateBackup": "バックアップの作成に失敗",
        "aboard": "歓迎します",
        "about": "情報",
        "aboutLine1": "このアプリはオープンソースでプロジェクトはここにあります",
        "aboutLine2": "私の仕事を良いと思ったら\nあなたの ♥ とリポジトリに⭐をつけてください",
        "accent": "アクセントカラー & 色相",
        "addNew": "新規",
        "addToPlaylist": "プレイリストに追加",
        "addToQueue": "キューに追加",
        "addedBy": "…から追加",
        "addedTo": "以下に追加しました",
        "albums": "アルバム",
        "alphabetical": "アルファベット順",
        "alreadyExists": "既に存在",
        "alreadyInQueue": "既にキューに存在",
        "bgGrad": "背景グラデーション",
        "blacklistedHomeSections": "ブラックリストに登録されたホームセクション",
        "blacklistedHomeSectionsSub": "このようなタイトルが含まれるセクションはホームスクリーンに表示されません",
        "bottomGrad": "下部シートのグラデーション",
        "bottomGradSub": "下部シートに使われるグラデーション",
        "buyCoffee": "コーヒーを買ってください",
        "cache": "キャッシュ",
        "cacheSong": "曲をキャッシュ",
        "cancel": "キャンセル",
        "cacheSongSub": "曲は将来の再生のためにキャッシュされます。端末の空き領域を使います",
        "cantAddToQueue": "オフラインのキューにオンラインの曲を追加できません",
        "cardColorSub": "検索バー・アラートダイアログ・カードの色",
        "cardGradSub": "カードのグラデーション",
        "changeDefault": "デフォルトに変更",
        "chartLocation": "Spotify チャートの場所",
        "chartLocationSub": "Spotify チャートの国",
        "checkingUpdate": "アップデートを確認中…",
        "checkUpdate": "自動的にアップデートを確認",
        "clear": "消去",
        "clearAll": "すべて消去",
        "clearCache": "キャッシュされた詳細を消去",
        "connectingRadio": "ラジオに接続中…",
        "contactUs": "我々に問い合わせ",
        "contactUsSub": "フィードバックは感謝されます!",
        "convertingSongs": "曲を変換中",
        "copied": "クリップボードにコピーしました!",
        "copy": "コピー",
        "countryQue": "どの地域の Spotify のチャートが見たいですか？",
        "createBack": "バックアップを作成",
        "darkMode": "ダークモード",
        "displayName": "表示名",
        "downDone": "ダウンロード完了",
        "downLocation": "ダウンロード場所",
        "downLyrics": "歌詞をダウンロード",
        "downQuality": "ダウンロード品質",
        "downQualitySub": "高品質では空き領域をより消費します",
        "downed": "はダウンロードされました",
        "duration": "長さ",
        "edit": "編集",
        "enforceRepeat": "強制的にリピート",
        "enterPlaylistLink": "プレイリストへのリンクを入力",
        "enterText": "テキストを入力",
        "enterThemeName": "テーマ名を入力",
        "excluded": "除外",
        "insta": "Instagram",
        "ipAdd": "IPアドレス",
        "joinTg": "Telegramにご参加ください",
        "joinTgSub": "テスト用ベータ版を試したいですか ? ご参加ください !",
        "lang": "言語",
        "langSub": "アプリテキストの言語",
        "lastAdded": "最後に追加された日時",
        "lastModified": "最終更新日時",
        "lastSession": "最新のセッション",
        "latest": "おめでとう! 最新版を使用しています :)",
        "library": "ライブラリ",
        "like": "いいね",
        "live": "ライブ中",
        "local": "ローカル",
        "lyrics": "歌詞",
        "madeBy": "Ankit Sangwanが愛をこめて制作",
        "minutes": "分",
        "moreInfo": "詳細",
        "musicLang": "音楽の言語",
        "musicPlayback": "音楽と再生",
        "myMusic": "マイミュージック",
        "no": "いいえ",
        "noFolderSelected": "フォルダの選択なし",
        "noLangSelected": "音楽の言語が選択されていません。ホーム画面に表示する曲の言語を選択してください",
        "notAvailable": "利用不可",
        "nowPlaying": "再生中",
        "ok": "OK",
        "or": "または",
        "pause": "停止",
        "playNext": "次を再生",
        "playing": "再生中",
        "playingCap": "再生してません",
        "playlistShareText": "私のプレイリストを見てください!",
        "proxySet": "プロキシ設定",
        "proxySetSub": "プロキシIPとポートを変更",
        "rememberChoice": "選択を記憶",
        "remove": "削除",
        "removed": "削除しました",
        "removedFrom": "以下から削除しました",
        "removedFromFav": "お気に入りから削除しました",
        "rename": "名前の変更",
        "reset": "リセット",
        "restore": "復元",
        "restoreSub": "バックアップからデータを復元\nアプリを再起動する必要があるかもしれません\n",
        "resultsNotFound": "結果が見つかりませんでした",
        "savePlaylist": "プレイリストを保存",
        "saveTheme": "テーマを保存",
        "search": "検索",
        "searchText": "曲, アルバム, アーティスト",
        "searchVideo": "動画を検索",
        "searchYt": "YouTubeで検索",
        "selectBackFile": "バックアップファイルを選択",
        "selectDownLocation": "ダウンロード場所を選択",
        "selectDur": "長さを選択",
        "selectExportLocation": "エクスポート場所を選択",
        "selectJsonImport": "インポートするJSONファイルを選択",
        "settings": "設定",
        "share": "共有",
        "shareApp": "Appを共有",
        "shareAppSub": "友達に知らせる",
        "showHistory": "検索履歴を表示",
        "showQr": "QRコードを表示",
        "shuffle": "シャッフル",
        "size": "サイズ",
        "skip": "スキップ",
        "skipNext": "次にスキップ",
        "skipPrevious": "前にスキップ",
        "sleepAfter": "N曲後にスリープ",
        "sleepTimer": "スリープタイマー",
        "song": "曲",
        "songInfo": "曲の情報",
        "songPath": "曲のパス",
        "songs": "曲",
        "sorry": "ごめんなさい",
        "stopDown": "ダウンロードを中止",
        "tgGp": "Telegramグループ",
        "themeDeleted": "テーマを削除しました!",
        "themeSaved": "テーマを保存しました!",
        "title": "タイトル",
        "useProxy": "プロキシを使用",
        "willPlayNext": "次を再生",
        "year": "年",
        "yes": "はい",
        "ytDownQuality": "YouTube ダウンロード品質",
        "ytStreamQuality": "YouTube ストリーミング品質",
        "ytStreamQualitySub": "高品質ではデータ量が大きいです",
        "artists": "アーティスト",
        "autoplay": "自動再生",
        "cardColor": "カードの色",
        "date": "日時",
        "addedToFav": "お気に入りに追加",
        "addedToPlaylists": "プレイリストに追加しました",
        "artist": "アーティスト",
        "albumArtist": "アルバムアーティスト",
        "appTitle": "BlackHole",
        "autoBack": "自動バックアップ",
        "back": "戻る",
        "canvasColor": "キャンバスカラー",
        "cardGrad": "カードのグラデーション",
        "changeOrder": "長押しして順序を変更\n",
        "backNRest": "バックアップと復元",
        "canvasColorSub": "バックグラウンドキャンバスの色",
        "dateAdded": "追加日時",
        "delete": "削除",
        "deleteTheme": "テーマを削除",
        "createBackSub": "データのバックアップを作成",
        "createYtFold": "YouTubeダウンロード用の新規フォルダを作成",
        "deleted": "削除された",
        "inc": "増加",
        "play": "再生",
        "createPlaylist": "プレイリスト作成",
        "currentTheme": "現在のテーマ",
        "dec": "減少",
        "deleteThemeSubtitle": "削除しますか ?",
        "disclaimer": "注意:",
        "donateGpay": "GPayで寄付",
        "downAgain": "既に存在します\n再度ダウンロードしますか?",
        "favSongs": "お気に入りの曲",
        "guest": "ゲスト",
        "equalizer": "イコライザ",
        "exported": "エクスポートしました",
        "failedDelete": "削除に失敗",
        "failedTagEdit": "タグの編集に失敗",
        "favorites": "お気に入り",
        "fetchingStream": "音声ストリームを取得中",
        "downingAlbum": "アルバムをダウンロード中",
        "downloadSomething": "何かダウンロードしてください",
        "export": "エクスポート",
        "failedExport": "エクスポートに失敗",
        "failedImport": "インポートに失敗",
        "gmail": "Gmail",
        "homeGreet": "こんにちは",
        "finish": "完了",
        "genre": "ジャンル",
        "genres": "ジャンル",
        "getStarted": "始める",
        "global": "グローバル",
        "home": "ホーム",
        "importFile": "ファイルからインポート",
        "importPublicPlaylist": "公開プレイリストをインポート",
        "importSpotify": "Spotify からインポート",
        "importYt": "YouTube からインポート",
        "importResso": "Resso からインポート",
        "importSuccess": "インポート成功",
        "popularity": "人気",
        "port": "ポート",
        "upiCopied": "UPI IDをコピーしました!",
        "nothingPlaying": "何も再生していません",
        "selectBackLocation": "バックアップ場所を選択",
        "playlists": "プレイリスト",
        "searchHome": "検索ホーム",
        "tg": "Telegram",
        "supportEq": "イコライザサポート",
        "streamQuality": "ストリーミング品質",
        "successTagEdit": "タグ編集に成功!",
        "undo": "取り消し",
        "ui": "アプリのUI",
        "update": "アップデート",
        "useSystemTheme": "システムのテーマを使う",
        "sponsor": "プロジェクトをスポンサーする",
        "spotifyTopCharts": "Spotifyトップチャート",
        "tgCh": "Telegramチャンネル",
        "unknown": "不明",
        "unlike": "いいねを取り消す",
        "updateAvailable": "最新版があります!",
        "viewAlbum": "アルバムを表示",
        "youTube": "YouTube",
        "spotifyCharts": "Spotify チャート",
        "streamQualitySub": "高品質はより多くのデータを消費します",
        "theme": "テーマ",
        "watchVideo": "動画を見る",
        "ytDownQualitySub": "高品質では空き領域をより消費します",
        "useAmoled": "Amoled Dark Mode設定を使う",
        "versionSub": "タップでアップデートを確認",
        "viewAll": "すべて表示",
        "version": "バージョン",
        "viewArtist": "アーティストを表示",
        "welcome": "ようこそ",
        "confirmViewable": "プレイリストが表示可能であることを確認してください",
        "createAlbumFold": "アルバムとプレイリストのダウンロード用のフォルダを作成",
        "disclaimerText": "私たちはあなたの個人情報を何よりも尊重します。ここに入力するあなたの名前だけが記録されます。",
        "enableGestureSub": "プレーヤーのアートワーク上でタップ、長押し、スワイプなどを有効にします",
        "addSomething": "何かを追加してください",
        "bgGradSub": "どこでも背景として使用されるグラデーション",
        "checkUpdateSub":
            "F-Droid、IzzyOnDroid など、更新オプションを提供するアプリリポジトリから BlackHole をダウンロードしていれば、ここをオフのままにします。一方、GitHub など自動更新の提供していない提供元からダウンロードしていれば、オンにし更新の通知を受け取るようにできます。\n",
        "clearCacheSub":
            "ホームページ、Spotifyトップチャート、YouTube、最終セッションのデータなどキャッシュされた詳細を削除します。通常、データが巨大化するとアプリが自動的で消去します\n",
        "donateGpaySub": "少しでも笑顔になります:)\nタップして寄付するか、長押ししてUPIIDをコピーします",
        "downFilename": "名前の形式をダウンロード",
        "autoBackLocation": "自動バックアップの場所",
        "createAlbumFoldSub": "アルバムまたはプレイリストのダウンロード時に曲の共通フォルダを作成します",
        "createYtFoldSub": "YouTubeからダウンロードした曲用に別のフォルダを作成します",
        "downFilenameSub": "曲はこのファイル名の形式に従ってダウンロードされます",
        "downLyricsSub": "可能であれば、曲と一緒に歌詞をダウンロードする",
        "enableGesture": "アートワークでのジェスチャを有効化",
        "enforceRepeatSub": "すべてのセッションで同じリピートオプションを維持",
        "enterSongsCount": "曲数を入力してください",
        "sleepDur": "hh:mm の時間後にスリープ",
        "useBlurForNowPlayingSub": "不透明な透かしが再生中セクションの背景に使用されます",
        "from": "中の",
        "getLyricsOnline": "端末内の曲の歌詞を検索",
        "langQue": "どの言葉の歌を聴きたいですか？",
        "useDenseMini": "高密度ミニプレーヤーを使用",
        "exitConfirm": "再度戻るを押すとアプリを終了",
        "importPlaylist": "プレイリストをインポート",
        "includeExcludeFolder": "含める/除外するフォルダー",
        "includeExcludeFolderSub": "「マイミュージック」セクション内にフォルダを含めるまたは除外できます",
        "included": "含める",
        "includedDetails": "選択したフォルダの曲のみが表示されます",
        "mergePlaylists": "プレイリストの結合",
        "minAudioAlert": "音声の最小の長さ (秒)",
        "minAudioLen": "検索する音楽の最小の音声の長さ",
        "minAudioLenSub": "これより小さい長さの音声は「マイミュージック」セクションに表示されません",
        "musicLangSub": "ホーム画面に表示される曲用",
        "others": "ほか",
        "playerScreenBackground": "プレーヤー画面の背景",
        "showHere": "表示されるものはありません",
        "showPlaylists": "ホーム画面にプレイリストを表示",
        "useDenseMiniSub": "ミニプレイヤーの高さが低くなります",
        "useDown": "ストリーム時に可能ならダウンロードした曲を再生",
        "useDownSub": "曲が既にダウンロード済みならオンラインスのトリーミングではなくダウンロード済みの曲を再生します",
        "yesReplace": "はい、古いものと置換",
        "openInSpotify": "Spotify で開く",
        "useProxySub":
            "インド以外の国でインドの曲しか出ない、検索結果がないなど、検索に問題があればこれをオンにしてください。インドのサーバーを利用したVPNを利用することもできます\n",
        "yourPlaylists": "プレイリスト",
        "nothingIs": "何も ",
        "mostPlayedSong": "最も再生された曲",
        "prefReq": "いくつかお答えくださいませんか？",
        "playerScreenBackgroundSub": "選択した背景がプレーヤー画面に表示されます",
        "radio": "ラジオ",
        "shareAppText": "ねぇねぇこの音楽プレーヤーのアプリいいよ",
        "showHistorySub": "検索履歴を検索バーの下に表示",
        "showLast": "最後のセッションを表示",
        "showTopCharts": "トップチャートを表示",
        "showTopChartsSub": "ホーム画面にSpotifyトップチャートを表示",
        "stopOnClose": "アプリを閉じたら音楽を停止",
        "stats": "統計",
        "supportEqSub": "曲を再生できないならこれをオフにしてください (オンライン/オフラインモード共に)",
        "topCharts": "トップチャート",
        "trendingSearch": "トレンド検索",
        "useVpn": "インド以外の国ですか ? インドのサーバーのVPNをお試しください",
        "cantFind": "探しているものが見つかりませんか ? ",
        "excludedDetails": "選択したフォルダ内の曲を表示しません",
        "getLyricsOnlineSub": "オフラインの曲の歌詞が利用/ダウンロード済みでない時、オンラインで検索します",
        "importJioSaavn": "JioSaavn からインポート",
        "likedWork": "アプリを気に入っていますか？",
        "liveSearch": "すぐ検索",
        "liveSearchSub": "入力を止めると同時に曲を検索",
        "loadLastSub": "アプリ起動時に最後のセッションを自動で読み込む",
        "loadLast": "アプリ起動時に最後のセッションを読み込む",
        "miniButtonsSub": "タップして、ミニプレーヤーに表示するボタンを変更します",
        "miniButtons": "見にプレーヤーに表示するボタン",
        "playSomething": "何か再生してください",
        "playRadio": "ラジオを再生",
        "sleepAfterSub": "選択した曲数の再生後に音楽が停止",
        "shareLogsSub": "現在のセッションのログを共有",
        "signInSpotify": "Spotifyにログイン",
        "sleepTimerSetFor": "スリープタイマーを設定",
        "ytLiveAlert": "動画がライブ放送か、またはエラーが発生しています。ライブの終了まで待つか、再度お試しください。",
        "nothingTo": "何も ",
        "shareLogs": "ログを共有",
        "showLastSub": "ホーム画面に最後のセッションを表示",
        "sleepDurSub": "選択した時間後に音楽が停止",
        "stopOnCloseSub":
            "オフなら、アプリを「閉じて」も、停止ボタンを押すまで音楽は停止しません。アプリを「閉じる」時のオプションで、「バックグラウンド」で実行中の時のものではありません。音楽は常にバックグラウンドで再生され、その設定を変更する必要はありません。\n",
      };
}
