class ZHHANT {
  static Map<String, String> get keys => {
        "aboutLine1": "這個軟體是開放原始碼專案，你可以在這裡找到原始碼",
        "about": "關於",
        "bgGrad": "背景漸層",
        "blacklistedHomeSectionsSub": "包含這些標題的部分不會顯示在主頁",
        "aboard": "正在播放",
        "aboutLine2": "如果你喜歡這個APP, \n請給我的repo按個⭐",
        "accent": "強調顏色與色調",
        "addToQueue": "加入佇列",
        "addedToFav": "已添加至我的最愛",
        "alreadyInQueue": "已在佇列中",
        "appTitle": "BlackHole",
        "artists": "藝人",
        "autoBackLocation": "自動備份位置",
        "autoBackSub": "自動備份資料",
        "autoplay": "自動播放",
        "addNew": "建立",
        "addedToPlaylists": "已添加至播放清單",
        "addSomething": "添加新內容",
        "addToPlaylist": "添加至播放清單",
        "addedBy": "添加方式",
        "addedTo": "已添加至",
        "autoBack": "自動備份",
        "autoplaySub": "自動接續播放類似歌曲",
        "backNRest": "備份&恢復",
        "albumArtist": "專輯藝人",
        "addedToQueue": "已添加至佇列",
        "adjustSpeed": "調整速度",
        "albums": "專輯",
        "alphabetical": "按字母排序",
        "album": "專輯",
        "alreadyExists": "已存在",
        "artist": "藝人",
        "canvasColorSub": "應用程式主背景顏色",
        "back": "返回",
        "backupSuccess": "成功備份",
        "bgGradSub": "永遠使用漸層背景",
        "blacklistedHomeSections": "Blacklisted Home Sections",
        "bottomGrad": "底欄漸層",
        "bottomGradSub": "在底欄使用漸層",
        "canvasColor": "背景顏色",
        "cardColor": "卡牌顏色",
        "buyCoffee": "Buy me a coffee ☕",
        "cache": "快取",
        "cacheSong": "快取歌曲",
        "cantFind": "找不到喔！ ",
        "cacheSongSub":
            "Songs will be cached for future playback. Additional space on your device will be taken",
        "cancel": "取消",
        "cantAddToQueue": "無法將線上歌曲添加至本地播放佇列",
        "cardGradSub": "Gradient used in Cards",
        "cardColorSub": "搜尋框、提示框和卡片顏色",
        "cardGrad": "卡片漸層",
      };
}
