class EL {
  static Map<String, String> get keys => {
        "checkUpdate": "Αυτόματος έλεγχος για ενημερώσεις",
        "aboutLine2": "Αν σου άρεσε η δουλειά μου\nδείξε ♥ και ⭐ το repo",
        "cancel": "Ακύρωση",
        "cantAddToQueue":
            "Δεν μπορείς να προσθέσεις διαδικτυακό τραγούδι σε ουρά εκτός σύνδεσης",
        "addedToQueue": "Προστέθηκε στην ουρά",
        "aboutLine1":
            "Αυτό είναι ένα πρόγραμμα ανοιχτού κώδικα και μπορεί να βρεθεί στο",
        "addToQueue": "Προσθήκη στην ουρά",
        "addedBy": "Προστέθηκε απο",
        "addedTo": "Προστέθηκε στο",
        "addedToFav": "Προστέθηκε στα Αγαπημένα",
        "addedToPlaylists": "Προστέθηκε στην λίστα αναπαραγωγής",
        "adjustSpeed": "Ρύθμιση ταχύτητας",
        "album": "Άλμπουμ",
        "albumArtist": "Καλλιτέχνης άλμπουμ",
        "alphabetical": "Αλφαβητικά",
        "alreadyExists": "Υπάρχει ίδη",
        "alreadyInQueue": "Ίδη στην ουρά",
        "appTitle": "BlackHole",
        "artist": "Καλλιτέχνης",
        "artists": "Καλλιτέχνες",
        "contactUsSub": "Τα σχόλια εκτιμήθηκαν!",
        "convertingSongs": "Μετατροπή τραγουδιών",
        "addNew": "Πρόσθεσε νέο",
        "changeOrder": "Πατήστε παρατεταμένα για αλλαγή σειράς\n",
        "addSomething": "Πάνε και πρόσθεσε κάτι",
        "addToPlaylist": "Προσθήκη στην λίστα αναπαραγωγής",
        "chartLocation": "Τοπικά γραφήματα Spotify",
        "chartLocationSub": "Χώρα για τα κορυφαία τοπικά γραφήματα του Spotify",
        "back": "Πίσω",
        "connectingRadio": "Σύνδεση στο ραδιόφωνο…",
        "checkingUpdate": "Έλεγχος για ενημερώσεις…",
        "confirmViewable": "Βεβαιωθείτε ότι η λίστα αναπαραγωγής είναι ορατή",
        "contactUs": "Επικοινωνήστε μαζί μας",
        "cardColorSub":
            "Χρώμα γραμμής αναζήτησης, διαλόγων ειδοποιήσεων, καρτών",
      };
}
