class PEO {
  static Map<String, String> get keys => {
        "@@locale": "fa_PAL",
        "addedBy": "اضافه شده توسط",
        "about": "درباره",
        "aboutLine2": "اگر کار من را دوست دارید\n♥  کنید و مخزن را ⭐  کنید",
        "accent": "شدت رنگ و شکل",
        "addNew": "اضافه کن",
        "addSomething": "برو و یه چیزی اضافه کن",
        "addedToFav": "به موارد دلخواه اضافه شد",
        "addedToQueue": "به صف پخش اضافه شد",
        "adjustSpeed": "تنظیم سرعت",
        "alphabetical": "به ترتیب حروف الفبا",
        "alreadyExists": "در حال حاضر وجود دارد",
        "autoBack": "پشتیبان گیری خودکار",
        "back": "عقب",
        "backNRest": "پشتیبان گیری و بازیابی",
        "bgGradSub": "گرادیانت به عنوان پس‌زمینه در همه جا استفاده شود",
        "aboutLine1": "این یک پروژه متن باز است و میتوانید آن را پیدا کنید",
        "addToPlaylist": "به پلی لیست اضافه کن",
        "addToQueue": "به صف پخش اضافه کن",
        "addedTo": "اضافه شده به",
        "addedToPlaylists": "به پلی لیست اضافه شد",
        "albumArtist": "هنرمند آلبوم",
        "album": "آلبوم",
        "albums": "آلبوم ها",
        "appTitle": "سیاه چاله",
        "autoBackLocation": "مکان پشتیبان گیری خودکار",
        "alreadyInQueue": "در حال حاضر در صف وجود دارد",
        "autoplay": "پخش خودکار",
        "artist": "هنرمند",
        "artists": "هنرمندان",
        "autoBackSub": "پشتیبان گیری خودکار از داده ها",
        "backupSuccess": "پشتیبان گیری با موفقیت انجام شد",
        "autoplaySub": "آهنگ های مرتبط را به صورت خودکار به صف اضافه کنید",
        "blacklistedHomeSections": "بخش های خانه در لیست سیاه",
        "blacklistedHomeSectionsSub":
            "بخش‌هایی با این عناوین در صفحه اصلی نشان داده نمی‌شوند",
        "bgGrad": "گرادیانت پس زمینه",
      };
}
