class HU {
  static Map<String, String> get keys => {
        "about": "Névjegy",
        "aboutLine2": "Ha tetszett a munkám\nNyomj ♥-et és⭐-ot a repora",
        "accent": "Kiemelő szín és árnyalat",
        "appTitle": "BlackHole",
        "artist": "Előadó",
        "artists": "Előadók",
        "backNRest": "Biztonsági mentés és visszaállítás",
        "cancel": "Mégsem",
        "autoplaySub":
            "Kapcsolódó dalok automatikus hozzáadása a lejátszási listához",
        "addToQueue": "Hozzáadás a lejátszási sorhoz",
        "addNew": "Új hozzáadása",
        "aboard": "A fedélzeten",
        "backupSuccess": "Sikeres biztonsági mentés",
        "alphabetical": "Betűrendben",
        "addSomething": "Menj és adj hozzá valamit",
        "addToPlaylist": "Hozzáadás a lejátszási listához",
        "addedBy": "Hozzáadta",
        "addedTo": "Hozzáadva a",
        "addedToFav": "Hozzáadva a kedvencekhez",
        "addedToPlaylists": "Hozzáadva a lejátszási listákhoz",
        "addedToQueue": "Hozzáadva a lejátszási sorhoz",
        "adjustSpeed": "Sebesség beállítása",
        "alreadyExists": "Már létezik",
        "alreadyInQueue": "Már a lejátszási sorban",
        "albumArtist": "Album előadója",
        "autoBack": "Automatikus biztonsági mentés",
        "autoBackLocation": "Automatikus biztonsági mentés helye",
        "autoBackSub": "Automatikus adatmentés",
        "bgGrad": "Háttér színátmenet",
        "autoplay": "Automatikus lejátszás",
        "bgGradSub": "Színátmenet használata háttérként mindenhol",
        "blacklistedHomeSectionsSub":
            "Az ilyen címekkel ellátott szakaszok nem jelennek meg a Kezdőképernyőn",
        "blacklistedHomeSections": "Feketelistára került főoldal szakaszok",
        "cacheSong": "Gyorsítótárazott dalok",
        "bottomGrad": "Alsó lapok színátmenete",
        "bottomGradSub": "Az alsó lapokban használt színátmenet",
        "checkingUpdate": "Frissítések keresése…",
        "checkUpdate": "Frissítések automatikus keresése",
        "copy": "Másolás",
        "countryQue":
            "Melyik ország esetében szeretnéd látni a Spotify Local Charts-ot?",
        "confirmViewable":
            "Győződj meg róla, hogy a lejátszási lista megtekinthető",
        "changeOrder": "Hosszan nyomd meg a sorrend megváltoztatásához\n",
        "contactUs": "Kapcsolatfelvétel",
        "copied": "Vágólapra másolva!",
        "dec": "Csökkenő",
        "downDone": "A letöltés kész",
        "dateAdded": "Hozzáadás dátuma",
        "convertingSongs": "A dalok konvertálása",
        "cantAddToQueue":
            "Nem lehet online dalt hozzáadni az offline lejátszási sorhoz",
        "canvasColorSub": "A háttér színe",
        "cardColor": "Kártya színe",
        "canvasColor": "Háttér színe",
        "createBackSub": "Biztonsági mentés készítése",
        "contactUsSub": "A visszajelzéseket nagyra értékeljük!",
        "changeDefault": "Váltás alapértelmezettre",
        "clear": "Törlés",
        "clearAll": "Összes törlése",
        "cardGrad": "Kártya színátmenete",
        "cardGradSub": "Kártyákban használt színátmenet",
        "connectingRadio": "Csatlakozás a rádióhoz…",
        "clearCache": "Gyorsítótárazott adatok törlése",
        "createAlbumFold":
            "Mappa létrehozása az Albumok és Lejátszási listák letöltéséhez",
        "createAlbumFoldSub":
            "Közös mappa létrehozása a zenékhez, amikor az albumokat és lejátszási listák letöltése befejeződött",
        "createBack": "Biztonsági mentés létrehozása",
        "enterSongsCount": "Add meg a dalok számát",
        "fetchingStream": "Audiófolyam lekérése",
        "finish": "Befejezés",
        "from": "a",
        "getLyricsOnline": "Helyi dalszövegek keresése",
        "getLyricsOnlineSub":
            "Online keresés, ha a dalszövegek nem elérhetők/letölthetők bármely offline dalhoz",
        "genre": "Műfaj",
        "genres": "Műfajok",
        "getStarted": "Kezdjünk hozzá",
        "global": "Globális",
        "gmail": "Gmail",
        "guest": "Vendég",
        "home": "Kezdőlap",
        "importFile": "Importálás fájlból",
        "importJioSaavn": "Importálás JioSaavn-ról",
        "importPublicPlaylist": "Nyilvános lejátszási lista importálása",
        "importResso": "Importálás Resso-ról",
        "importSpotify": "Importálás Spotify-ról",
        "importSuccess": "Sikeresen importált",
        "importYt": "Importálás YouTube-ról",
        "inc": "Növekvő",
        "insta": "Instagram",
        "ipAdd": "IP cím",
        "live": "LIVE NOW",
        "minutes": "percek",
        "no": "Nem",
        "ok": "Ok",
        "or": "vagy",
        "includeExcludeFolder": "Mappák felvétele/kizárása",
        "includeExcludeFolderSub":
            "Kiválasztott mappák felvétele/kizárása a 'Saját zene' szekcióból",
        "included": "Tartalmazza",
        "includedDetails": "Csak a kiválasztott mappák dalai jelennek meg",
        "lastAdded": "Utoljára hozzáadva",
        "lastModified": "Utoljára módosítva",
        "lastSession": "Utolsó munkamenet",
        "loadLast": "Utolsó munkamenet betöltése az alkalmazás indításakor",
        "minAudioAlert": "Minimális hanghossz (másodpercben)",
        "minAudioLen": "Minimális hanghossz a zene kereséséhez",
        "minAudioLenSub":
            "Az ennél kisebb hosszúságú audiók nem jelennek meg a 'Saját zene' szekcióban",
        "prefReq": "Elmondanál nekünk néhány dolgot?",
        "useBlurForNowPlayingSub":
            "Elmosódás alacsonyabb átlátszósággal lesz a Most lejátszás szakasz háttereként használva",
        "welcome": "Üdvözlünk",
        "year": "Év",
        "yes": "Igen",
        "yesReplace": "Igen, de cserélje ki a régit",
        "watchVideo": "Videó megtekintése",
        "useProxy": "Proxy használata",
        "useProxySub":
            "Kapcsold be ezt a funkciót, ha nem Indiából származol, és problémáid vannak a kereséssel, például csak indiai dalokat kapsz, vagy nem kapsz semmilyen eredményt stb. Akár VPN-t is használhatsz indiai szerverrel\n",
        "useSystemTheme": "Rendszertéma használata",
        "useVpn": "Nem Indiából? Próbáld ki a VPN-t indiai szerverrel",
        "version": "Verzió",
        "versionSub": "Érintsd meg a frissítések kereséséhez",
        "viewAlbum": "Album megtekintése",
        "viewArtist": "Előadó megtekintése",
        "viewAll": "Összes megtekintése",
        "youTube": "YouTube",
        "ytDownQuality": "YouTube letöltési minőség",
        "ytDownQualitySub": "A magasabb minőség több helyet használ",
        "yourPlaylists": "Lejátszási listáid",
        "ytLiveAlert":
            "A videó élőben van. Kérjük, várj, amíg az élő közvetítés befejeződik, és próbáld meg újra.",
        "ytStreamQuality": "YouTube streaming minőség",
        "ytStreamQualitySub": "A magasabb minőség több adatot használ",
        "willPlayNext": "lejátszás a következő lesz",
        "useHome":
            "Használd a fő szekciót a jobb minőségért és a letöltési támogatásért",
        "useDownSub":
            "Ha a dal már le van töltve, a letöltött dal fog lejátszódni az online streaming helyett",
        "useDown": "Letöltött dalok streamelése, ha elérhető",
        "back": "Vissza",
        "aboutLine1": "Ez egy nyílt forráskódú projekt",
        "album": "Album",
        "albums": "Albumok",
        "buyCoffee": "Vegyél nekem egy kávét",
        "cache": "Gyorsítótár",
        "checkUpdateSub":
            "Ha a BlackHole-t olyan alkalmazás-tárhelyről töltötted le, mint az 'F-Droid', 'IzzyOnDroid' stb., amelyek frissítési lehetőségeket biztosítanak, tartsd ezt KIKAPCSOLVA. Ha viszont a 'GitHub'-ról vagy bármely más forrásból töltötte le, amely nem biztosít automatikus frissítési lehetőséget, akkor kapcsold be, hogy frissítési értesítést kapj.\n",
        "darkMode": "Sötét mód",
        "createYtFold": "Külön mappa létrehozása a YouTube letöltésekhez",
        "date": "Dátum",
        "donateGpay": "Adományozz GPay segítségével",
        "cardColorSub":
            "A keresősáv, a figyelmeztető párbeszédpanelek, és a kártyák színe",
        "cacheSongSub":
            "A dalok a későbbi lejátszás érdekében gyorsítótárba kerülnek. A készülékeden több helyet foglal el",
        "chartLocationSub": "Ország a Top Spotify Local Charts-ra",
        "chartLocation": "Spotify Local Charts helye",
        "clearCacheSub":
            "Törli a gyorsítótárazott adatokat, beleértve a kezdőlapot, a Spotify Top Charts-ot, a YouTube és az utolsó munkamenet adatait. Általában az alkalmazás automatikusan törli őket, amikor az adatok nagyok lesznek\n",
        "downFilename": "Letöltési név formátuma",
        "createPlaylist": "Lejátszási lista létrehozása",
        "deleteTheme": "Téma törlése",
        "delete": "Törlés",
        "deleted": "Törölve",
        "createNewPlaylist": "Új lejátszási lista létrehozása",
        "deleteThemeSubtitle": "Biztos, hogy törölni akarod?",
        "failedExport": "Sikertelen exportálás",
        "createYtFoldSub":
            "Külön mappa létrehozása a YouTube-ról letöltött dalok számára",
        "currentTheme": "Jelenlegi téma",
        "disclaimer": "Felelősségi nyilatkozat:",
        "downFilenameSub":
            "A dalok letöltése a következő fájlnév formátum szerint történik",
        "downQuality": "Letöltés minősége",
        "liveSearchSub":
            "Dalok keresése, amint a felhasználó abbahagyja a gépelést",
        "lang": "Nyelv",
        "disclaimerText":
            "Mindennél jobban tiszteljük a magánéleted. Csak a neved rögzítjük, amelyet itt adtál meg.",
        "downLyrics": "Dalszövegek letöltése",
        "madeBy": "♥-el készült Ankit Sangwan által",
        "notAvailable": "Nem elérhető",
        "musicLangSub": "Dalok megjelenítése a kezdőképernyőn",
        "local": "Helyi",
        "musicLang": "Zene nyelve",
        "musicPlayback": "Zene és lejátszás",
        "displayName": "Megjelenített név",
        "donateGpaySub":
            "Minden kis mennyiség mosolyt csal az arcomra :)\nÉrintsd meg az adományozáshoz vagy hosszan nyomd meg az UPI azonosító másolásához",
        "down": "Letöltés",
        "downAgain": "már létezik.\nSzeretnéd újra letölteni?",
        "downs": "Letöltések",
        "failedTagEdit": "Nem sikerült a címkéket szerkeszteni",
        "homeGreet": "Szia,",
        "downLocation": "Letöltés helye",
        "downQualitySub": "A magasabb minőség több helyet használ",
        "downloadSomething": "Valami letöltése",
        "downLyricsSub":
            "Dalszövegek letöltése a dallal együtt, ha rendelkezésre állnak",
        "equalizer": "Kiegyenlítő",
        "library": "Könyvtár",
        "downed": "letöltésre került",
        "downingAlbum": "Album letöltése",
        "duration": "Időtartam",
        "enableGestureSub":
            "Lehetővé teszi a koppintást, hosszan nyomást, swipe-olást, stb. a művészeti alkotáson a lejátszó képernyőn",
        "enforceRepeat": "Ismétlés kikényszerítése",
        "edit": "Szerkesztés",
        "enableGesture": "Művészeti gesztusok engedélyezése",
        "enforceRepeatSub":
            "Tartsd meg ugyanazt az ismétlési opciót minden munkamenethez",
        "enterPlaylistLink": "Add meg a lejátszási lista linkjét",
        "enterThemeName": "Téma nevének megadása",
        "joinTgSub":
            "Szeretnéd tesztelni a béta verziókat? Csatlakozz hozzánk most!",
        "enterName": "Add meg a neved",
        "enterText": "Szöveg beírása",
        "excluded": "Kivéve",
        "excludedDetails": "A kiválasztott mappák dalai nem jelennek meg",
        "export": "Export",
        "exported": "Exportált",
        "failedDelete": "Sikertelen törlés",
        "exitConfirm":
            "Nyomd meg újra a Vissza gombot az alkalmazásból való kilépéshez",
        "failedCreateBackup": "Sikertelen a biztonsági mentés létrehozása",
        "favSongs": "Kedvenc dalok",
        "failedImport": "Sikertelen importálás",
        "favorites": "Kedvencek",
        "langSub": "Alkalmazás nyelve",
        "langQue": "Milyen nyelvű dalokat hallgatnál szívesebben?",
        "joinTg": "Csatlakozz hozzánk Telegramon",
        "latest": "Gratulálok! A legújabb verziót használod :)",
        "loadLastSub":
            "Automatikusan betölti az utolsó munkamenetet az alkalmazás indításakor",
        "likedWork": "Tetszett a munkám?",
        "liveSearch": "Élő keresés",
        "like": "Tetszik",
        "lyrics": "Dalszöveg",
        "search": "Keresés",
        "saveTheme": "Téma mentése",
        "restore": "Visszaállítás",
        "savePlaylist": "Lejátszási lista mentése",
        "moreInfo": "Több információ",
        "others": "Mások",
        "nowPlaying": "Most hallgatja",
        "play": "Lejátszás",
        "myMusic": "Saját zenék",
        "pause": "Szünet",
        "playlists": "Lejátszási listák",
        "playNext": "Következő lejátszása",
        "proxySet": "Proxy beállítások",
        "playing": "Most hallgatja",
        "rename": "Átnevezés",
        "reset": "Visszaállítás",
        "resetOnSkip": "Ismétlés az előző kihagyáskor",
        "resetOnSkipSub": "Lejátszás az elejétől az előző dalra ugrás helyett",
        "restoreSub":
            "Állítsd vissza az adataid biztonsági mentésből. \nLehet, hogy újra kell indítanod az alkalmazást\n",
        "resultsNotFound": "Nincsenek találatok",
        "searchHome": "Keresés a főoldalon",
        "searchText": "Zenék, albumok vagy előadók",
        "searchVideo": "Videó keresése",
        "searchYt": "Keresés YouTube-on",
        "selectDownLocation": "Letöltési hely kiválasztása",
        "selectDur": "Időtartam kiválasztása",
        "selectExportLocation": "Exportálási hely kiválasztása",
        "selectJsonImport": "JSON fájl kiválasztása importálásra",
        "settings": "Beállítás",
        "showLastSub": "Utolsó munkamenet megjelenítése a kezdőképernyőn",
        "remove": "Eltávolítás",
        "rememberChoice": "Emlékezz a választásomra",
        "showHistory": "Keresési előzmények megjelenítése",
        "showHistorySub": "Keresési előzmények megjelenítése a keresősáv alatt",
        "showLast": "Utolsó munkamenet megjelenítése",
        "stopOnClose": "Zene leállítása az alkalmazás bezárásakor",
        "showPlaylists": "Lejátszási listák megjelenítése a kezdőképernyőn",
        "stopOnCloseSub":
            "Ha ki van kapcsolva, a zene az alkalmazás \"bezárása\" után sem áll le, amíg meg nem nyomod a leállítás gombot. Ez az opció az alkalmazás \"bezárására\" vonatkozik, nem pedig arra, amikor az alkalmazás \"háttérben\" van. A zene mindig a háttérben fog szólni, ehhez nem kell semmilyen beállítást megváltoztatni.\n",
        "miniButtonsSub":
            "Érintsd meg a gombok megváltoztatásához a Mini Lejátszóban",
        "noFolderSelected": "Nincs kiválasztott mappa",
        "noLangSelected":
            "Nincs kiválasztott zenei nyelv. Válaszd ki a nyelvet a dalok megjelenítéséhez a kezdőképernyőn",
        "nothingIs": "Semmi sem ",
        "nothingPlaying": "Semmi sem játszódik",
        "nothingTo": "Semmi sem ",
        "playerScreenBackground": "Lejátszási képernyő háttere",
        "playerScreenBackgroundSub":
            "A kiválasztott háttér megjelenik a lejátszó képernyőn",
        "miniButtons": "Gombok megjelenítése a Mini lejátszóban",
        "playRadio": "Rádió lejátszása",
        "playSomething": "Menj és játssz valamit",
        "playingCap": "LEJÁTSZÁS",
        "playlistShareText": "Nézd meg a lejátszási listámat!",
        "popularity": "Népszerűség",
        "port": "Port",
        "proxySetSub": "Proxy IP és Port módosítása",
        "removed": "Eltávolítva",
        "removedFrom": "Eltávolítva a",
        "removedFromFav": "Eltávolítva a kedvencek közül",
        "selectBackFile": "Biztonsági mentés fájl kiválasztása",
        "selectBackLocation": "Biztonsági mentés helyének kiválasztása",
        "share": "Megosztás",
        "shareApp": "Alkalmazás megosztása",
        "shareAppSub": "Mondd el a barátaidnak, hogy megismerjenek minket",
        "shareAppText": "Helló! Nézd meg ezt a menő zenelejátszó alkalmazást",
        "showHere": "Mutasd meg itt",
        "showQr": "QR-kód megjelenítése",
        "shuffle": "Keverés",
        "size": "Méret",
        "skip": "Ugrás",
        "skipNext": "Ugorj tovább",
        "skipPrevious": "Előzőre ugrás",
        "sleepAfter": "Alvás N dalok után",
        "sleepAfterSub": "A zene leáll a kiválasztott dalok lejátszása után",
        "sleepDurSub": "A zene a kiválasztott időtartam után leáll",
        "sleepDur": "Alvás hh:mm időtartam után",
        "sleepTimer": "Alvás időzítő",
        "sleepTimerSetFor": "Alvás időzítő beállítva",
        "song": "Dal",
        "songInfo": "Dal infó",
        "songPath": "Dal útvonala",
        "songs": "Dalok",
        "sorry": "BOCSI",
        "sponsor": "Támogasd ezt a projektet",
        "spotifyCharts": "Spotify slágerlisták",
        "spotifyPublic": "Spotify Nyilvános",
        "spotifyTopCharts": "Spotify Top Slágerlisták",
        "stopDown": "Letöltés leállítása",
        "streamQuality": "Streamelés minősége",
        "streamQualitySub": "A magasabb minőség több adatot használ",
        "successTagEdit": "Sikeresen szerkesztett címkék !",
        "supportEq": "Equalizer támogatás",
        "supportEqSub":
            "Tartsd kikapcsolva, ha nem tudod lejátszani a dalokat (online és offline módban egyaránt)",
        "tg": "Telegram",
        "tgCh": "Telegram csatorna",
        "tgGp": "Telegram csoport",
        "theme": "Téma",
        "themeDeleted": "Téma törölve!",
        "themeSaved": "Téma mentve!",
        "title": "Cím",
        "topCharts": "Legjobb Slágerlisták",
        "trendingSearch": "Trendkeresés",
        "ui": "Alkalmazás felhasználói felület",
        "undo": "Visszavonás",
        "unknown": "Ismeretlen",
        "unlike": "Különböző",
        "update": "Frissítés",
        "updateAvailable": "Frissítés elérhető!",
        "upiCopied": "UPI ID másolva!",
        "upNext": "Következő",
        "useAmoled": "Amoled sötét mód beállításainak használata",
        "useDenseMiniSub": "A minilejátszó magassága csökken",
        "useDenseMini": "Sűrített minilejátszó használata",
        "importPlaylist": "Lejátszási lista importálása",
        "mergePlaylists": "Lejátszási listák egyesítése",
        "top": "Legjobb",
        "viral": "Virális",
        "radio": "Rádió",
        "openInSpotify": "Nyisd meg Spotify-on",
        "signInSpotify": "Bejelentkezés Spotifyba",
      };
}
