class DE {
  static Map<String, String> get keys => {
        "aboutLine1":
            "Dies ist ein quelloffenes Projekt und man kann es finden auf",
        "addSomething": "Gehe und füge etwas hinzu",
        "addToPlaylist": "Zur Wiedergabeliste hinzufügen",
        "addedBy": "Hinzugefügt von",
        "addedToFav": "Zu Favoriten hinzugefügt",
        "addedToQueue": "Zur Warteschlange hinzugefügt",
        "adjustSpeed": "Geschwindigkeit anpassen",
        "canvasColorSub": "Farbe der Hintergrundleinwand",
        "copy": "Kopieren",
        "countryQue":
            "Für welches Land würdest du gerne die Spotify-Local-Charts sehen?",
        "createAlbumFold":
            "Ordner fürs Herunterladen von Alben und Wiedergabelisten erstellen",
        "createAlbumFoldSub":
            "Erstellt einen gemeinsamen Ordner für die Lieder, wenn ein Album oder eine Wiedergabeliste heruntergeladen wird",
        "createBack": "Sicherung erstellen",
        "createPlaylist": "Wiedergabeliste erstellen",
        "createYtFold": "Anderen Ordner für Musik aus YouTube erstellen",
        "currentTheme": "Aktuelles Farbschema",
        "darkMode": "Dunkler Modus",
        "dateAdded": "Datum hinzugefügt",
        "delete": "Löschen",
        "deleted": "Gelöscht",
        "deleteTheme": "Farbschema löschen",
        "deleteThemeSubtitle": "Bist du sicher, dass du löschen willst?",
        "disclaimer": "Haftungsausschluss :",
        "disclaimerText":
            "Wir respektieren deine Privatsphäre mehr als alles andere. Nur dein Name, den du hier eingeben, wird gespeichert.",
        "donateGpay": "Mit GPay spenden",
        "donateGpaySub":
            "Jeder kleine Betrag bringt mich zum Lächeln :)\nTippen Sie, um zu spenden oder drücken Sie lange, um die UPI-ID zu kopieren",
        "down": "Herunterladen",
        "downDone": "Herunterladen erledigt",
        "downLocation": "Speicherort",
        "downLyricsSub": "Herunterladen von Liedtexten, falls verfügbar",
        "downQuality": "Qualität",
        "downQualitySub": "Höhere Qualität verbraucht mehr Speicherplatz",
        "downingAlbum": "Album wird heruntergeladen",
        "downloadSomething": "Etwas herunterladen",
        "downs": "Heruntergeladene Dateien",
        "edit": "Bearbeiten",
        "enableGesture": "Gesten für Kunstwerke aktivieren",
        "enforceRepeat": "Wiederholung erzwingen",
        "enterName": "Gib deinen Namen ein",
        "enterPlaylistLink": "Gib den Link zur Wiedergabeliste ein",
        "enterText": "Gib Text ein",
        "enterSongsCount": "Gib die Anzahl der Titel ein",
        "enterThemeName": "Gib den Name des Farbschemas ein",
        "export": "Exportieren",
        "exported": "Exportiert",
        "failedDelete": "Fehler beim Löschen",
        "failedExport": "Fehler beim Exportieren",
        "failedImport": "Fehler beim Importieren",
        "failedTagEdit": "Schlagwörter konnten nicht bearbeitet werden",
        "favorites": "Favoriten",
        "fetchingStream": "Abrufen des Audiostreams",
        "finish": "Beenden",
        "from": "aus",
        "getStarted": "Los geht’s",
        "home": "Startseite",
        "homeGreet": "Hallo,",
        "importFile": "Aus Datei importieren",
        "importPublicPlaylist": "Öffentliche Wiedergabeliste importieren",
        "importSpotify": "Aus Spotify importieren",
        "importSuccess": "Erfolgreich importiert",
        "importYt": "Aus YouTube importieren",
        "inc": "Zunehmend",
        "insta": "Instagram",
        "ipAdd": "IP-Adresse",
        "joinTg": "Begleite uns auf Telegram",
        "joinTgSub": "Möchtest du Beta-Versionen testen? Mach jetzt mit!",
        "lang": "Sprache",
        "langQue": "In welcher Sprache würdest du Lieder am liebsten hören?",
        "langSub": "Textsprache der Anwendung",
        "lastAdded": "Zuletzt hinzugefügt",
        "latest":
            "Herzlichen Glückwunsch! Du verwendest die neueste Version :)",
        "library": "Bibliothek",
        "likedWork": "Hat dir meine Arbeit gefallen?",
        "live": "JETZT LIVE",
        "liveSearch": "Live-Suche",
        "loadLast": "Letzte Sitzung beim Start laden",
        "loadLastSub":
            "Automatisches Laden der letzten Sitzung beim Start der Anwendung",
        "local": "Lokal",
        "lyrics": "Liedtext",
        "minAudioAlert": "Min. Audiolänge (in Sekunden)",
        "minAudioLen": "Minimale Audiolänge für die Suche nach Musik",
        "miniButtons": "Schaltflächen, die im Mini-Player angezeigt werden",
        "miniButtonsSub":
            "Tippe auf , um die im Mini-Player angezeigten Schaltflächen zu ändern",
        "minutes": "Minuten",
        "musicLang": "Sprache der Musik",
        "musicLangSub": "Um Titel auf dem Startbildschirm anzuzeigen",
        "musicPlayback": "Musik und Wiedergabe",
        "myMusic": "Meine Musik",
        "no": "Nein",
        "noFolderSelected": "Kein Ordner ausgewählt",
        "notAvailable": "Nicht verfügbar",
        "nothingIs": "Nichts ist ",
        "nothingTo": "Nichts zu ",
        "nowPlaying": "Wird jetzt abgespielt",
        "ok": "OK",
        "or": "ODER",
        "others": "Andere",
        "pause": "Pause",
        "play": "Abspielen",
        "playNext": "Zunächst hören",
        "playSomething": "Geh und spiel etwas ab",
        "playing": "Wird abgespielt",
        "playingCap": "Jetzt abgespielt",
        "playlistShareText": "Schaut euch meine Wiedergabeliste an!",
        "playlists": "Wiedergabelisten",
        "popularity": "Popularität",
        "port": "Port",
        "proxySet": "Proxy-Einstellungen",
        "rememberChoice": "Meine Wahl speichern",
        "removed": "Entfernt",
        "removedFromFav": "Aus den Favoriten entfernt",
        "restore": "Wiederherstellen",
        "restoreSub":
            "Stelle deine Daten aus der Sicherung wieder her.\nMöglicherweise musst du die Anwendung neu starten\n",
        "resultsNotFound": "Keine Ergebnisse",
        "saveTheme": "Farbschema speichern",
        "search": "Suchen",
        "searchHome": "Suche-Startseite",
        "searchText": "Titel, Alben oder Künstler/innen",
        "searchVideo": "Video suchen",
        "searchYt": "Auf YouTube suchen",
        "selectBackFile": "Sicherungsdatei auswählen",
        "selectBackLocation": "Sicherungsort auswählen",
        "selectDownLocation": "Speicherort auswählen",
        "selectDur": "Eine Dauer auswählen",
        "selectJsonImport": "JSON-Datei zum Importieren auswählen",
        "shareAppSub": "Sprich deinen Freunden über uns",
        "shareAppText": "Hallo! Probier mal diese coole Musik-Player aus",
        "showHere": "Hier anzeigen",
        "showHistory": "Suchverlauf anzeigen",
        "showLastSub": "Letzte Sitzung auf dem Startbildschirm anzeigen",
        "showQr": "QR-Code anzeigen",
        "size": "Größe",
        "skip": "Überspringen",
        "skipNext": "Weiter",
        "skipPrevious": "Zum Vorherigen überspringen",
        "sleepAfterSub":
            "Die Musik wird nach einer bestimmten Anzahl von Titeln gestoppt",
        "sleepDur": "Nach einer Dauer von hh:mm stoppen",
        "sleepAfter": "Nach N Lieder stoppen",
        "sleepDurSub": "Die Musik wird nach der gewählten Dauer gestoppt",
        "sleepTimerSetFor": "Schlaf-Schaltuhr eingestellt für",
        "song": "Titel",
        "songInfo": "Titel-Infos",
        "songs": "Titel",
        "sorry": "Entschuldigung",
        "sponsor": "Unterstütze dieses Projekt",
        "spotifyPublic": "Spotify Öffentlich",
        "spotifyTopCharts": "Spotify-Top-Charts",
        "stopDown": "Stoppen",
        "stopOnClose": "Musik stoppen beim Schließen der Anwendung",
        "streamQuality": "Streaming-Qualität",
        "streamQualitySub": "Höhere Qualität erfordert mehr Daten",
        "successTagEdit": "Schlagwörter sind gearbeitet worden!",
        "supportEq": "Equalizer verwenden",
        "supportEqSub":
            "Schalte diese Option aus, wenn du keine Lieder abspielen kannst (sowohl im Online- als auch im Offline-Modus)",
        "tgCh": "Telegramm-Kanal",
        "themeDeleted": "Farbschema gelöscht!",
        "unknown": "Unbekannt",
        "unlike": "Gefällt mir nicht mehr",
        "update": "Aktualisieren",
        "updateAvailable": "Aktualisierung verfügbar!",
        "upiCopied": "UPI-ID kopiert!",
        "useAmoled": "AMOLED-Dunkler-Modus-Einstellungen verwenden",
        "useDenseMini": "Dense Mini-Player verwenden",
        "useDenseMiniSub": "Höhe des Minispielers wird reduziert",
        "useVpn": "Nicht aus Indien? Versuche es mit VPN mit indischem Server",
        "versionSub": "Tippe auf, um nach Aktualisierugen zu suchen",
        "viewAlbum": "Album ansehen",
        "welcome": "Willkommen",
        "willPlayNext": "wird als nächstes abgespielt",
        "year": "Jahr",
        "yes": "Ja",
        "yesReplace": "Ja, aber das Alte ersetzen",
        "youTube": "YouTube",
        "aboard": "an Bord",
        "accent": "Akzentfarbe und Farbton",
        "addNew": "Neu hinzufügen",
        "changeOrder": "Langer Druck zum Ändern der Reihenfolge\n",
        "about": "Über",
        "aboutLine2":
            "Wenn dir meine Arbeit gefällt\nzeige etwas ♥ und ⭐ das Repo",
        "addToQueue": "Zur Warteschlange hinzufügen",
        "albums": "Alben",
        "artist": "Künstler/in",
        "addedTo": "Hinzugefügt zu",
        "albumArtist": "Albumkünstler",
        "artists": "Künstler/innen",
        "addedToPlaylists": "Zu Wiedergabelisten hinzugefügt",
        "alreadyExists": "Existiert bereits",
        "album": "Album",
        "alphabetical": "Alphabetisch",
        "alreadyInQueue": "Bereits in Warteschlange",
        "autoBack": "Automatische Sicherung",
        "autoBackSub": "Automatisch Daten sichern",
        "autoplay": "Automatische Wiedergabe",
        "copied": "In Zwischenablage kopiert!",
        "appTitle": "BlackHole",
        "shareApp": "Anwendung teilen",
        "remove": "Entfernen",
        "selectExportLocation": "Exportort auswählen",
        "autoplaySub":
            "Verwandter Lieder zur Warteschlange automatisch hinzufügen",
        "backNRest": "Sicherung und Wiederherstellung",
        "backupSuccess": "Sicherung erfolgreich",
        "bgGrad": "Hintergrund-Farbverlauf",
        "blacklistedHomeSections":
            "Startseite-Bereiche auf der schwarzen Liste",
        "buyCoffee": "Kauf mir einen Kaffee",
        "cacheSong": "Musik in Zwischenspeicher",
        "cantAddToQueue":
            "Online-Musik kann nicht zur Offline-Warteschlange hinzugefügt werden",
        "checkUpdate": "Automatische Suche nach Aktualisierungen",
        "contactUsSub": "Rückmeldungen erwünscht!",
        "equalizer": "Klangregelung (Equalizer)",
        "prefReq": "Könntest du uns ein paar Dinge sagen?",
        "showLast": "Letzte Sitzung anzeigen",
        "back": "Zurück",
        "bgGradSub": "Überall als Hintergrund verwendeter Farbverlauf",
        "blacklistedHomeSectionsSub":
            "Abschnitte mit diesen Titeln werden auf dem Startbildschirm nicht angezeigt",
        "cardColorSub": "Farbe von Suchleiste, Warndialogen und Karten",
        "changeDefault": "Auf Standard ändern",
        "chartLocationSub": "Land für lokale Top-Spotify-Charts",
        "checkingUpdate": "Aktualisierungen werden gesucht …",
        "cache": "Zwischenspeicher",
        "cacheSongSub":
            "Die Titel werden für die zukünftige Wiedergabe zwischengespeichert. Es wird zusätzlicher Speicherplatz auf deinem Gerät belegt",
        "cancel": "Abbrechen",
        "canvasColor": "Farbe der Leinwand",
        "cardColor": "Farbe der Karte",
        "chartLocation": "Standort der lokalen Spotify-Charts",
        "checkUpdateSub":
            "Wenn du BlackHole von einem Anwendungsrepository wie F-Droid, IzzyOnDroid usw. heruntergeladen hast, das Aktualisierung-Optionen bietet, lass diese Option AUS. Wenn du BlackHole von GitHub oder einer anderen Quelle heruntergeladen hast, die keine automatischen Aktualisierungen anbietet, schalte diese Option ein, um Aktualisierungsbenachrichtigungen zu erhalten.\n",
        "clear": "Löschen",
        "clearAll": "Alles löschen",
        "clearCache": "Zwischengespeicherte Details löschen",
        "clearCacheSub":
            "Löscht zwischengespeicherte Details wie Startseite, Spotify-Top-Charts, YouTube und Daten der letzten Sitzung. Normalerweise löscht die Anwendung diese automatisch, wenn die Daten zu groß werden\n",
        "connectingRadio": "Verbindung zum Radio wird hergestellt …",
        "convertingSongs": "Konversion der Musik",
        "date": "Datum",
        "dec": "Abnehmend",
        "displayName": "Anzeigename",
        "downLyrics": "Liedtext herunterladen",
        "enableGestureSub":
            "Ermöglicht das Tippen, Wischen, Streichen usw. auf dem Kunstwerk im Player-Bildschirm",
        "enforceRepeatSub":
            "Die gleiche Wiederholungsoption für jede Sitzung beibehalten",
        "exitConfirm": "Drücke erneut auf Zurück, um die Anwendung zu beenden",
        "contactUs": "Kontakt",
        "createBackSub": "Sicherungskopie der Daten erstellen",
        "createNewPlaylist": "Neue Wiedergabeliste erstellen",
        "createYtFoldSub":
            "Erstellt einen anderen Ordner für von YouTube heruntergeladene Musik",
        "downAgain":
            "existiert bereits.\nMöchtest du sie erneut herunterladen?",
        "downed": "ist heruntergeladen worden",
        "duration": "Dauer",
        "failedCreateBackup": "Sicherung konnte nicht erstellt werden",
        "global": "Global",
        "guest": "Gast",
        "lastModified": "Zuletzt geändert",
        "lastSession": "Letzte Sitzung",
        "liveSearchSub": "Musik suchen, sobald der Benutzer aufhört zu tippen",
        "noLangSelected":
            "Keine Musiksprache ausgewählt. Wählen Sie eine Sprache, um Lieder auf dem Startbildschirm anzuzeigen",
        "removedFrom": "Entfernt von",
        "savePlaylist": "Wiedergabeliste speichern",
        "share": "Teilen",
        "spotifyCharts": "Spotify-Charts",
        "tg": "Telegram",
        "genre": "Genre",
        "genres": "Musikrichtungen",
        "gmail": "Gmail",
        "like": "Gefällt mir",
        "madeBy": "Gemacht mit ♥ von Ankit Sangwan",
        "minAudioLenSub":
            "Audios mit einer geringeren Länge werden im Bereich „Meine Musik“ nicht angezeigt",
        "moreInfo": "Mehr Infos",
        "nothingPlaying": "Nichts wird abgespielt",
        "proxySetSub": "Proxy-IP und -Port ändern",
        "rename": "Umbenennen",
        "reset": "Zurücksetzen",
        "settings": "Einstellungen",
        "sleepTimer": "Schlaf-Schaltuhr",
        "songPath": "Titelpfad",
        "themeSaved": "Farbschema gespeichert!",
        "title": "Titel",
        "version": "Version",
        "showHistorySub": "Suchverlauf unter der Suchleiste anzeigen",
        "stopOnCloseSub":
            "Wenn diese Option deaktiviert ist, wird die Musik auch nach dem Schließen der Anwendung nicht gestoppt, bis du die Stopptaste drückst. Diese Option gilt für das Schließen der Anwendung, nicht für das Schließen der Anwendung im Hintergrund. Die Musik wird immer im Hintergrund abgespielt; du brauchst dafür keine Einstellung zu ändern.\n",
        "tgGp": "Telegram-Gruppe",
        "undo": "Rückgängig",
        "useSystemTheme": "Systemfarbschema verwenden",
        "viewAll": "Alle anzeigen",
        "theme": "Farbschema",
        "trendingSearch": "Trendsuche",
        "ui": "Benutzeroberfläche",
        "watchVideo": "Video ansehen",
        "ytLiveAlert":
            "Entweder ist das Video live oder es ist ein Fehler aufgetreten. Bitte warten Sie, bis der Live-Stream beendet ist oder versuchen Sie es erneut.",
        "useDominant": "Dominante Farbe für Abspielbildschirm verwenden",
        "useDominantSub":
            "Die vorherrschende Farbe des Bildes wird für den Hintergrund des Abspielbildschirms verwendet. Wenn diese Option deaktiviert ist, wird der Standard-Hintergrundverlauf verwendet",
        "useDown": "Heruntergeladene Titel streamen, falls verfügbar",
        "useProxySub":
            "Schalten Sie diese Option ein, wenn Sie nicht aus Indien kommen und Probleme mit der Suche haben, z. B. nur indische Musik oder keine Ergebnisse erhalten usw. Sie können sogar VPN mit indischem Server verwenden\n",
        "useDominantFullScreen":
            "Dominante Farbe für den gesamten Abspielbildschirm verwenden",
        "useDownSub":
            "Wenn der Titel bereits heruntergeladen wurde, wird der heruntergeladene Titel anstelle des Online-Streamings wiedergegeben",
        "useHome":
            "Den Hauptbereich für bessere Qualität und Herunterladen-Unterstützung verwenden",
        "useProxy": "Proxy verwenden",
        "useDominantFullScreenSub":
            "Die dominante Farbe des Bildes wird für den Hintergrund des gesamten Abspielbildschirms verwendet. Nur verfügbar, wenn Dominant verwenden eingeschaltet ist",
        "shuffle": "Mischen",
        "cardGradSub": "Farbverlauf für Karten",
        "cardGrad": "Kartenfarbverlauf",
        "favSongs": "Lieblingslieder",
        "bottomGrad": "Unterer Farbverlauf",
        "bottomGradSub": "Unten verwendeter Farbverlauf",
        "viewArtist": "Künstler ansehen",
        "downFilename": "Dateinamenformat",
        "excluded": "Ausgeschlossen",
        "excludedDetails":
            "Lieder der ausgewählten Ordner werden nicht angezeigt",
        "includeExcludeFolder": "Ordner einschließen/ausschließen",
        "included": "Eingeschlossen",
        "includedDetails":
            "Nur Lieder von ausgewählten Ordnern werden angezeigt",
        "downFilenameSub":
            "Lieder werden entsprechend dieses Dateinamenformates heruntergeladen",
        "includeExcludeFolderSub":
            "Ausgewählte Ordner der „Meine Musik“-Sektion werden eingeschlossen/ausgeschlossen",
        "getLyricsOnline": "Suche nach Liedtexten lokaler Lieder",
        "getLyricsOnlineSub":
            "Suche online, wenn keine Liedtexte für ein Offline-Lied verfügbar sind oder heruntergeladen wurden",
        "importResso": "Aus Resso importieren",
        "ytStreamQuality": "YouTube-Streaming-Qualität",
        "ytDownQuality": "YouTube-Herunterladen-Qualität",
        "ytDownQualitySub": "Höhere Qualität verbraucht mehr Speicherplatz",
        "ytStreamQualitySub": "Höhere Qualität erfordert mehr Daten",
        "useDominantAndDarkerColors":
            "Dominante und dunklere Farben für den Wiedergabebildschirm verwenden",
        "useBlurForNowPlaying":
            "Unschärfe für den Hintergrund des Abschnitts „Aktuelle Wiedergabe“ verwenden",
        "useBlurForNowPlayingSub":
            "Unschärfe mit einer geringeren Deckkraft wird als Hintergrund für den Abschnitt „Aktuelle Wiedergabe“ verwendet",
        "upNext": "Als nächstes",
        "useDominantAndDarkerColorsSub":
            "Die dominante und dunklere Farbe des Bildes wird als Farbverlauf für den Hintergrund des Wiedergabebildschirms verwendet. Nur verfügbar, wenn Dominant verwenden eingeschaltet ist (bessere Ergebnisse, wenn Dominant für den gesamten Bildschirm verwenden eingeschaltet ist)",
        "confirmViewable":
            "Stellen Sie sicher, dass die Wiedergabeliste angezeigt werden kann",
        "autoBackLocation": "Speicherort der automatischen Sicherung",
        "showPlaylists": "Wiedergabelisten auf dem Startbildschirm anzeigen",
        "yourPlaylists": "Deine Wiedergabelisten",
        "resetOnSkip": "Wiederholung, wenn man zum vorherigen Lied springt",
        "resetOnSkipSub":
            "Wiederholung von Anfang an, anstatt zum vorherigen Lied zu springen",
        "importJioSaavn": "Von JioSaavn importieren",
        "playerScreenBackground": "Player-Bildschirmhintergrund",
        "playerScreenBackgroundSub":
            "Der ausgewählte Hintergrund wird im Player-Bildschirm angezeigt",
        "topCharts": "Top-Charts",
        "playRadio": "Radio abspielen",
        "importPlaylist": "Wiedergabeliste importieren",
        "mergePlaylists": "Playlists zusammenführen",
        "top": "Oben",
        "viral": "Viral",
        "openInSpotify": "In Spotify öffnen",
        "signInSpotify": "Bei Spotify anmelden",
        "shareLogs": "Protokolle teilen",
        "shareLogsSub": "Aktuelle Sitzungsprotokolle teilen",
        "radio": "Radio",
        "cantFind": "Nichts Passendes gefunden? ",
        "showTopCharts": "Top-Charts anzeigen",
        "showTopChartsSub":
            "Spotify-Top-Charts auf dem Startbildschirm anzeigen",
        "mostPlayedSong": "Meistgespieltes Lied",
        "stats": "Statistiken",
        "songsPlayed": "Gespielte Lieder",
        "compactNotificationButtons": "Kompakte Benachrichtigungsschaltflächen",
        "compactNotificationButtonsSub":
            "Schaltflächen, die in der kompakten Benachrichtigungsansicht angezeigt werden",
        "compactNotificationButtonsHeader":
            "Sie können maximal 3 Buttons auswählen",
      };
}
