class KN {
  static Map<String, String> get keys => {
        "albumArtist": "ಆಲ್ಬಂ ಕಲಾವಿದ",
        "about": "ಬಗ್ಗೆ",
        "addNew": "ಹೊಸದನ್ನು ಸೃಷ್ಟಿಸಿ",
        "addedBy": "ಇವರಿಂದ ಸೇರಿಸಲಾಗಿದೆ",
        "addedTo": "ಗೆ ಸೇರಿಸಲಾಗಿದೆ",
        "addedToPlaylists": "ಪ್ಲೇಪಟ್ಟಿಗಳಿಗೆ ಸೇರಿಸಲಾಗಿದೆ",
        "addedToQueue": "ಸಾಲಿಗೆ ಸೇರಿಸಲಾಗಿದೆ",
        "adjustSpeed": "ವೇಗವನ್ನು ಹೊಂದಿಸಿ",
        "album": "ಆಲ್ಬಮ್",
        "albums": "ಆಲ್ಬಮ್‌ಗಳು",
        "alphabetical": "ವರ್ಣಮಾಲೆಯ",
        "alreadyInQueue": "ಈಗಾಗಲೇ ಸರದಿಯಲ್ಲಿದೆ",
        "appTitle": "ಬ್ಲ್ಯಾಕ್ ಹೋಲ್",
        "artists": "ಕಲಾವಿದರು",
        "autoBack": "ಸ್ವಯಂ ಬ್ಯಾಕಪ್",
        "autoBackSub": "ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಡೇಟಾ ಬ್ಯಾಕಪ್ ಮಾಡು",
        "autoplaySub": "ಸರದಿಯಲ್ಲಿ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಂಬಂಧಿಸಿದ ಹಾಡುಗಳನ್ನು ಸೇರಿಸಿ",
        "back": "ಹಿಂದೆ",
        "backupSuccess": "ಬ್ಯಾಕಪ್ ಯಶಸ್ವಿಯಾಗಿದೆ",
        "bgGrad": "ಹಿನ್ನೆಲೆ ಗ್ರೇಡಿಯಂಟ್",
        "blacklistedHomeSections": "ಕಪ್ಪುಪಟ್ಟಿಯಲ್ಲಿರುವ ಮನೆ ವಿಭಾಗಗಳು",
        "addSomething": "ಹೊಸದನ್ನು ಸೇರಿಸಿ",
        "alreadyExists": "ಈಗಾಗಲೇ ಇದೆ",
        "backNRest": "ಬ್ಯಾಕಪ್ & ಪುನಃಸ್ಥಾಪನೆ",
        "addedToFav": "ಮೆಚ್ಚಿನವುಗಳಿಗೆ ಸೇರಿಸಲಾಗಿದೆ",
        "aboard": "ಸ್ವಾಗತ",
        "artist": "ಕಲಾವಿದ",
        "autoplay": "ಸ್ವಚಾಲಿತ",
        "bgGradSub": "ಎಲ್ಲೆಡೆ ಹಿನ್ನೆಲೆಯಾಗಿ ಬಳಸಲಾಗುವ ಗ್ರೇಡಿಯಂಟ್",
        "blacklistedHomeSectionsSub":
            "ಈ ಶೀರ್ಷಿಕೆಗಳನ್ನು ಹೊಂದಿರುವ ವಿಭಾಗಗಳನ್ನು ಹೋಮ್ ಸ್ಕ್ರೀನ್ ನಲ್ಲಿ ತೋರಿಸಲಾಗುವುದಿಲ್ಲ",
        "autoBackLocation": "ಸ್ವಯಂ ಬ್ಯಾಕಪ್ ಸ್ಥಳ",
        "addToQueue": "ಸಾಲಿಗೆ ಸೇರಿಸಿ",
        "addToPlaylist": "ಪ್ಲೇಪಟ್ಟಿಗೆ ಸೇರಿಸಿ",
        "aboutLine1": "ಇದು ತೆರೆದ ಮೂಲ ಯೋಜನೆಯಾಗಿದೆ ಮತ್ತು ಇದನ್ನು ಕಾಣಬಹುದು",
        "aboutLine2":
            "ನಿಮಗೆ ನನ್ನ ಕೆಲಸ ನಿಚ್ಚೆದಲ್ಲಿ ಕೆಲವು ♥ ಮತ್ತು ಭಂಡಾರವನ್ನು⭐ ಮಾಡಿ",
        "accent": "ಉಚ್ಚಾರಣೆ ಬಣ್ಣ ಮತ್ತು ವರ್ಣ",
      };
}
