import 'package:get/route_manager.dart';

import 'app_ar.dart';
import 'app_be.dart';
import 'app_bn.dart';
import 'app_cs.dart';
import 'app_da.dart';
import 'app_de.dart';
import 'app_el.dart';
import 'app_en.dart';
import 'app_es.dart';
import 'app_fa.dart';
import 'app_fr.dart';
import 'app_gu.dart';
import 'app_he.dart';
import 'app_hi.dart';
import 'app_hu.dart';
import 'app_id.dart';
import 'app_it.dart';
import 'app_ja.dart';
import 'app_kn.dart';
import 'app_ko.dart';
import 'app_ml.dart';
import 'app_mn.dart';
import 'app_mr.dart';
import 'app_ne.dart';
import 'app_nl.dart';
import 'app_or.dart';
import 'app_pa.dart';
import 'app_peo.dart';
import 'app_pl.dart';
import 'app_pt.dart';
import 'app_ru.dart';
import 'app_sq.dart';
import 'app_sv.dart';
import 'app_ta.dart';
import 'app_tr.dart';
import 'app_uk.dart';
import 'app_ur.dart';
import 'app_vi.dart';
import 'app_zh.dart';
import 'app_zh_d.dart';
import 'app_zh_t.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": AR.keys,
        "be": BE.keys,
        "bn": BN.keys,
        "cs": CS.keys,
        "da": DA.keys,
        "de": DE.keys,
        "el": EL.keys,
        "en": EN.keys,
        "es": ES.keys,
        "fa": FA.keys,
        "fr": FR.keys,
        "gu": GU.keys,
        "he": HE.keys,
        "hi": HI.keys,
        "hu": HU.keys,
        "id": ID.keys,
        "it": IT.keys,
        "ja": JA.keys,
        "kn": KN.keys,
        "ko": KO.keys,
        "ml": ML.keys,
        "mn": MN.keys,
        "mr": MR.keys,
        "ne": NE.keys,
        "nl": NL.keys,
        "or": OR.keys,
        "pa": PA.keys,
        "peo": PEO.keys,
        "pl": PL.keys,
        "pt": PT.keys,
        "ru": RU.keys,
        "sq": SQ.keys,
        "sv": SV.keys,
        "ta": TA.keys,
        "tr": TR.keys,
        "uk": UK.keys,
        "ur": UR.keys,
        "vi": VI.keys,
        "zh": ZH.keys,
        "zhd": ZHHANS.keys,
        "zht": ZHHANT.keys,
      };
}
